"""Adjectives for display handles — see handles/__init__.py.

Curated by hand: every word is <=5 characters, a plain positive or neutral
character trait, and checked against every pioneer surname in pioneers.py for
a bad combination before landing. Nothing here is slang, an insult, or a word
that reads as mocking once it is stuck in front of a person's name.
"""

from __future__ import annotations

ADJECTIVES: tuple[str, ...] = (
    "able",
    "agile",
    "alert",
    "avid",
    "bold",
    "brave",
    "brisk",
    "calm",
    "clean",
    "clear",
    "cool",
    "deft",
    "eager",
    "easy",
    "exact",
    "fair",
    "fast",
    "fine",
    "firm",
    "fleet",
    "free",
    "fresh",
    "good",
    "grand",
    "great",
    "handy",
    "hardy",
    "just",
    "keen",
    "kind",
    "lean",
    "light",
    "loyal",
    "lucky",
    "merry",
    "neat",
    "nice",
    "noble",
    "proud",
    "pure",
    "quick",
    "quiet",
    "rapid",
    "ready",
    "rich",
    "right",
    "sharp",
    "shiny",
    "smart",
    "sober",
    "solid",
    "sound",
    "stout",
    "sunny",
    "super",
    "sure",
    "swift",
    "tidy",
    "tough",
    "true",
    "warm",
    "wise",
    "witty",
    "zesty",
)
