"""Pioneer surnames for display handles — see handles/__init__.py.

Curated by hand: every entry is a real computing pioneer's surname, spelled
correctly, <=7 characters. The set favours people who are actually foundational
(languages, algorithms, hardware, networking, cryptography, graphics, AI) over
recent business figures, and was screened for surnames that read badly once
paired with an adjective (a slang homophone, a loaded political name, a plain
English word that clashes) — those pioneers are real but their names are left
out on purpose.
"""

from __future__ import annotations

PIONEERS: tuple[str, ...] = (
    "Adleman",
    "Aiken",
    "Allen",
    "Amdahl",
    "Babbage",
    "Backus",
    "Baran",
    "Bartik",
    "Bengio",
    "Berry",
    "Blinn",
    "Bloch",
    "Blum",
    "Boole",
    "Bourne",
    "Brin",
    "Catmull",
    "Cerf",
    "Chen",
    "Clark",
    "Codd",
    "Cook",
    "Cray",
    "Crocker",
    "Curry",
    "Cutler",
    "Davies",
    "Diffie",
    "Eckert",
    "Eich",
    "Estrin",
    "Filo",
    "Flowers",
    "Floyd",
    "Gates",
    "Geschke",
    "Gosling",
    "Gray",
    "Grove",
    "Hamming",
    "Hellman",
    "Hinton",
    "Hopper",
    "Iverson",
    "Jobs",
    "Kahn",
    "Karp",
    "Kay",
    "Kemeny",
    "Kilby",
    "Kildall",
    "Knuth",
    "Kurtz",
    "Lamport",
    "LeCun",
    "Lerdorf",
    "Liskov",
    "Mauchly",
    "Merkle",
    "Minsky",
    "Moore",
    "Nelson",
    "Neumann",
    "Newell",
    "Noyce",
    "Olsen",
    "Page",
    "Papert",
    "Perlis",
    "Perlman",
    "Pike",
    "Postel",
    "Rabin",
    "Raymond",
    "Ritchie",
    "Rivest",
    "Roberts",
    "Sammet",
    "Samuel",
    "Shamir",
    "Shannon",
    "Simon",
    "Tarjan",
    "Taylor",
    "Turing",
    "Tutte",
    "Wall",
    "Warnock",
    "Watson",
    "Wilkes",
    "Wirth",
    "Wozniak",
    "Yang",
    "Yao",
    "Zuse",
)
