// DO NOT EDIT — generated by scripts/stations-registry.py generate from
// registry/stations/*.json + registry/registry-v1.json; run `make station-registry-generate`.
import type { RuntimeVMManifestEntry } from '../types';

// ============================================================================
//  ARCHETYPE + TRANSPORT REGISTRY
//  ---------------------------------------------------------------------------
//  Generated view (source of truth: registry/stations/*.json) mapping every OS to:
//    - archetypeId : which era-accurate model renders it
<<<<<<< HEAD
//    - transport   : how its LIVE framebuffer texture is obtained (77 of the 79
=======
//    - transport   : how its LIVE framebuffer texture is obtained (78 of the 80
>>>>>>> origin/main
//                    bindings are streamhost — WebTransport + WebCodecs against
//                    the Rust daemon, signaled same-origin via /signal/<osId>.json)
//    - accentColor : OS accent
//    - eraLabel    : placard line
//
// ============================================================================

export type ArchetypeId =
  | 'beige-ibm-pc'      // boxy DOS-era CRT + IBM-PC (Win3.11, FreeDOS, DOS)
  | 'beige-tower-crt'   // mid/late-90s tower + curvy CRT (Win95/98/2000, Serenity, Kolibri)
  | 'putty-lcd'         // early-2000s putty/graphite PC + flat CRT/LCD (WinXP, Toaru, Alpine, TinyCore)
  | 'sparc-pizzabox'    // Sun SPARCstation pizza-box + CRT (Solaris CDE)
  | 'mono-terminal'     // monochrome Bell-Labs/DEC terminal (9front, HelenOS)
  | 'touch-phone'       // era touchscreen smartphone (Android, postmarketOS, Sailfish)
  | 'apple-studio';     // modern Apple all-in-one / Studio Display (macOS)

export type Transport =
  | 'streamhost'    // from-scratch WebTransport+WebCodecs client (~6x lower latency)
  | 'showcase';     // poster/placard only — no connection attempt

export interface OSBinding {
  osId: string;
  displayName?: string;
  archetypeId: ArchetypeId;
  transport: Transport;
  /** Optional manifest-provided endpoint retained for forward-compatible transports. */
  endpoint?: string;
  accentColor: string;
  eraLabel: string;
  /**
   * OPTIONAL streamhost signaling endpoint (HTTP GET → { url, certHashB64,
   * wireVersion?, audio? } or a bare base64 hash). Only consulted when this tile
   * is on the `streamhost` transport; when omitted the client falls back to the
   * SAME-ORIGIN `/signal/<osId>.json` served by the HTTPS SPA server (see
   * streamSignal.streamhostSignalFor) — which is what every live tile uses.
   */
  signalEndpoint?: string;
  /**
   * COLD-BOOT-ON-VISIT flag — the SPA↔tile CONTRACT for the power-on experience.
   * ---------------------------------------------------------------------------
   * When TRUE, this tile does NOT resume an already-booted golden — the host
   * launcher powers the guest ON FROM POST on each visit (fresh ephemeral overlay,
   * BIOS/POST → boot menu → OS splash + startup sounds → desktop) and powers it
   * OFF when the last visitor leaves. The SPA reads this flag to swap the generic
   * "Connecting…" spinner for the dramatic CRT power-on treatment (PowerOnOverlay
   * in StreamView) so the visitor SEES + HEARS the machine warming up, framing the
   * incoming live POST frames as a real vintage boot. Boot AUDIO rides the normal
   * path (setAudioEnabled(true) on control-connect → Opus uni-stream, un-gated;
   * the click that opened the tile is the autoplay gesture).
   *
   * OWNERSHIP: the per-tile BACKEND agent that converts a tile to cold-boot-on-
   * visit sets this to `true` here for that tile id (single source of truth the
   * SPA reads synchronously at mount — no signal round-trip, so the warm-up shows
   * the instant the tile opens). Omitted / false ⇒ the tile behaves exactly as
   * today (instant resume + plain spinner); the power-on treatment is strictly
   * additive and flag-gated, so non-cold-boot tiles are never affected.
   */
  coldBoot?: boolean;
  /**
   * RELATIVE-POINTER flag — mirrors the daemon's per-tile `SH_POINTER=rel`
   * (tiles.json `pointer_mode: "rel"`). These guests own a PS/2-style relative
   * mouse with NO absolute-position API, so the daemon cannot SetAbsPosition —
   * it must feed Mouse.RelMotion deltas. When TRUE and the SPA holds Pointer
   * Lock, the locked-move handler sends the raw per-event movementX/Y as a
   * type=4 DIRECT RelMotion datagram (client.sendMoveRel → input.rs case 4 →
   * rel_motion), giving real 1:1 tracking with the guest rendering its own
   * cursor. This BYPASSES the old abs→rel homing bridge (send abs point → daemon
   * diffs against last position → RelMotion of the difference), which emitted
   * huge deltas on the first move / after any warp that QEMU's PS/2 accel
   * clamped, leaving the cursor stuck (the QNX frozen-cursor bug). Omitted /
   * false ⇒ ABSOLUTE tiles keep the accumulated-virtual-cursor + sendMoveAbs
   * path unchanged. Only meaningful for streamhost tiles under pointer lock.
   */
  pointerRel?: boolean;
  /** Show the grid's hardware-input badge for a native guest input device. */
  hardwareInput?: boolean;
  /** Show the grid's relative-pointer warning badge: the exhibit is graphical
   *  and takes a pointer, but only a RELATIVE one, so the cursor cannot track
   *  the visitor 1:1. Derived from stream.pointer, not from spa.pointerRel. */
  relativePointerOnly?: boolean;
  /**
   * BOOT-VIDEO REPLAY — same-origin URL of this tile's recorded power-on clip
   * (`/boot/<osId>/boot.mp4`, baked out-of-band; NOT bundled/committed). When
   * set, the SPA plays it in a scrubbable `<video>` (BootVideoOverlay) while the
   * live golden readies behind it, then swaps invisibly on the first live frame
   * (the clip's last frame === golden first frame — the seamless-handoff
   * invariant). This flag is BOTH the grid "▶ Boot" badge signal AND the mount
   * selector + the `<video src>` in StreamView. Sibling assets (poster.jpg,
   * sprite.jpg, thumbs.vtt) are resolved by convention from this path. Omitted
   * ⇒ today's behaviour (PowerOnOverlay when coldBoot, else the plain spinner);
   * the boot-video treatment is strictly additive and flag-gated. Paths/durations
   * may also arrive at runtime via /boot/index.json (VMManifestEntry.bootVideo).
   */
  bootVideo?: string;
  /** STATION-TYPE grouping dimensions, carried through from the manifest so
   *  telemetry call sites that only have an `OSBinding` (not the full
   *  manifest row) can still stamp them — see analytics/stationAttrs.ts. */
  emulatorFamily?: string;
  uiKind?: string;
  resetMode?: string;
}

<<<<<<< HEAD
// One entry per OS. 77 rows are streamhost; 2 are showcase posters.
=======
// One entry per OS. 78 rows are streamhost; 2 are showcase posters.
>>>>>>> origin/main
export const OS_BINDINGS: Record<string, OSBinding> = {
  // ---- streamhost tiles (WebTransport + WebCodecs; signaled via /signal/<osId>.json) ----
  freedos:     { osId: 'freedos', archetypeId: 'beige-ibm-pc', transport: 'streamhost', accentColor: '#5fa85f', eraLabel: '1994 · DOS era', pointerRel: true },
  kolibrios:   { osId: 'kolibrios', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#39c6d6', eraLabel: '2004 · asm GUI OS' },
  toaruos:     { osId: 'toaruos', archetypeId: 'putty-lcd', transport: 'streamhost', accentColor: '#c98b3a', eraLabel: '2011 · hobby UNIX' },
  win311:      { osId: 'win311', archetypeId: 'beige-ibm-pc', transport: 'streamhost', accentColor: '#7fb0d6', eraLabel: '1993 · Windows 3.11' },
  win95:       { osId: 'win95', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#2f8f5b', eraLabel: '1995 · Windows 95', bootVideo: '/boot/win95/boot.mp4' },
  win98se:     { osId: 'win98se', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#3a7fc9', eraLabel: '1999 · Windows 98 SE', bootVideo: '/boot/win98se/boot.mp4' },
  win2000:     { osId: 'win2000', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#5b6fc9', eraLabel: '2000 · Windows 2000', bootVideo: '/boot/win2000/boot.mp4' },
  winxp:       { osId: 'winxp', archetypeId: 'putty-lcd', transport: 'streamhost', accentColor: '#5aa832', eraLabel: '2001 · Windows XP' },
  alpine:      { osId: 'alpine', archetypeId: 'putty-lcd', transport: 'streamhost', accentColor: '#0d597f', eraLabel: '2005 · Alpine Linux' },
  tinycore:    { osId: 'tinycore', archetypeId: 'putty-lcd', transport: 'streamhost', accentColor: '#4a9fd6', eraLabel: '2009 · Tiny Core' },
  ninefront:   { osId: 'ninefront', archetypeId: 'mono-terminal', transport: 'streamhost', accentColor: '#c9c05b', eraLabel: '2011 · 9front (Plan 9)', bootVideo: '/boot/ninefront/boot.mp4' },
  helenos:     { osId: 'helenos', archetypeId: 'mono-terminal', transport: 'streamhost', accentColor: '#b58fd6', eraLabel: '2006 · HelenOS' },
  solaris:     { osId: 'solaris', archetypeId: 'sparc-pizzabox', transport: 'streamhost', accentColor: '#d68a3a', eraLabel: '1994 · Solaris CDE', hardwareInput: true, bootVideo: '/boot/solaris/boot.mp4' },
  nt351:       { osId: 'nt351', archetypeId: 'beige-ibm-pc', transport: 'streamhost', accentColor: '#3a6ea5', eraLabel: '1995 · Windows NT 3.51' },
  serenityos:  { osId: 'serenityos', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#c95a8f', eraLabel: '2018 · SerenityOS' },
  android:     { osId: 'android', archetypeId: 'touch-phone', transport: 'streamhost', accentColor: '#3ddc84', eraLabel: '2008 · Android' },
  postmarketos:{ osId: 'postmarketos', archetypeId: 'touch-phone', transport: 'streamhost', accentColor: '#008b4b', eraLabel: '2017 · postmarketOS' },
  sailfishos:  { osId: 'sailfishos', archetypeId: 'touch-phone', transport: 'streamhost', accentColor: '#e60d42', eraLabel: '2013 · Sailfish (Jolla)' },
  templeos:    { osId: 'templeos', archetypeId: 'beige-ibm-pc', transport: 'streamhost', accentColor: '#f2c14e', eraLabel: '2013 · TempleOS' },
  reactos:     { osId: 'reactos', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#2f6fba', eraLabel: '2024 · ReactOS 0.4.14' },
  haiku:       { osId: 'haiku', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#ffca3a', eraLabel: '2024 · Haiku R1/beta5', bootVideo: '/boot/haiku/boot.mp4' }, // ideal: BeBox
  os2warp:     { osId: 'os2warp', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#1e5aa8', eraLabel: '1996 · OS/2 Warp 4', bootVideo: '/boot/os2warp/boot.mp4' },
  aros:        { osId: 'aros', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#e87a17', eraLabel: '2024 · AROS (Amiga)' }, // ideal: Amiga wedge
  qnx:         { osId: 'qnx', archetypeId: 'putty-lcd', transport: 'streamhost', accentColor: '#1b6fb5', eraLabel: '2010 · QNX Neutrino 6.5', pointerRel: true },
  msdoswin1:   { osId: 'msdoswin1', archetypeId: 'beige-ibm-pc', transport: 'streamhost', accentColor: '#c8a24a', eraLabel: '1994 · MS-DOS 6.22 + Win 1.0', pointerRel: true },

  // ---- emulator-bridge retro home computers (captured-Linux kiosk running a
  //      period emulator; streamhost captures the Linux framebuffer + AC97.
  //      See streamhost/docs/BRIDGE.md. beige-tower-crt is the closest era
  //      archetype; bespoke breadbin/wedge/all-in-one models are the ideal
  //      follow-ups). ----
  c64:         { osId: 'c64', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#6c5eb5', eraLabel: '1982 · C64 + GEOS' },
  atarist:     { osId: 'atarist', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#E4002B', eraLabel: '1985 · Atari ST (GEM)' },
  apple2:      { osId: 'apple2', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#8A8577', eraLabel: '1988 · Apple II — GEOS' },
  amiga:       { osId: 'amiga', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#0055AA', eraLabel: '1987 · Amiga Workbench 1.3', bootVideo: '/boot/amiga/boot.mp4' },
  win11:       { osId: 'win11', archetypeId: 'apple-studio', transport: 'streamhost', accentColor: '#2d9bd6', eraLabel: '2021 · Windows 11' },

  // ---- riscos — SHOWCASE poster. RISC OS is ARM (the old tile streamed RPCEmu
  // through the now-deleted neko plane at :8111), so it has no QEMU streamhost
  // tile yet; poster + placard only, no connection attempt. // ideal: Acorn RiscPC
  riscos:      { osId: 'riscos', archetypeId: 'beige-tower-crt', transport: 'showcase', accentColor: '#4a7c3a', eraLabel: '2022 · RISC OS 5.30' },

  // ---- macos — SHOWCASE poster. VM 925 (the macOS guest) was destroyed
  // 2026-07-14 along with its VNC->WebSocket bridge (ws :8115 / wss :8116), so
  // there is nothing to connect to; poster + placard only, no connection attempt.
  macos:       { osId: 'macos', archetypeId: 'apple-studio', transport: 'showcase', accentColor: '#a0a0a8', eraLabel: '2024 · macOS Sequoia' },
  redstar2:    { osId: 'redstar2', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#c8102e', eraLabel: '2009 · Red Star OS 2.0', bootVideo: '/boot/redstar2/boot.mp4' },
  redstar3:    { osId: 'redstar3', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#b3202a', eraLabel: '2013 · Red Star OS 3.0', bootVideo: '/boot/redstar3/boot.mp4' },
  amstradcpc:  { osId: 'amstradcpc', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#F0C000', eraLabel: '1985 · CPC 6128 (Locomotive BASIC)' },
  nt4:         { osId: 'nt4', archetypeId: 'putty-lcd', transport: 'streamhost', accentColor: '#1f7a7a', eraLabel: '1996 · Windows NT 4.0' },
  openvms:     { osId: 'openvms', archetypeId: 'putty-lcd', transport: 'streamhost', accentColor: '#00a6d6', eraLabel: '2024 · OpenVMS 9.2 · DECwindows' },
  irix:        { osId: 'irix', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#5B8FA8', eraLabel: '1993 · SGI Indy — IRIX 6.5', bootVideo: '/boot/irix/boot.mp4' },
  mpf2:        { osId: 'mpf2', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#8B4513', eraLabel: '1982 · MPF-II BASIC' },
  vic20:       { osId: 'vic20', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#3FBFC7', eraLabel: '1980 · VIC-20 (CBM BASIC V2)' },
  plus4:       { osId: 'plus4', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#C2CF5F', eraLabel: '1984 · Plus/4 (3-plus-1 in ROM)' },
  c128:        { osId: 'c128', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#7FD4C1', eraLabel: '1985 · C128 (80-column BASIC 7.0 · CP/M 3.0)' },
  pet2001:     { osId: 'pet2001', archetypeId: 'mono-terminal', transport: 'streamhost', accentColor: '#AEB8F0', eraLabel: '1977 · PET 2001 (COMMODORE BASIC)' },
  cbm8032:     { osId: 'cbm8032', archetypeId: 'mono-terminal', transport: 'streamhost', accentColor: '#41FF00', eraLabel: '1980 · CBM 8032 (BASIC 4.0, 80 columns)' },
  cbm2:        { osId: 'cbm2', archetypeId: 'beige-ibm-pc', transport: 'streamhost', accentColor: '#55D544', eraLabel: '1982 · CBM 610 (BASIC 128, 6509)' },
  pdp11:       { osId: 'pdp11', archetypeId: 'mono-terminal', transport: 'streamhost', accentColor: '#9A4F96', eraLabel: '1975 · PDP-11/70 (2.11BSD)' },
  gt40:        { osId: 'gt40', archetypeId: 'mono-terminal', transport: 'streamhost', accentColor: '#3BE84B', eraLabel: '1973 · GT40 (VT11 vector, light pen)' },
  decos:       { osId: 'decos', archetypeId: 'mono-terminal', transport: 'streamhost', accentColor: '#7A5CC4', eraLabel: '1970 · PDP-11 · RT-11 / RSX-11M / RSTS-E' },
  zxspectrum:  { osId: 'zxspectrum', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#CD0000', eraLabel: '1982 · ZX Spectrum 48K' },
  zx81:        { osId: 'zx81', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#D8462F', eraLabel: '1981 · ZX81 (1 KB, black and white)' },
  bbcmicro:    { osId: 'bbcmicro', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#D8442F', eraLabel: '1981 · BBC Micro Model B (BBC BASIC II)' },
  dragon32:    { osId: 'dragon32', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#30D200', eraLabel: '1982 · Dragon 32 (Microsoft BASIC)' },
  oricatmos:   { osId: 'oricatmos', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#D8402F', eraLabel: '1984 · Oric Atmos (Extended BASIC V1.1)' },
  kc854:       { osId: 'kc854', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#3FD8D0', eraLabel: '1988 · KC 85/4 (CAOS 4.2)' },
  sinclairql:  { osId: 'sinclairql', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#2EE65A', eraLabel: '1984 · Sinclair QL (QDOS · SuperBASIC)' },
  nextstep:    { osId: 'nextstep', archetypeId: 'mono-terminal', transport: 'streamhost', accentColor: '#8C8C8C', eraLabel: '1995 · NeXTSTEP 3.3 (NeXTcube)' },
  armeval:     { osId: 'armeval', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#0000FF', eraLabel: '1986 · ARM Evaluation System (ARM BBC Basic V)' },
  indyr4400:   { osId: 'indyr4400', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#3E6E9E', eraLabel: '1993 · SGI Indy R4400 — IRIX 6.5', pointerRel: true },
  alto:        { osId: 'alto', archetypeId: 'mono-terminal', transport: 'streamhost', accentColor: '#9FE3EA', eraLabel: '1973 · Alto II XM (portrait page display)' },
  star:        { osId: 'star', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#D6001C', eraLabel: '1981 · Pilot + ViewPoint 2.0 on the 8010', pointerRel: true },
  daybreak:    { osId: 'daybreak', archetypeId: 'sparc-pizzabox', transport: 'streamhost', accentColor: '#C8102E', eraLabel: '1985 · ViewPoint 2.0.5 on the 6085' },
  w2kalpha:    { osId: 'w2kalpha', archetypeId: 'putty-lcd', transport: 'streamhost', accentColor: '#862633', eraLabel: '1999 · Windows 2000 RC2 — Alpha AXP' },
  tru64:       { osId: 'tru64', archetypeId: 'putty-lcd', transport: 'streamhost', accentColor: '#2f6a9b', eraLabel: '2003 · Tru64 UNIX 5.1B — Alpha' },
  macos753:    { osId: 'macos753', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#8c8a85', eraLabel: '1996 · Mac OS 7.5.3 — Quadra 800', pointerRel: false },
  hpuxvue:     { osId: 'hpuxvue', archetypeId: 'sparc-pizzabox', transport: 'streamhost', accentColor: '#5b7c99', eraLabel: '1996 · HP-UX 10.20 — HP VUE', pointerRel: false },
  beos:        { osId: 'beos', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#3466a0', eraLabel: '2000 · BeOS R5 Professional', pointerRel: false }, // BeOS<->Haiku pairing
  newsos:      { osId: 'newsos', archetypeId: 'putty-lcd', transport: 'streamhost', accentColor: '#7a6f9b', eraLabel: '1991 · NEWS-OS 4.1R — Sony NWS-3260', pointerRel: false },
  sunos414:    { osId: 'sunos414', archetypeId: 'sparc-pizzabox', transport: 'streamhost', accentColor: '#7c3aed', eraLabel: '1994 · SunOS 4.1.4 — OpenWindows', pointerRel: false },
  aux:         { osId: 'aux', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#6b7f8e', eraLabel: '1993 · A/UX 3.0.1 — Quadra 800', pointerRel: true },
  rhapsody:    { osId: 'rhapsody', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#7a8fb0', eraLabel: '1998 · Rhapsody DR2 — Apple/NeXT', pointerRel: false }, // NeXTSTEP -> Rhapsody -> Mac OS X lineage
  chokanji:    { osId: 'chokanji', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#2f6fb0', eraLabel: '2002 · 超漢字 / BTRON3', pointerRel: true },
  macos9:      { osId: 'macos9', archetypeId: 'apple-studio', transport: 'streamhost', accentColor: '#9a9ad1', eraLabel: '2001 · Mac OS 9.2.2 — Power Mac G4', pointerRel: true },
  amigaos35:   { osId: 'amigaos35', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#CC4444', eraLabel: '1999 · AmigaOS 3.5 (AWeb II)' }, // ideal: Amiga big-box tower
  aix432:      { osId: 'aix432', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#2f6ea8', eraLabel: '1999 · IBM RS/6000 — AIX 4.3.3 / CDE', pointerRel: false },
  ravynos:     { osId: 'ravynos', archetypeId: 'apple-studio', transport: 'streamhost', accentColor: '#64748b', eraLabel: '2025 · ravynOS 0.6.1' }, // ideal: any 2020s PC — the point is that it is not a Mac
  amix:        { osId: 'amix', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#7A8B99', eraLabel: '1992 · Amiga UNIX (AMIX) 2.1' }, // ideal: Amiga 3000 desktop box
  bootos:      { osId: 'bootos', archetypeId: 'beige-ibm-pc', transport: 'streamhost', accentColor: '#8ecae6', eraLabel: '2019 · 512-byte boot-sector OS' },
  pcgeos:      { osId: 'pcgeos', archetypeId: 'beige-ibm-pc', transport: 'streamhost', accentColor: '#e08a3c', eraLabel: '1993 · GeoWorks Ensemble', pointerRel: false },
<<<<<<< HEAD
  slackware:   { osId: 'slackware', archetypeId: 'putty-lcd', transport: 'streamhost', accentColor: '#008080', eraLabel: '1997 · Slackware 3.4 — fvwm95', pointerRel: true },
=======
  pcbsd:       { osId: 'pcbsd', archetypeId: 'putty-lcd', transport: 'streamhost', accentColor: '#2f6fba', eraLabel: '2008 · PC-BSD 1.5.1', pointerRel: true },
  ubuntu:      { osId: 'ubuntu', archetypeId: 'beige-tower-crt', transport: 'streamhost', accentColor: '#dd4814', eraLabel: '2004 · Ubuntu 4.10 Warty Warthog' },
>>>>>>> origin/main
};

/** Adapt one validated runtime manifest row to the existing streaming seam. */
export function bindingFromManifest(vm: RuntimeVMManifestEntry): OSBinding {
  return {
    osId: vm.id,
    displayName: vm.displayName,
    archetypeId: vm.archetypeId,
    transport: vm.transport,
    endpoint: vm.endpoint,
    accentColor: vm.accent ?? '#8891a6',
    eraLabel: vm.eraLabel,
    signalEndpoint: vm.signalEndpoint ?? undefined,
    coldBoot: vm.coldBoot,
    pointerRel: vm.pointerRel,
    hardwareInput: vm.hardwareInput,
    relativePointerOnly: vm.relativePointerOnly,
    bootVideo: vm.bootVideo?.mp4,
    emulatorFamily: vm.emulatorFamily,
    uiKind: vm.uiKind,
    resetMode: vm.resetMode,
  };
}
