#!/bin/bash
# DO NOT EDIT — generated by scripts/stations-registry.py generate from
# registry/stations/*.json + registry/registry-v1.json; run `make station-registry-generate`.
# bring-up-all.sh — ordered boot of the registry's 76 production streamhost tiles
# gallery after a from-scratch NVMe rebuild. Run ON the host as root.
#
# Grounded in the real host layout:
#   /data/vms/streamhost/{scripts,deploy,serve,tiles}/  (scripts/deploy/tiles are
#     mirrored from this streamhost/ tree; serve/ is mirrored from the repo's
#     scripts/serve/ — see docs/lab/MASTER-REPRODUCE.md Phase 5)
#   built streamhost binary at /data/vms/streamhost/build/target/release/streamhost
#   guest images under /data/gallery-guests/ (+ a couple of odd paths, see below)
#
# Order per tile:  emit files  ->  launch its QEMU (nohup, by pidfile)  ->  wait
# for its QMP socket  ->  systemctl start streamhost@<tile> (attaches to QMP,
# serves its UDP port, mints+publishes its WebTransport cert hash).
#
# This is NOT expected to run unattended end-to-end on a cold box (guest images
# must be present first — see the EXTERNAL DEPENDENCIES list at the bottom), but
# it is a faithful, ordered recipe. Set DRY_RUN=1 to print without executing.
set -u

REPO="/data/vms/streamhost" # where this repo is checked out on the host
SCRIPTS="$REPO/scripts/streamhost-station.sh"
UNIT_SRC="$REPO/deploy/streamhost@.service"
SERVE="$REPO/serve"
TILESDIR="$REPO/stations"
DRY_RUN="${DRY_RUN:-0}"
# SIGNAL_HOST defaults to the repo's public placeholder (RFC 5737, unroutable).
# Export the real value first (e.g. `set -a; . /path/to/repo/registry/local.env;
# set +a` — see registry/README.md) or pass SIGNAL_HOST= on the command line.
SIGNAL_HOST="${SIGNAL_HOST:-${SH_HOST_IP:-192.0.2.10}}"

run() {
  echo "+ $*"
  [ "$DRY_RUN" = 1 ] || "$@"
}

# All 76 production tile-dir names, in a sane boot order (light guests first; the four
# emulator-bridge kiosks last — they're the heaviest and launch in qcap scopes).
TILES=(
  alpine tinycore reactos toaruos haiku beos rhapsody
  aros helenos kolibrios ninefront bootos pcgeos
  android solaris redstar3
  win2000 winxp nt4 nt351 openvms win11
  win311 win95 win98se freedos msdoswin1 os2warp
  qnx sailfishos templeos serenityos postmarketos
  c64 atarist apple2 amiga redstar2 amstradcpc mpf2 vic20 plus4 c128 pet2001 cbm8032 cbm2 pdp11 gt40 decos zxspectrum zx81 bbcmicro dragon32 oricatmos kc854 sinclairql nextstep armeval indyr4400 alto star daybreak
  irix w2kalpha tru64 macos753 hpuxvue newsos sunos414 aux
  chokanji macos9 amigaos35 aix432 ravynos amix
)

# ---------------------------------------------------------------------------
# 0. Preconditions
# ---------------------------------------------------------------------------
echo "== step 0: preconditions =="
[ -x "$SCRIPTS" ] || {
  echo "FATAL: $SCRIPTS missing (sync repo->host first)"
  exit 1
}
# The serve plane (step 6: :8443 HTTPS SPA + signaling) is NOT part of the
# streamhost/ tree — its canonical source is the repo's scripts/serve/. Fail loud
# now rather than booting the fleet and silently skipping the serve plane.
[ -f "$SERVE/osgallery-https-server.py" ] || {
  cat >&2 <<EOF
FATAL: $SERVE/osgallery-https-server.py missing.
Copy the repo's scripts/serve/ to $SERVE first — see
docs/lab/MASTER-REPRODUCE.md Phase 5 (serve plane). Without it step 6 cannot
start the :8443 HTTPS SPA + signaling server.
EOF
  exit 1
}
[ -x "$REPO/build/target/release/streamhost" ] ||
  echo "WARN: streamhost binary not built yet -> (cd $REPO/build && cargo build --release)"
# /root/qmp_hmp.py: runtime dep of the alpine/tinycore launchers (post-boot QMP
# hostfwd_add) and the bridge/amiga builders. Canonical source: scripts/qmp_hmp.py.
if [ ! -f /root/qmp_hmp.py ]; then
  run install -m 644 "$REPO/scripts/qmp_hmp.py" /root/qmp_hmp.py
fi

# ---------------------------------------------------------------------------
# 1. Install the systemd template unit (once)
# ---------------------------------------------------------------------------
echo "== step 1: install systemd unit =="
run cp "$UNIT_SRC" /etc/systemd/system/streamhost@.service
run systemctl daemon-reload

# ---------------------------------------------------------------------------
# 2. Emit every tile's files from the manifest (station.env + qemu-streamhost.sh)
# ---------------------------------------------------------------------------
echo "== step 2: emit all 76 production tiles' config =="
# On a FRESH NVMe rebuild run this whole script with SH_PIN_MACHINE=1 so the
# manifest emits versioned machine types (pc-i440fx-11.0 / pc-q35-11.0) and the
# new goldens are immune to a future QEMU alias retarget. The live dry-run box
# keeps the default (unpinned) emit for byte-parity with its baked goldens —
# see scripts/dev/verify-emit.sh, the launcher-parity gate.
run bash "$REPO/stations-manifest.sh"

# ---------------------------------------------------------------------------
# 3. Per-tile special-case pre-seeding
# ---------------------------------------------------------------------------
echo "== step 3: per-tile pre-seed =="
# postmarketos: writable qcow2 UEFI varstore. stations-manifest.sh already seeds it
# post-emit (qemu-img convert of OVMF_VARS_4M.fd); this is an idempotent safety
# net for a bring-up after a manifest run on a box without the firmware package.
if [ ! -f "$TILESDIR/postmarketos/OVMF_VARS.qcow2" ]; then
  run qemu-img convert -f raw -O qcow2 /usr/share/pve-edk2-firmware/OVMF_VARS_4M.fd \
    "$TILESDIR/postmarketos/OVMF_VARS.qcow2"
fi
# serenityos: no pre-seed needed — its (verbatim) qemu-streamhost.sh recreates
# the fresh per-boot writable qcow2 overlay over the RO golden raw ext2 root
# itself, every launch (resetMode=restart).

# ---------------------------------------------------------------------------
# 4. For each tile: launch QEMU, wait for QMP, start the streamhost daemon
# ---------------------------------------------------------------------------
echo "== step 4: launch QEMU + streamhost per tile =="
wait_qmp() { # $1 = tile dir
  local sock="$TILESDIR/$1/qmp.sock"
  for _ in $(seq 1 40); do
    [ -S "$sock" ] && return 0
    sleep 0.5
  done
  echo "WARN: $1 QMP socket never appeared ($sock)"
  return 1
}

for t in "${TILES[@]}"; do
  echo "--- tile: $t ---"
  skip_qmp=0
  case "$t" in
  irix | c64 | atarist | apple2 | amiga)
    # The qcap-scope tiles: the IRIX x11-runtime tile (issue #20, not QEMU at
    # all — no QMP socket ever appears, hence skip_qmp) and the four
    # emulator-bridge kiosks. All five put their guest in a 3 GiB
    # `systemd-run --scope`: the daemon's SH_QEMU_RSS_GUARD_MB bounds
    # display-backlog growth at the source, the MemoryMax cap is the outer net.
    #
    # This script deliberately does NOT create that scope itself any more.
    # A scope started here, before `systemctl start`, cannot be BindsTo= a
    # service that is still inactive, so it would be exactly the unbound,
    # un-killable cgroup that let an IRIX watchdog survive a `systemctl stop`.
    # ensure-tile-{qemu,x11}.sh — the unit's own ExecStartPre — is idempotent
    # and creates the scope BOUND to the service, so letting it own the launch
    # is both less code and the only version that can be stopped.
    skip_qmp=1
    ;;
  *)
    run bash "$TILESDIR/$t/qemu-streamhost.sh" # nohup QEMU (kills old by pidfile)
    ;;
  esac
  [ "$skip_qmp" = 1 ] || wait_qmp "$t" || true
  run systemctl start "streamhost@${t}.service" # attaches to QMP, serves its UDP port
done

# ---------------------------------------------------------------------------
# 5. postmarketos caveat — portrait resolution settles late
# ---------------------------------------------------------------------------
echo "== step 5: postmarketos 720x1440 settle =="
# phosh brings the framebuffer up in stages and only lands on the final portrait
# 720x1440 mode after the greeter loads. If streamhost attached before that, its
# capture is locked to the wrong geometry. Give it time, then RESTART the daemon so
# capture re-reads the settled scanout geometry.
echo "   (waiting for phosh to reach 720x1440 before restarting the daemon)"
run sleep 45
run systemctl restart streamhost@postmarketos.service

# ---------------------------------------------------------------------------
# 6. Signaling registry + HTTPS SPA origin
# ---------------------------------------------------------------------------
echo "== step 6: tiles.json + local CA + HTTPS server =="
# tiles.json (osId -> {udpPort, hashFile}) is the committed reference in this repo.
# Ensure the live serve copy matches it.
run install -m 600 "$SERVE/tiles.json" "$REPO/serve/tiles.json"
# Local CA + leaf cert the browser trusts (idempotent; regenerates if missing/expiring).
run bash "$SERVE/gen-local-ca.sh"
# Start the HTTPS SPA + same-origin signaling server on :8443.
echo "+ launching osgallery-https-server.py on :8443"
if [ "$DRY_RUN" != 1 ]; then
  WEBROOT="$REPO/serve/webroot" \
    SIGNAL_CONFIG="$REPO/serve/tiles.json" \
    CERT="$REPO/serve/pki/leaf.crt" \
    KEY="$REPO/serve/pki/leaf.key" \
    SIGNAL_HOST="$SIGNAL_HOST" PORT=8443 BIND_IP=0.0.0.0 \
    nohup python3 "$SERVE/osgallery-https-server.py" \
    >"$REPO/serve/https-server.log" 2>&1 &
  echo "  https server pid=$!  (log: $REPO/serve/https-server.log)"
fi

cat <<NOTE

== done ==
Open the gallery:
    https://$SIGNAL_HOST:8443/
(streamhost is the committed live transport for the gallery tiles —
spa/src/three/archetypeRegistry.ts.)

REMINDERS
  * The SPA bundle under serve/webroot/ is built from spa/ in this repo and is
    NOT vendored here — deploy it into serve/webroot/ before step 6.
  * Guest images are large binaries NOT in the repo — scripts/build-guests/
    build-all.sh rebuilds every one of them from upstream (MASTER-REPRODUCE.md
    Phase 4). They land under /data/gallery-guests/ plus the two LiveCD ISOs at
    /data/isos/Alpine.iso and /data/isos/TinyCore.iso (canonical paths the
    emitted launchers reference) before the corresponding tiles will boot.
NOTE
