#!/bin/bash
# DO NOT EDIT — generated by scripts/tiles-registry.py generate from
# registry/tiles/*.json + registry/registry-v1.json; run `make tile-registry-generate`.
# tiles-manifest.sh — registry-generated recipe for all 55 production
# gallery tiles. Each `emit` line re-emits one tile's per-tile files (tile.env,
# ROLLBACK.md, and for local modes qemu-streamhost.sh) under the tile runtime
# directory by invoking scripts/streamhost-tile.sh.
#
# Run ON the host (root@192.0.2.10) after an NVMe rebuild, once
# scripts/streamhost-tile.sh + deploy/streamhost@.service are in place:
#     bash tiles-manifest.sh                 # emits all 55 production tiles' files
#     bash tiles-manifest.sh --install       # also drops the systemd unit (once)
#     bash tiles-manifest.sh --pin-machine   # versioned machine types (NVMe rebuild;
#                                            # see streamhost-tile.sh header)
#     bash tiles-manifest.sh --out-root /tmp/x   # scratch emit (verify-emit.sh)
#
# It does NOT start QEMU or the daemons — bring-up-all.sh does the full ordered
# boot. This file is purely the "what reproduces each tile" ledger.
#
# THREE QEMU MODES (see scripts/streamhost-tile.sh):
#   * GENERIC tiles pass the full media/machine/audio/input flag set and the
#     launcher is generated from the standard template.
#   * VERBATIM tiles pass --launcher-file tiles/<tile>/qemu-streamhost.sh — a
#     tracked, byte-exact launcher carrying that tile's bespoke logic (golden
#     state-qcow2 create-if-missing, conditional/unconditional -loadvm golden,
#     per-boot overlays, post-boot QMP hostfwd_add, serial chardevs, reset
#     monitors). For those tiles the launcher FILE is the device-set ledger;
#     the emit line only carries the tile.env-relevant flags.
#   * PVE tiles pass --pve-vmid. PVE owns QEMU; the emitter writes its SH_PVE_*
#     environment and deliberately generates no qemu-streamhost.sh. `qm config`
#     captured in the registry is the device-set ledger.
#   Golden-fixture tile.env stanzas are tracked per tile in
#   tiles/<tile>/tile.env.fixture and appended verbatim (--env-append-file).
#
# PARITY GATE: scripts/dev/verify-emit.sh (repo) emits all 55 production tiles into a
# scratch dir on the box and byte-diffs against the live tiles. Keep it green
# (PASS or whitelisted-with-justification) after ANY change here.
#
# osId vs tile-dir note: osId "aros" == tile dir "amigaos"; osId "solaris" == tile
# dir "solariscde"; all other osIds equal their tile dir name. streamhost-tile.sh
# keys everything on the TILE DIR name (--tile), and tiles.json maps osId->tile.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
SH="$HERE/scripts/streamhost-tile.sh"
T="$HERE/tiles"                        # tracked verbatim launchers + env fixtures
RUNTIME_T="/data/vms/streamhost/tiles" # runtime tile root (referenced in args)

FWD=()
OUT_ROOT="$RUNTIME_T"
while [ $# -gt 0 ]; do
  case "$1" in
    --install)
      FWD+=(--install)
      shift
      ;;
    --pin-machine)
      FWD+=(--pin-machine)
      shift
      ;;
    --out-root)
      OUT_ROOT="$2"
      FWD+=(--out-root "$2")
      shift 2
      ;;
    *)
      echo "unknown arg: $1" >&2
      exit 2
      ;;
  esac
done

# ---------------------------------------------------------------------------
# PREFLIGHT — every tile.env fixture referenced below must exist BEFORE we emit
# anything. A single missing --env-append-file used to kill the run mid-fleet
# (set -e inside emit), leaving every later tile unemitted and unchecked while
# the truncated output still read as progress. That is the silent-cap failure
# mode: validate the whole set up front, name EVERY missing file, emit nothing.
# Fixtures are repo-tracked build inputs (streamhost/tiles/<tile>/tile.env.fixture);
# if they are missing here, this copy of the kit is incomplete — run the sweep
# from a full checkout (scripts/dev/verify-emit.sh) or sync the named files in.
# ---------------------------------------------------------------------------
FIXTURES=()
MISSING_FIXTURES=()
# shellcheck disable=SC2016 # the grep/sed patterns match the LITERAL "$T/…" text of this file
while IFS= read -r fx; do
  [ -n "$fx" ] || continue
  FIXTURES+=("$fx")
  [ -f "$T/$fx" ] || MISSING_FIXTURES+=("$fx")
done < <(grep -oE -- '--env-append-file "\$T/[^"]+"' "$0" | sed 's|.*\$T/||; s|"$||' | sort -u)
if [ "${#MISSING_FIXTURES[@]}" -gt 0 ]; then
  echo "FATAL: ${#MISSING_FIXTURES[@]} of ${#FIXTURES[@]} tile.env fixtures are missing under $T —" >&2
  printf '  MISSING FIXTURE: %s\n' "${MISSING_FIXTURES[@]}" >&2
  echo "NOTHING WAS EMITTED. This manifest refuses to run a partial sweep." >&2
  exit 1
fi
echo "=== preflight: ${#FIXTURES[@]}/${#FIXTURES[@]} tile.env fixtures present under $T"

EMITTED=0
emit() {
  echo "=== emit: $1"
  shift
  bash "$SH" "$@" ${FWD[@]+"${FWD[@]}"}
  EMITTED=$((EMITTED + 1))
}

# ---------------------------------------------------------------------------
# GROUP A — modern Linux / hobby-OS LiveCDs & disks, USB-tablet abs pointer,
#           intel-hda or AC97 audio, KVM.
# ---------------------------------------------------------------------------

# alpine (VMID 81) — Alpine LiveCD + golden fixture. VERBATIM LAUNCHER
#   (tiles/alpine/qemu-streamhost.sh): state.qcow2 (2G ide, create-if-missing)
#   holds the savevm 'golden' snapshot; conditional -loadvm golden; post-boot
#   QMP hostfwd_add re-adds the ssh forward 127.0.0.1:5881 -> guest :22 (SLIRP
#   state is host-side, NOT in the snapshot; QMP add keeps the device set
#   loadvm-exact). Needs /root/qmp_hmp.py (source: scripts/qmp_hmp.py here).
#   ISO at /data/isos/Alpine.iso (canonical; the retired CT110 subvol path the
#   pre-2026-07-14 live launcher used is whitelisted in verify-emit).
emit alpine \
  --tile alpine --vmid 81 --udp 54081 --pointer abs --audio on --fps 60 \
  --launcher-file "$T/alpine/qemu-streamhost.sh" \
  --env-append-file "$T/alpine/tile.env.fixture"

# tinycore (VMID 82) — TinyCore LiveCD + golden fixture. VERBATIM LAUNCHER:
#   state.qcow2 (3G virtio) for the golden snapshot; conditional -loadvm golden;
#   post-boot QMP hostfwd_add 127.0.0.1:5882 -> guest :22 (user 'tc').
#   ISO at /data/isos/TinyCore.iso (canonical; old /data/vms/spikeA path
#   whitelisted). Resolution 1600x1200x32 (4:3, under the 1920x1200 cap; set in
#   the guest .xsession Xvesa -screen). Cursor calibration (2026-07): TinyCore's
#   Xvesa reads a RELATIVE PS/2 mouse (/dev/input/mice), so the daemon-abs path
#   is relative tracking with edge re-homing (clamp at screen edges). The single
#   cursor_scale sets the 1:1 GAIN (measured transfer A~1.28 per axis, equal at
#   4:3); the offset is a neutral origin. scale=0.783 off=(0,0) tracks 1:1 within
#   ~1-2px after any edge touch (live-client + framebuffer verified). Re-verify
#   after any TinyCore major bump or resolution change.
emit tinycore \
  --tile tinycore --vmid 82 --udp 54082 --pointer abs \
  --cursor-scale 0.783 --cursor-off-x 0 --cursor-off-y 0 --audio on --fps 60 \
  --launcher-file "$T/tinycore/qemu-streamhost.sh" \
  --env-append-file "$T/tinycore/tile.env.fixture"

# reactos (VMID 106) — NT-era LiveCD + golden fixture. UDP 4433. VERBATIM
#   LAUNCHER: boots the LiveCD (-boot d) with reactos-golden.qcow2 attached
#   solely to hold the savevm 'golden' snapshot (no -snapshot, no floppy —
#   matches the baked device set). Golden store canonical at
#   /data/gallery-guests/ReactOS/ (old /data/reactos-golden whitelisted).
emit reactos \
  --tile reactos --vmid 106 --udp 4433 --pointer abs --audio on --fps 30 \
  --launcher-file "$T/reactos/qemu-streamhost.sh" \
  --env-append-file "$T/reactos/tile.env.fixture"

# toaruos (VMID 98) — LiveCD, AC97 + usb-tablet. GENERIC. The remastered
#   image.iso IS the golden artifact (no snapshottable disk): resetMode=restart.
emit toaruos \
  --tile toaruos --vmid 98 --udp 54098 --pointer abs --audio on --audio-dev ac97 \
  --input-dev usb --mem 1024 --smp 2 --machine pc-i440fx-11.0 --cpu host --vga std --fps 30 \
  --cdrom /data/gallery-guests/toaruos/image.iso --boot d \
  --env-append-file "$T/toaruos/tile.env.fixture"

# haiku (VMID 107) — persistent disk boot. GENERIC. --vga none: --extra supplies
#   a VGA device forced to 1920x1200 via EDID (the built-in -vga would ignore the
#   EDID). intel-hda + usb-tablet.
# SSH GUEST SHELL: ssh -i /root/.ssh/gallery_guest_key -p 5807 user@127.0.0.1
#   (login user 'user', uid 0; guest 10.0.2.15:22). hostfwd=...5807-:22 is baked
#   onto the EXISTING -netdev user below (a netdev backend property, NOT a
#   -device => -loadvm golden still matches exactly). sshd autostart + keys live
#   on the persistent disk AND in savevm golden (see the fixture stanza). The
#   tile boots haiku-persist.qcow2 (-boot c, ide — via --disk-raw so it lands in
#   the media slot exactly as baked); loadvm needs exactly this device set.
emit haiku \
  --tile haiku --vmid 107 --udp 54107 --pointer abs --audio on --audio-dev hda \
  --input-dev usb --mem 2048 --smp 2 --machine pc-i440fx-11.0 --cpu host --vga none --fps 30 \
  --disk-raw "-drive file=/data/vms/streamhost/tiles/haiku/haiku-persist.qcow2,format=qcow2,if=ide" \
  --boot c \
  --extra "-device VGA,id=vga0,edid=on,xres=1920,yres=1200 -netdev user,id=n0,hostfwd=tcp:127.0.0.1:5807-:22 -device e1000,netdev=n0" \
  --env-append-file "$T/haiku/tile.env.fixture"

# ---------------------------------------------------------------------------
# GROUP B — legacy guests with explicit input handling. 9front uses bare i8042
#           PS/2; AROS binds Poseidon hid.class to a QEMU USB HID tablet.
# ---------------------------------------------------------------------------

# amigaos / osId "aros" (VMID 110) — AROS LiveCD, AC97, usb-tablet, abs pointer.
#   VERBATIM LAUNCHER: golden-scratch.qcow2 holds the diskless LiveCD savevm.
#   The device-set-matched golden preserves `AddUSBHardware pciusb.device 0` and
#   is auto-loaded so AROS owns the absolute tablet immediately after launch.
emit amigaos \
  --tile amigaos --vmid 110 --udp 54110 --pointer abs --audio on --fps 30 \
  --launcher-file "$T/amigaos/qemu-streamhost.sh"

# helenos (VMID 99) — ia32 LiveCD on -cpu qemu32, intel-hda. GENERIC.
# POINTER=abs (2026-07-13): HelenOS's upstream USB HID stack binds the QEMU
# usb-tablet over the default PIIX3 UHCI controller (`--input-dev usb` -> `-usb
# -device usb-tablet`) and consumes absolute coordinates 1:1 — verified on a
# clone then live via QMP-abs framebuffer tracking. The golden snapshot was
# re-baked with the tablet present. golden.qcow2 (--extra) holds the savevm
# 'golden' snapshot for the diskless LiveCD; loadvm needs this exact device set.
emit helenos \
  --tile helenos --vmid 99 --udp 54099 --pointer abs \
  --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on --audio-dev hda \
  --input-dev usb --mem 512 --smp 1 --machine pc-i440fx-11.0 --cpu qemu32 --vga std --fps 30 \
  --cdrom /data/gallery-guests/HelenOS/HelenOS-0.14.1-ia32.iso --boot d \
  --extra "-drive file=/data/vms/streamhost/tiles/helenos/golden.qcow2,if=ide,index=0,media=disk" \
  --env-append-file "$T/helenos/tile.env.fixture"

# kolibrios (VMID 97) — LiveCD, usb-tablet, AC97. VERBATIM LAUNCHER:
#   state.qcow2 (virtio) holds the golden snapshot; conditional -loadvm golden.
# POINTER=abs (Pattern A): KolibriOS's native USB HID stack consumes usb-tablet
# absolute coordinates 1:1; golden re-baked 2026-07-13 with the tablet present.
emit kolibrios \
  --tile kolibrios --vmid 97 --udp 54097 --pointer abs --audio on --fps 30 \
  --launcher-file "$T/kolibrios/qemu-streamhost.sh" \
  --env-append-file "$T/kolibrios/tile.env.fixture"

# ninefront / 9front (VMID 96) — q35 disk, PS/2, intel-hda. GENERIC. Disk is a
#   virtio-less ide-hd on bus ide.0; whole drive+net string + the baked
#   `-loadvm golden` (the golden lives INSIDE the 9front qcow2; the disk runs
#   WITHOUT -snapshot so savevm persists) goes in --extra.
# POINTER=warpd: 9front's kernel devmouse accepts true absolute injection via
# /dev/mousein "A x y buttons msec" lines. In-guest agent /amd64/bin/warpd
# (guest-agents/ninefront/warpd.c, compiled IN-GUEST with 6c/6l) listens on
# tcp!*!7777; autostarted at boot by /cfg/cirno/termrc. The daemon reaches it
# via the hostfwd baked onto the EXISTING -netdev user below (host
# 127.0.0.1:57793 -> guest :7777; a netdev backend property, NOT a -device =>
# loadvm golden matches). Agent BAKED into the golden qcow2 disk AND the settled
# rio/app RAM snapshot with boot replay (2026-07-15).
emit ninefront \
  --tile ninefront --vmid 96 --udp 54096 --pointer warpd --warpd-addr 127.0.0.1:57793 --audio on --audio-dev hda \
  --input-dev ps2 --mem 1024 --smp 2 --machine pc-q35-11.0 --cpu host --vga std --fps 60 \
  --boot c \
  --extra "-drive file=/data/gallery-guests/9front/9front-11554.amd64.qcow2,if=none,id=hd0,format=qcow2 -device ide-hd,drive=hd0,bus=ide.0 -netdev user,id=n0,hostfwd=tcp:127.0.0.1:57793-:7777 -device virtio-net-pci,netdev=n0 -loadvm golden"

# ---------------------------------------------------------------------------
# GROUP C — disk-image Linux/Unix guests, USB-tablet abs pointer.
# ---------------------------------------------------------------------------

# android (VMID 101) — Android-x86 qcow2 on q35, virtio-blk + virtio-net,
#   usb-tablet, intel-hda. VERBATIM LAUNCHER: golden fixture — runs WITHOUT
#   -snapshot, boots -loadvm golden unconditionally, and exposes a dedicated
#   HMP reset socket (reset-hmp.sock) for live loadvm resets.
emit android \
  --tile android --vmid 101 --udp 54101 --pointer abs --audio on --fps 30 \
  --launcher-file "$T/android/qemu-streamhost.sh" \
  --env-append-file "$T/android/tile.env.fixture"

# solariscde / osId "solaris" (VMID 100) — Solaris 10 CDE on the standalone
# gallery-hid QEMU. The launcher requires -loadvm golden (never cold-boots), uses
# the VMState golden's two-socket CPU identity, and wires gallery-hid-pci at 0x1e.
# SH_INPUT_BACKEND=gallery-hid names the native absolute-pointer path directly.
# SH_GHID_SOCKET selects its chardev; hostfwd 57790 and the guest warpd agent are
# retained for rollback/exec only.
emit solariscde \
  --tile solariscde --vmid 100 --udp 54100 --pointer abs --input-backend gallery-hid --audio on --fps 60 \
  --launcher-file "$T/solariscde/qemu-streamhost.sh" \
  --env-append-file "$T/solariscde/tile.env.fixture"

# ---------------------------------------------------------------------------
# GROUP D — Windows NT family (usb-tablet + AC97), abs pointer.
# ---------------------------------------------------------------------------

# win2000 (VMID 93) — std VGA (VBEMP-NT/framebuf, 1600x1200x32), AC97,
#   usb-tablet, rtl8139 NIC. GENERIC.
#   Golden fixture: the disk runs WITHOUT -snapshot so the savevm 'golden'
#   snapshot persists inside win2k-pro.qcow2 (resetMode=loadvm).
emit win2000 \
  --tile win2000 --vmid 93 --udp 54093 --pointer abs --audio on --audio-dev ac97 \
  --input-dev usb --mem 512 --smp 1 --machine pc-i440fx-11.0 --cpu host --vga std --fps 30 \
  --boot c \
  --extra "-drive file=/data/gallery-guests/Win2000/win2k-pro.qcow2,format=qcow2,if=ide -netdev user,id=n0 -device rtl8139,netdev=n0 -loadvm golden" \
  --env-append-file "$T/win2000/tile.env.fixture"

# winxp (VMID 94) — boots hdd + attaches the retro-software LiveCD;
#   -boot order=c,menu=off. AC97 + usb-tablet. VERBATIM LAUNCHER: boots the
#   tile-LOCAL winxp-golden.qcow2 (gallery WinXPpro/winxp.qcow2 stays pristine)
#   WITHOUT -snapshot; golden snapshot inside (resetMode=loadvm).
emit winxp \
  --tile winxp --vmid 94 --udp 54094 --pointer abs --audio on --fps 30 \
  --launcher-file "$T/winxp/qemu-streamhost.sh" \
  --env-append-file "$T/winxp/tile.env.fixture"

# ---------------------------------------------------------------------------
# GROUP E — Win9x / DOS / OS/2: PS/2-only (usb=off), Sound Blaster 16 (only
#           inbox codec that works), acpi=off/kernel-irqchip=off, legacy
#           -cpu pentium*. rel/warpd pointer. ALL VERBATIM (golden fixtures).
# ---------------------------------------------------------------------------

# win311 (VMID 90) — Windows 3.11, sb16, two golden qcow2 disks (tile-local,
#   NO -snapshot; savevm/loadvm 'golden' persists). VERBATIM LAUNCHER with the
#   COM1 serial chardev (serial.sock) for the in-guest agent.
# POINTER=warpd (hybrid): usb=off => PS/2 RELATIVE-only mouse, and the Win3.x
# DOS mouse driver applies acceleration so an abs->rel bridge desyncs. Fix
# (guest-agents/win311/agent.c): an in-guest Win16 agent OpenComm("COM1")s and
# SetCursorPos()es the cursor absolutely from the warpd M/P/R/B protocol over
# COM1. SH_WARPD_BUTTONS=qemu keeps MOTION on the agent but routes BUTTONS
# through the real QEMU PS/2 device for true window-manager semantics. The COM1
# device comes from machine 'pc'; -serial chardev:ser0 only redirects its
# BACKEND so the guest device set is UNCHANGED and loadvm golden still matches.
# LAG+DRAG FIX (baked 2026-07-08): AGENT.EXE coalesces moves per COM1 drain
# batch; the two-channel race is closed by SH_WARPD_BUTTON_DELAY_MS=80 with
# SH_WARPD_PACE_MS=8 write pacing (empirical floor 50; 80 = 0 races observed).
emit win311 \
  --tile win311 --vmid 90 --udp 54090 --pointer warpd \
  --warpd-addr unix:/data/vms/streamhost/tiles/win311/serial.sock \
  --warpd-buttons qemu --warpd-pace-ms 8 --warpd-button-delay-ms 80 \
  --audio on --fps 30 \
  --launcher-file "$T/win311/qemu-streamhost.sh" \
  --env-append-file "$T/win311/tile.env.fixture"

# win95 (VMID 91) — Win95 OSR2, sb16, pcnet NIC; machine carries accel=kvm.
#   VERBATIM LAUNCHER: boots the tile-LOCAL win95-golden.qcow2 (gallery
#   Win95/win95-osr2-kvm.qcow2 stays pristine) WITHOUT -snapshot; conditional
#   -loadvm golden.
# POINTER=warpd: usb=off => PS/2 RELATIVE-only mouse + Win9x pointer
# acceleration make an abs->rel bridge drift. Fix (guest-agents/win9x/
# warpnet.c): an in-guest Win32 agent SetCursorPos()s absolutely over Winsock
# TCP :7777, reached via the hostfwd 127.0.0.1:57791 on the launcher's -netdev.
# BUTTONS ride the real QEMU PS/2 device (--warpd-buttons qemu, 2026-07-14): a
# warpnet mouse_event click is a WINDOWS-level click that punches through a
# fullscreen DOS box's input ownership (killed GTA/Duke/Quake with "VESA
# function 5h failed"); PS/2 buttons land in whoever owns the mouse. Motion
# stays on the agent (absolute, drift-free).
emit win95 \
  --tile win95 --vmid 91 --udp 54091 --pointer warpd --warpd-addr 127.0.0.1:57791 \
  --warpd-buttons qemu --audio on --fps 30 \
  --launcher-file "$T/win95/qemu-streamhost.sh" \
  --aux-file "$T/win95/drive.py" \
  --aux-file "$T/win95/golden-bake.sh" \
  --env-append-file "$T/win95/tile.env.fixture"

# win98se (VMID 92) — Win98SE, sb16, two qcow2 disks (system + games), pcnet,
#   usb-tablet. VERBATIM LAUNCHER: golden snapshot lives INSIDE the base disks
#   (NO -snapshot); conditional -loadvm golden.
# POINTER=abs via usb-tablet — BAKED + LIVE 2026-07-12. WINNING accel = KVM +
# acpi=on + -cpu pentium3 (apic ON, default irqchip): acpi=on is REQUIRED for
# PCI enumeration (this golden is an ACPI-HAL install; acpi=off left it on the
# fail-safe PnP BIOS with no PCI/NIC/USB). hidusb.sys staged from the base cabs
# by scripts/build-guests/win98.sh. Full evidence: docs/guests/win9x.md.
emit win98se \
  --tile win98se --vmid 92 --udp 54092 --pointer abs --audio on --fps 30 \
  --launcher-file "$T/win98se/qemu-streamhost.sh" \
  --aux-file "$T/win98se/golden-bake.sh" \
  --aux-file "$T/win98se/qmp.py" \
  --aux-file "$T/win98se/shot.sh" \
  --aux-file "$T/win98se/sk.py" \
  --env-append-file "$T/win98se/tile.env.fixture"

# freedos (VMID 95) — sb16 + routed PC-speaker audio, pc-i440fx-11.0,acpi=off, cirrus, ne2k NIC, PS/2 relative.
#   VERBATIM LAUNCHER: golden fixture — NO -snapshot (writes persist in
#   freedos.qcow2) and boots straight into the baked snapshot via an
#   unconditional -loadvm golden (fixture = the retro-games CHOICE menu).
emit freedos \
  --tile freedos --vmid 95 --udp 54095 --pointer rel --audio on --fps 30 \
  --launcher-file "$T/freedos/qemu-streamhost.sh" \
  --env-append-file "$T/freedos/tile.env.fixture"

# msdoswin1 (VMID 113) — MS-DOS 6.22 + Windows 1.01, tiny 16MB, PS/2, ide disk.
#   VERBATIM LAUNCHER: golden fixture — no -snapshot; post-boot `loadvm golden`
#   + `cont` via the tile-local qmpc.py helper (installed via --aux-file).
#   2026-07-13/14 streamhost fixes (docs/guests/msdos-win1.md):
#   - SOUND: PC-speaker only — `-machine pc,pcspk-audiodev=snd0` (backend-only).
#   - KEYBOARD: SH_LEGACY_KBD=1 — input.rs remaps the cursor cluster to bare
#     keypad scancodes for this pre-1986 guest.
#   - MOUSE: genuine Win 1.01 re-SETUP with the Windows 2.03 MOUSE.DRV (PS/2)
#     + SETVER entries baked into the golden ("Option B — PROMOTED LIVE").
emit msdoswin1 \
  --tile msdoswin1 --vmid 113 --udp 54113 --pointer rel --legacy-kbd 1 \
  --audio on --fps 60 \
  --launcher-file "$T/msdoswin1/qemu-streamhost.sh" \
  --aux-file "$T/msdoswin1/qmpc.py"

# os2warp (VMID 108) — *** TCG ONLY *** (OS/2 Warp 4 will NOT boot under KVM).
#   pc,acpi=off,usb=off, -cpu pentium, std VGA, sb16, pcnet NIC, PS/2. VERBATIM
#   LAUNCHER: COM1 serial chardev (serial.sock) + conditional -loadvm golden
#   (no -snapshot — savevm/loadvm persist; the OS/2 register nag never returns).
# DISPLAY: Warp 4.52 (MCP2) + IBM GENGRADD at 1024x768x64k on -vga std.
#   -global VGA.vgamem_mb=2 is LOAD-BEARING: GENPMI's mode tables hold 64 VESA
#   modes and SeaVGABIOS reports 93 at the 16 MB default, overflowing them
#   (trap c0000005 at display init). 2 MB trims the list to 46. See
#   docs/guests/os2warp.md.
# POINTER: in-guest warpd agent (guest-agents/os2/warpd_os2.c -> C:\WARPD.EXE,
#   PM WinSetPointerPos, Y-flipped) over COM1. Critical enablers: DosDevIOCtl
#   SET_DCBINFO forcing MODE_NOWAIT_READ_TIMEOUT, a PM message queue, and
#   MouSetPtrPos mirroring each warp into OS/2's native mouse subsystem. Buttons
#   ride the real QEMU PS/2 device (--warpd-buttons qemu) for PM capture, frame
#   sizing, menus, and double-clicks; the 80ms guard orders serial motion first.
emit os2warp \
  --tile os2warp --vmid 108 --udp 54108 --pointer warpd \
  --warpd-addr unix:/data/vms/streamhost/tiles/os2warp/serial.sock \
  --warpd-buttons qemu --warpd-wheel agent --warpd-pace-ms 8 \
  --warpd-button-delay-ms 80 --audio on --fps 30 \
  --launcher-file "$T/os2warp/qemu-streamhost.sh"

# ---------------------------------------------------------------------------
# GROUP F — SPECIAL tiles (non-standard boot/firmware/overlay). Read the notes.
# ---------------------------------------------------------------------------

# qnx (VMID 112) — QNX 6.5 LiveCD, Cirrus VGA, AC97, TABLET-FREE (PS/2 relative).
#   VERBATIM LAUNCHER: golden.qcow2 (ide, the savevm store — the LiveCD still
#   boots via -boot d) + the legacy HMP monitor on tcp 7112 (bring-up guest
#   keystrokes). Re-baked 2026-07-15 (docs/guests/qnx.md "LIVE PROMOTION"): the
#   usb-tablet made qemu_input_is_absolute() true and dbus RelMotion refuse,
#   freezing the pointer; the tablet-free golden is 1024x768 Photon with
#   SH_POINTER=rel driving the built-in i8042 PS/2 mouse 1:1 (SPA pointer-lock
#   type=4 direct-rel). loadvm needs exactly this device set: NO usb, NO tablet.
emit qnx \
  --tile qnx --vmid 112 --udp 54112 --pointer rel --audio on --fps 30 \
  --launcher-file "$T/qnx/qemu-streamhost.sh"

# sailfishos (VMID 104) — audio OFF, usb-tablet + usb-kbd, ide disk, e1000 NIC.
#   GENERIC (+ -snapshot: ephemeral; no golden — labctl reset refuses it).
emit sailfishos \
  --tile sailfishos --vmid 104 --udp 54104 --pointer abs --audio off \
  --input-dev usb --mem 1536 --smp 2 --machine pc-i440fx-11.0 --cpu host --vga std --fps 30 \
  --boot c \
  --extra "-drive file=/data/gallery-guests/SailfishOS/sailfishos-gui.qcow2,format=qcow2,if=ide -device usb-kbd -netdev user,id=n0 -device e1000,netdev=n0 -snapshot"

# templeos (VMID 105) — LiveCD (TempleOS.ISO), audio OFF, PS/2, plain std VGA.
#   VERBATIM LAUNCHER: state.qcow2 (create-if-missing) holds the savevm
#   'golden' snapshot (TempleOS is ISO/RAM-only); conditional -loadvm golden;
#   COM1 serial chardev (serial.sock) for the in-guest agent.
# POINTER=warpd (2026-07-13): TempleOS has NO USB stack and its PS/2 mouse is
# relative. Fix (guest-agents/templeos/warpd.HC): an in-guest HolyC task WS()
# polls the 16550 UART directly (ring-0, no serial driver needed), parses the
# warpd M/P/R/B protocol, and writes motion straight to the global mouse state
# ms.pos.x/y + clicks to ms.lb/ms.rb (framebuffer-verified). The agent is
# Spawn()ed at the T:/Home> REPL and BAKED into the golden RAM snapshot.
emit templeos \
  --tile templeos --vmid 105 --udp 54105 --pointer warpd \
  --warpd-addr unix:/data/vms/streamhost/tiles/templeos/serial.sock \
  --audio off --fps 30 \
  --launcher-file "$T/templeos/qemu-streamhost.sh" \
  --env-append-file "$T/templeos/tile.env.fixture"

# serenityos (VMID 102) — -kernel direct boot off an NVMe-attached qcow2
#   overlay over the read-only golden raw ext2 root (_disk_image); the Ext2FS
#   root must mount RW or the kernel panics. VERBATIM LAUNCHER: recreates the
#   overlay FRESH on every boot (rm + qemu-img create -b) — resetMode=restart;
#   the launcher is self-contained, no external pre-seed step needed.
# NOTE: pointer=ABS even though there is no usb-tablet. SerenityOS reads
# absolute pointer position (verified live: dbus SetAbsPosition lands 1:1; a
# relative delta is ignored). Do NOT switch this to rel.
emit serenityos \
  --tile serenityos --vmid 102 --udp 54102 --pointer abs --audio on --fps 60 \
  --launcher-file "$T/serenityos/qemu-streamhost.sh" \
  --env-append-file "$T/serenityos/tile.env.fixture"

# postmarketos (VMID 103) — *** UEFI (OVMF pflash) + PORTRAIT 720x1440 ***
#   q35, intel-hda; xhci usb-tablet + usb-kbd; AHCI disk. VERBATIM LAUNCHER:
#   golden fixture — boots the qcow2 disk pmos-phosh.qcow2 (NO snapshot=on) +
#   a WRITABLE qcow2 UEFI varstore (OVMF_VARS.qcow2); conditional
#   -loadvm golden (logged-in phosh desktop, PIN auto-typed at bake time).
#   PRE-REQ (this manifest performs it, see the pre-seed step at the bottom):
#   seed the varstore once —
#       qemu-img convert -f raw -O qcow2 \
#         /usr/share/pve-edk2-firmware/OVMF_VARS_4M.fd \
#         /data/vms/streamhost/tiles/postmarketos/OVMF_VARS.qcow2
#   The guest (phosh) drives the 720x1440 portrait mode; the streamhost daemon
#   must be (re)started only AFTER that resolution settles (bring-up-all.sh
#   step 5 handles it).
emit postmarketos \
  --tile postmarketos --vmid 103 --udp 54103 --pointer abs --audio on --fps 60 \
  --launcher-file "$T/postmarketos/qemu-streamhost.sh" \
  --env-append-file "$T/postmarketos/tile.env.fixture"

# ---------------------------------------------------------------------------
# GROUP G — emulator-bridge retro home computers (c64, atarist, apple2, amiga).
#   Each tile is a captured Debian 12 "bridge" kiosk (shared read-only base
#   /data/vms/bridge/bridge-base.qcow2 + a thin per-tile overlay.qcow2) running
#   a period emulator full-screen; streamhost captures the Linux framebuffer +
#   AC97 audio exactly like every other tile. See streamhost/docs/BRIDGE.md and
#   docs/guests/c64.md. Atari ST/Apple II/Amiga use usb-tablet ABS; C64 keeps
#   browser coordinates absolute but streamhost translates them to PS/2 REL for
#   VICE's SDL/1351 path (vmport=off, no tablet). All four use AC97, KVM,
#   -m 1536 -smp 2 -cpu host -vga std. VERBATIM LAUNCHERS: overlay.qcow2 (ide,
#   holds the INTERNAL golden snapshot — NEVER delete), e1000 NIC with an ssh
#   hostfwd (c64:5814 atarist:5816 apple2:5817 amiga:5818 -> guest :22), and a
#   CONDITIONAL -loadvm golden. tile.env carries the golden-fixture stanza
#   (SH_RESET_MODE=loadvm etc.) via the tracked fixture files.
# ---------------------------------------------------------------------------

# c64 (VMID 214) — VICE x64sc -> Commodore 64 -> GEOS 2.0 deskTop. ssh 5814.
emit c64 \
  --tile c64 --vmid 214 --udp 54114 --pointer rel \
  --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on --fps 60 \
  --launcher-file "$T/c64/qemu-streamhost.sh" \
  --env-append-file "$T/c64/tile.env.fixture"

# atarist (VMID 216) — hatari -> Atari ST -> EmuTOS GEM desktop. ssh 5816.
emit atarist \
  --tile atarist --vmid 216 --udp 54116 --pointer abs \
  --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on --fps 60 \
  --launcher-file "$T/atarist/qemu-streamhost.sh" \
  --env-append-file "$T/atarist/tile.env.fixture"

# apple2 (VMID 217) — LinApple 2.3.0 -> Apple //e -> Apple GEOS deskTop. ssh 5817.
emit apple2 \
  --tile apple2 --vmid 217 --udp 54117 --pointer abs \
  --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on --fps 60 \
  --launcher-file "$T/apple2/qemu-streamhost.sh" \
  --env-append-file "$T/apple2/tile.env.fixture"

# amiga (VMID 218) — FS-UAE -> Amiga 500 -> Kickstart 1.3 + Workbench 1.3.
#   ssh 5818. Fixture stanza also pins SH_IDLE_PAUSE_SECS=0 (never QMP-freeze
#   the kiosk out from under the watcher).
emit amiga \
  --tile amiga --vmid 218 --udp 54118 --pointer abs \
  --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on --fps 60 \
  --launcher-file "$T/amiga/qemu-streamhost.sh" \
  --env-append-file "$T/amiga/tile.env.fixture"

# redstar2 (VMID 120) — Red Star OS 2.0 i386 KDE desktop. AIR-GAPPED
#   VERBATIM launcher: -nodefaults, no NIC/netdev/hostfwd, IDE golden disk,
#   std VGA (Xorg vesa + ShadowFB, 1920x1200), absolute USB tablet, no audio.
#   Required -loadvm golden; dedicated HMP reset socket.
emit redstar2 \
  --tile redstar2 --vmid 120 --udp 54120 --pointer abs --audio off --fps 30 \
  --input-dev usb \
  --launcher-file "$T/redstar2/qemu-streamhost.sh" \
  --env-append-file "$T/redstar2/tile.env.fixture"

# redstar3 (VMID 121) — private Red Star OS 3.0 Desktop preservation tile.
#   KVM/i440fx, stable Nehalem CPU, std VGA (Xorg vesa + ShadowFB, 1920x1080),
#   IDE, USB tablet, no audio.
#   -nodefaults is mandatory: it prevents QEMU's implicit e1000; zero guest NICs.
emit redstar3 \
  --tile redstar3 --vmid 121 --udp 54121 --pointer abs --audio off --fps 30 \
  --input-dev usb --mem 1024 --smp 1 --machine pc-i440fx-11.0 --cpu Nehalem,kvm=off --vga std \
  --disk-raw "-drive file=/data/gallery-guests/RedStar3/redstar3.qcow2,format=qcow2,if=ide,index=0,media=disk -drive if=ide,index=2,media=cdrom" \
  --boot c --extra "-nodefaults -loadvm golden" \
  --env-append-file "$T/redstar3/tile.env.fixture"

# amstradcpc (VMID 219) — cap32 (Caprice32) -> Amstrad CPC 6128 -> Locomotive BASIC Ready. ssh 5819.
emit amstradcpc \
  --tile amstradcpc --vmid 219 --udp 54119 --pointer rel \
  --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on --fps 60 \
  --launcher-file "$T/amstradcpc/qemu-streamhost.sh" \
  --env-append-file "$T/amstradcpc/tile.env.fixture"

# nt351 (VMID 83) — Windows NT Workstation 3.51 on the ISA-only machine.
#   TCG/486/64 MiB, 480 MiB FAT16 IDE disk, ISA Cirrus, SB16, NE2000 at
#   0x300/IRQ9. VERBATIM launcher with conditional -loadvm golden. The disk is
#   deliberately below the legacy 504 MiB CHS boundary: a 1 GiB install reaches
#   the desktop during Setup but cannot cold-boot through isapc's 16-head BIOS.
# DISPLAY: accelerated Cirrus 1024x768x65536 colors (16bpp). The launcher pins
#   /opt/qemu-cirrusfix with patch 0004-cirrus-blt-rop1-fill.patch; the stock
#   QEMU drops source-independent row fills and corrupts scroll/window redraws.
#   Rebuild the pinned binary whenever the packaged QEMU version changes.
#   Program Manager and Main are maximized; dirty -> loadvm restores cleanly.
# POINTER: NT reads only the relative PS/2 mouse. Streamhost receives absolute
#   browser coordinates, homes the relative guest at an edge, then applies the
#   measured cursor_scale for 1:1 tracking. Recalibrate after a resolution or
#   mouse-control-panel change.
emit nt351 \
  --tile nt351 --vmid 83 --udp 54083 --pointer abs --input-backend dbus-rel \
  --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on --fps 30 \
  --launcher-file "$T/nt351/qemu-streamhost.sh" \
  --env-append-file "$T/nt351/tile.env.fixture"

# nt4 (VMID 89) — Windows NT 4.0 Workstation SP6a, accelerated ISA Cirrus
#   1024x768x65536 colors (16bpp), pcnet device, audio off. VERBATIM launcher:
#   boots the tile-local nt4-golden.qcow2 without -snapshot; conditional
#   -loadvm golden. Pins /opt/qemu-cirrusfix2 with patches 0004 (ROP1 fill) and
#   0005 (ISA Cirrus vmstate substructure restore); rebuild and reverify on a
#   packaged-QEMU version change. pc vmport=on auto-instantiates vmmouse, which
#   the preserved NT4 driver consumes as true absolute 1:1 input.
emit nt4 \
  --tile nt4 --vmid 89 --udp 54089 --pointer abs --audio off --fps 30 \
  --launcher-file "$T/nt4/qemu-streamhost.sh" \
  --env-append-file "$T/nt4/tile.env.fixture"

# openvms (slot 84) — TWO-VM DECwindows bridge. A captured 1024x768 Debian
#   bridge runs lean Xorg only (no Linux WM/DM) with usb-tablet. OpenVMS is an
#   independent SLIRP X client restored from leanx-preconnect, then replays the
#   DECterm/FileView/Clock/Calculator fixture. Reset is a cold service restart;
#   warm loadvm is forbidden because it restores dead X sockets.
emit openvms \
  --tile openvms --vmid 84 --udp 54084 --pointer abs \
  --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio off --fps 30 \
  --launcher-file "$T/openvms/qemu-streamhost.sh" \
  --aux-file "$T/openvms/bridge-launch.sh" \
  --aux-file "$T/openvms/bridge-xserverrc" \
  --aux-file "$T/openvms/DECW_FIXTURE.COM" \
  --env-append-file "$T/openvms/tile.env.fixture"

# irix — x11 RUNTIME tile (issue #20), NOT QEMU. MAME(indy_4610) booting
#   SGI IRIX 6.5 with NO window and NO X server (-video none), captured from
#   the framebuffer it publishes: SH_CAPTURE=shm + mamesock input (mamectl
#   OSD module ctl.sock, issue #45; irixagent.lua stays deployed as the
#   IRIX_CTL=off deep-rollback arm).
#   No SH_QMP; large media staged by tiles/irix/fetch-assets.sh.
emit irix \
  --tile irix --udp 54122 --x11 --x11-display :40 --capture shm \
  --pointer abs --input-backend mamesock --audio off --fps 30 \
  --x11-runtime-file "$T/irix/x11-runtime.sh" \
  --aux-file "$T/irix/irixagent.lua" \
  --aux-file "$T/irix/fbstat.py" \
  --aux-file "$T/irix/tapnet.sh" \
  --env-append-file "$T/irix/tile.env.fixture"

# mpf2 (VMID 220) — MAME mpf2 (Multitech Microprofessor II, 1982) -> Applesoft BASIC. ssh 5820. Keyboard-only.
emit mpf2 \
  --tile mpf2 --vmid 220 --udp 54124 --pointer none --input-backend disabled \
  --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on --fps 60 \
  --launcher-file "$T/mpf2/qemu-streamhost.sh" \
  --env-append-file "$T/mpf2/tile.env.fixture"

# ---------------------------------------------------------------------------
# GROUP H — UEFI Windows. Secure Boot + virtio-scsi + HD Audio; nothing here is
#           shared with the legacy Windows tiles above.
# ---------------------------------------------------------------------------

# win11 (VMID 123) — Windows 11 Pro 25H2, the only q35/OVMF Windows tile. The
#   launcher is the device-set ledger and its header explains three things that
#   look wrong but are not: the system disk is declared BEFORE the pflash pair
#   (savevm picks its vmstate device by -drive order, so this keeps the RAM
#   image out of the 528 KiB variable store), the variable store is qcow2 and
#   WRITABLE (read-only hangs OVMF before display init), and there is no vTPM
#   (Win11 needs one to install, not to run; BitLocker verified off first).
#   restrict=on isolates the guest: adapter up, no default route, no DNS.
#   VERBATIM LAUNCHER: boots the tile-LOCAL win11-golden.qcow2 (the pristine
#   install stays at /data/gallery-guests/Win11/win11.qcow2) with a golden
#   snapshot inside (resetMode=loadvm).
emit win11 \
  --tile win11 --vmid 123 --udp 54123 --pointer abs --audio on --fps 30 \
  --launcher-file "$T/win11/qemu-streamhost.sh" \
  --env-append-file "$T/win11/tile.env.fixture"

# vic20 (VMID 221) — VICE xvic (Commodore VIC-20, PAL, 1980) -> CBM BASIC V2. ssh 5821. Keyboard-only.
emit vic20 \
  --tile vic20 --vmid 221 --udp 54085 --pointer none --input-backend disabled \
  --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on --fps 60 \
  --launcher-file "$T/vic20/qemu-streamhost.sh" \
  --env-append-file "$T/vic20/tile.env.fixture"

# plus4 (VMID 221) — VICE xvic (Commodore VIC-20, PAL, 1980) -> CBM BASIC V2. ssh 5821. Keyboard-only.
emit plus4 \
  --tile plus4 --vmid 222 --udp 54086 --pointer none --input-backend disabled \
  --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on --fps 60 \
  --launcher-file "$T/plus4/qemu-streamhost.sh" \
  --env-append-file "$T/plus4/tile.env.fixture"
emit c128 \
  --tile c128 --vmid 223 --udp 54087 --pointer none --input-backend \
  disabled --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on \
  --fps 60 --launcher-file "$T/c128/qemu-streamhost.sh" --env-append-file \
  "$T/c128/tile.env.fixture"
emit pet2001 \
  --tile pet2001 --vmid 224 --udp 54088 --pointer none --input-backend \
  disabled --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on \
  --fps 60 --launcher-file "$T/pet2001/qemu-streamhost.sh" \
  --env-append-file "$T/pet2001/tile.env.fixture"
emit cbm8032 \
  --tile cbm8032 --vmid 225 --udp 54109 --pointer none --input-backend \
  disabled --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on \
  --fps 60 --launcher-file "$T/cbm8032/qemu-streamhost.sh" \
  --env-append-file "$T/cbm8032/tile.env.fixture"
emit cbm2 \
  --tile cbm2 --vmid 226 --udp 54111 --pointer none --input-backend \
  disabled --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on \
  --fps 60 --launcher-file "$T/cbm2/qemu-streamhost.sh" --env-append-file \
  "$T/cbm2/tile.env.fixture"
emit pdp11 \
  --tile pdp11 --vmid 227 --udp 54115 --pointer none --input-backend \
  disabled --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on \
  --fps 60 --launcher-file "$T/pdp11/qemu-streamhost.sh" --env-append-file \
  "$T/pdp11/tile.env.fixture"
emit gt40 \
  --tile gt40 --vmid 228 --udp 54125 --pointer abs --cursor-scale 1.0 \
  --cursor-off-x 0 --cursor-off-y 0 --audio on --fps 60 --launcher-file \
  "$T/gt40/qemu-streamhost.sh" --env-append-file \
  "$T/gt40/tile.env.fixture"
emit decos \
  --tile decos --vmid 229 --udp 54126 --pointer none --input-backend \
  disabled --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on \
  --fps 60 --launcher-file "$T/decos/qemu-streamhost.sh" --env-append-file \
  "$T/decos/tile.env.fixture"
emit zxspectrum \
  --tile zxspectrum --vmid 230 --udp 54127 --pointer none --input-backend \
  disabled --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on \
  --fps 60 --launcher-file "$T/zxspectrum/qemu-streamhost.sh" \
  --env-append-file "$T/zxspectrum/tile.env.fixture"
emit zx81 \
  --tile zx81 --vmid 231 --udp 54128 --pointer none --input-backend \
  disabled --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on \
  --fps 60 --launcher-file "$T/zx81/qemu-streamhost.sh" --env-append-file \
  "$T/zx81/tile.env.fixture"

# bbcmicro (VMID 232) — MAME 0.289 bbcb (Acorn BBC Micro Model B, 1981) -> BBC BASIC II. ssh 5832. Keyboard-only.
emit bbcmicro \
  --tile bbcmicro --vmid 232 --udp 54129 --pointer none --input-backend \
  disabled --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on \
  --fps 60 --launcher-file "$T/bbcmicro/qemu-streamhost.sh" \
  --env-append-file "$T/bbcmicro/tile.env.fixture"

# dragon32 (VMID 233) — MAME dragon32 -ext "" (Dragon 32, PAL, 1982) -> Microsoft Extended Color BASIC. ssh 5833. Keyboard-only.
emit dragon32 \
  --tile dragon32 --vmid 233 --udp 54130 --pointer none --input-backend \
  disabled --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on \
  --fps 60 --launcher-file "$T/dragon32/qemu-streamhost.sh" \
  --env-append-file "$T/dragon32/tile.env.fixture"
emit oricatmos \
  --tile oricatmos --vmid 234 --udp 54131 --pointer none --input-backend \
  disabled --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on \
  --fps 60 --launcher-file "$T/oricatmos/qemu-streamhost.sh" \
  --env-append-file "$T/oricatmos/tile.env.fixture"
emit kc854 \
  --tile kc854 --vmid 235 --udp 54132 --pointer none --input-backend \
  disabled --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on \
  --fps 60 --launcher-file "$T/kc854/qemu-streamhost.sh" --env-append-file \
  "$T/kc854/tile.env.fixture"
emit sinclairql \
  --tile sinclairql --vmid 236 --udp 54133 --pointer none --input-backend \
  disabled --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on \
  --fps 60 --launcher-file "$T/sinclairql/qemu-streamhost.sh" \
  --env-append-file "$T/sinclairql/tile.env.fixture"
emit nextstep \
  --tile nextstep --vmid 237 --udp 54134 --pointer rel --cursor-scale 1.0 \
  --cursor-off-x 0 --cursor-off-y 0 --audio on --fps 60 --launcher-file \
  "$T/nextstep/qemu-streamhost.sh" --env-append-file \
  "$T/nextstep/tile.env.fixture"
emit armeval \
  --tile armeval --vmid 238 --udp 54135 --pointer none --input-backend \
  disabled --cursor-scale 1.0 --cursor-off-x 0 --cursor-off-y 0 --audio on \
  --fps 60 --launcher-file "$T/armeval/qemu-streamhost.sh" \
  --env-append-file "$T/armeval/tile.env.fixture"

# ---------------------------------------------------------------------------
# Pre-seed steps the manifest performs (documented per tile above)
# ---------------------------------------------------------------------------
# postmarketos: writable qcow2 UEFI varstore (the verbatim launcher expects it;
# seed ONCE — never clobber an existing one, phosh's boot entry lives in it).
PMOS_VARS="$OUT_ROOT/postmarketos/OVMF_VARS.qcow2"
PMOS_SRC=/usr/share/pve-edk2-firmware/OVMF_VARS_4M.fd
if [ ! -f "$PMOS_VARS" ]; then
  if command -v qemu-img >/dev/null 2>&1 && [ -f "$PMOS_SRC" ]; then
    qemu-img convert -f raw -O qcow2 "$PMOS_SRC" "$PMOS_VARS"
    echo "=== pre-seed: postmarketos OVMF_VARS.qcow2 created from $PMOS_SRC"
  else
    echo "WARN: cannot pre-seed $PMOS_VARS (qemu-img or $PMOS_SRC missing) — do it before first boot" >&2
  fi
fi

# Truncation guard: a sweep that covered fewer tiles than the roster must never
# exit 0 — a short run is a failed run, not an "all clear".
if [ "$EMITTED" -ne 55 ]; then
  echo "FATAL: emitted $EMITTED tiles but the production roster is 55 — the sweep was truncated." >&2
  exit 1
fi
echo "=== all 55 production tiles emitted ==="
