NEW
10 REM IS IT A PRIME NUMBER?
20 CLS:INPUT "TYPE A WHOLE NUMBER";N
30 IF N<2 THEN PRINT "TRY 2 OR MORE.":END
40 D=2
50 IF D*D>N THEN PRINT N;"IS A PRIME!":END
60 IF N/D=INT(N/D) THEN PRINT N;"=";D;"*";N/D:END
70 D=D+1:GOTO 50
