NEW
10 REM YOUR NAME BACKWARDS
20 CLS:INPUT "WHAT IS YOUR NAME";N$
30 R$=""
40 FOR I=LEN(N$) TO 1 STEP -1
50 R$=R$+MID$(N$,I,1)
60 NEXT I
70 PRINT "HELLO, ";N$;"!"
80 PRINT "YOUR NAME HAS";LEN(N$);"LETTERS."
90 PRINT "BACKWARDS IT IS ";R$
