#!/usr/bin/env bash
# DO NOT EDIT — generated by scripts/tiles-registry.py generate from
# registry/tiles/*.json + registry/registry-v1.json; run `make tile-registry-generate`.
# =============================================================================
# build-guests/build-all.sh  —  orchestrator for the Kernel Hive from-source builds
#
# GOAL: rebuild the ENTIRE Kernel Hive guest set from source on a fresh Proxmox
# host, by running each per-guest build script in a sensible order. This is the
# PRIMARY, reproducible path (MASTER-REPRODUCE.md Phase 4): every selected guest
# is rebuilt END TO END from upstream or explicitly supplied source media — no
# image backups. The old zfs-send image-restore path is now the optional shortcut.
#
# Each per-guest script (freedos.sh, 9front.sh, ...) is fully self-contained:
# it re-downloads its source ISO/image, creates the disk, drives the install
# automation, injects era software, lands the bootable artifact under
# /data/gallery-guests/<DIR>/, and framebuffer-verifies it reaches the GUI.
# This wrapper only sequences them, filters, times, and reports.
#
# USAGE:
#   ./build-all.sh                     # build everything that needs no staged media
#   ./build-all.sh --list              # print the manifest table and exit
#   ./build-all.sh --only 9front       # build just one guest (any class)
#   ./build-all.sh --only kolibrios --only toaruos   # build a subset
#   ./build-all.sh --class fast        # build only the fast live-ISO guests
#   ./build-all.sh --with-media        # include Sailfish (needs SDK emulator media)
#   ./build-all.sh --include-licensed  # also build guests needing a supplied ISO
#   ./build-all.sh --check-assets      # preflight staged media/env first (check-assets.sh)
#   ./build-all.sh --fail-fast         # stop at the first failing guest
#   ./build-all.sh --skip-verify       # pass VERIFY=0/DO_VERIFY=0 to each guest
#   ./build-all.sh --dry-run           # show what WOULD run, run nothing
#
# Env overrides are passed straight through to the per-guest scripts, e.g.:
#   FORCE=1 ./build-all.sh --only win95            # force a rebuild
#   SOL10_ISO=/isos/sol10.iso ./build-all.sh --only solaris-cde
#   XP_ISO_LOCAL=/isos/xp.iso ./build-all.sh --only winxp
#
# HYGIENE: this wrapper never kills anything and never touches other guests,
# CT 110 or the deleted Win11/macOS VMIDs. Each per-guest script owns its own
# cleanup (pidfile/monitor-quit only, namespaced sockets/dirs).
# =============================================================================
set -u
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GALLERY_ROOT="${GALLERY_ROOT:-/data/gallery-guests}"

# ---------------------------------------------------------------------------
# Guest manifest.  Columns (pipe-separated):
#   KEY | SCRIPT | OUTPUT_DIR | CLASS | EST_TIME | AUTOMATION | PRODUCES [| FLAGS]
#
# CLASS:
#   fast      cheap live-ISO / prebuilt-disk exotics — no OS install, seconds-to-GUI
#   retro     prebuilt Win/DOS base image + era-software injection (mid-weight download)
#   heavy     from-source compile or full unattended OS install (slow)
#   licensed  needs a user-supplied source (copyright / SSO-gated) — SKIPPED by default
#
# AUTOMATION:
#   full      build reaches the GUI hands-off, zero human input
#   full*     build hands-off; a ONE-TIME footnote applies at RUNTIME (documented)
#   1-click   build needs (worst case) a single one-time interactive click/calibration
#   supplied  fully scripted once you supply the required source media
#
# FLAGS:
#   media     needs staged, account-gated source media; skipped unless selected
#             by --with-media or an explicit --only
#
# ---------------------------------------------------------------------------
MANIFEST=(
  "kolibrios   |kolibrios.sh   |KolibriOS   |fast     |~2-3m   |full   |kolibri.iso (live CD)"
  "toaruos     |toaruos.sh     |toaruos     |fast     |~3m     |full   |image.iso (live CD)"
  "helenos     |helenos.sh     |HelenOS     |fast     |~3m     |full   |HelenOS-0.14.1-ia32.iso (live)"
  "9front      |9front.sh      |9front      |fast     |~5-8m   |full   |9front-11554.amd64.qcow2"
  "reactos     |reactos.sh     |ReactOS     |fast     |~3-5m   |full   |ReactOS.iso (live CD)"
  "haiku       |haiku-install.sh|Haiku       |fast     |~6-10m  |full   |haiku.iso -> tile haiku-persist.qcow2 + sshd/key + golden"
  "templeos    |templeos.sh    |TempleOS    |fast     |~2-3m   |full   |TempleOS.ISO (live CD)"
  "amigaos     |amigaos.sh     |AmigaOS     |fast     |~3-5m   |full   |aros-pc-i386.iso (AROS live CD)"
  "qnx         |qnx.sh         |QNX         |fast     |~5-10m  |full   |QNX650Live.iso (drives Photon first-run to desktop)"
  "alpine      |alpine.sh      |Alpine      |fast     |~2-3m   |full   |Alpine.iso -> /data/isos/ (ssh-golden LiveCD)"
  "tinycore    |tinycore.sh    |TinyCore    |fast     |~2-3m   |full   |TinyCore.iso -> /data/isos/ (ssh-golden LiveCD)"
  "freedos     |freedos.sh     |FreeDOS     |retro    |~10-15m |full*  |freedos.qcow2 (games+Arachne)"
  "msdos-win1  |msdos-win1.sh  |MSDOSWin1   |retro    |~10-15m |full   |msdos-win1.qcow2 (DOS 6.22 + Windows 1.01, from real floppies)"
  "win311      |win311.sh      |Win311      |retro    |~10m    |full   |hda.img + games.img"
  "win95       |win95.sh       |Win95       |retro    |~15-25m |1-click|win95-osr2.qcow2"
  "win98       |win98.sh       |Win98SE     |retro    |~15-25m |1-click|win98se.qcow2 + games qcow2"
  "win2000     |win2000.sh     |Win2000     |retro    |~15-30m |full*  |win2k-pro.qcow2"
  "os2warp     |os2warp.sh     |OS2Warp     |retro    |~20-30m |full   |os2.qcow2 (Warp 4 prebuilt + first-boot taming; TCG)"
  "android-x86 |android-x86.sh |Android     |heavy    |~20-40m |1-click|android.qcow2"
  "postmarketos|postmarketos-fixture.sh|postmarketOS|heavy|~12-25m |full   |pmos-phosh.qcow2 + OVMF vars + golden"
  "sailfishos  |sailfishos.sh  |SailfishOS  |heavy    |~15-30m |supplied|sailfishos.qcow2 (STAGE 1; needs Sailfish SDK emulator VDI/archive)|media"
  "sailfishos-gui|sailfishos-gui.sh|SailfishOS|heavy  |~20-40m |full   |sailfishos-gui.qcow2 (STAGE 2 bochs-drm KMS; run after sailfishos)|media"
  "serenityos  |serenityos.sh  |SerenityOS  |heavy    |~20-60m |full   |_disk_image + Kernel (compiled)"
  "winxp       |winxp.sh       |WinXPpro    |licensed |~30-50m |supplied|winxp.qcow2 (needs XP ISO)"
  "solaris-cde |solaris-cde.sh |SolarisCDE  |licensed |~40-60m |supplied|solaris.qcow2 (needs OTN ISO)"
  "win11       |win11.sh       |Win11       |licensed |~20-25m |full    |win11.qcow2 (needs Win11 ISO)"
  # emulator-bridge retro home computers. bridge-base is a PREREQUISITE (shared
  # read-only base image) — build it BEFORE c64/atarist/apple2/amiga (each is a
  # thin overlay + golden bake over it). Artifacts land outside GALLERY_ROOT under
  # /data/vms/bridge/ + /data/vms/streamhost/tiles/<tile>/. See streamhost/docs/BRIDGE.md.
  "bridge-base  |bridge-base.sh |bridge         |retro    |~20-30m |full   |/data/vms/bridge/bridge-base.qcow2 (VICE+hatari+cap32 bare-X kiosk base)"
  "c64          |c64.sh         |bridge/c64     |retro    |~3-5m   |full   |tiles/c64 overlay + golden (VICE x64sc → GEOS 2.0)"
  "atarist      |atarist.sh     |bridge/atarist |retro    |~3-5m   |full   |tiles/atarist overlay + golden (hatari → EmuTOS GEM)"
  "apple2       |apple2.sh      |bridge/apple2  |retro    |~3-5m   |full   |tiles/apple2 overlay + golden (Apple //e → GEOS)"
  "amiga        |amiga.sh       |bridge/amiga   |retro    |~3-5m   |full   |tiles/amiga overlay + golden (Kickstart 1.3 + Workbench 1.3)"
  "redstar2     |redstar2.sh     |RedStar2    |heavy    |~45-90m |vision |redstar2.qcow2 (air-gapped install + golden)"
  "redstar3    |redstar3.sh    |RedStar3    |retro    |~15-30m |vision |redstar3.qcow2|media"
  "amstradcpc   |amstradcpc.sh  |bridge/amstradcpc|retro    |~3-5m   |full   |tiles/amstradcpc overlay + golden (cap32 → Locomotive BASIC)"
  "nt351       |nt351.sh       |Nt351         |installed|~15-30m |partial |nt351.qcow2 (480 MiB FAT16; needs bootable SP5 ISO)"
  "nt4         |nt4.sh         |Nt4           |fast     |~2-5m   |full    |nt4-golden.qcow2 (prebuilt VMware VM -> qcow2 + boot.ini scsi->multi fix)"
  "openvms     |openvms.sh     |OpenVMS       |licensed |~3-8m   |full    |OpenVMS disks; openvms-decwindows-bridge.sh builds lean-X bridge"
  "mpf2         |mpf2.sh        |bridge/mpf2     |retro    |~3-5m   |full   |tiles/mpf2 cold-boot overlay (MAME mpf2 → Applesoft BASIC)"
  "vic20        |vic20.sh       |bridge/vic20    |retro    |~2-4m   |full   |tiles/vic20 overlay + golden (VICE xvic → CBM BASIC V2)"
  "plus4        |plus4.sh       |bridge/plus4    |retro    |~2-4m   |full   |tiles/plus4 overlay + golden (VICE xplus4 → 3-plus-1 suite)"
  "c128         |c128.sh        |bridge/c128     |retro    |~3-5m   |full   |tiles/c128 overlay + golden (VICE x128 → 80-col BASIC V7.0, CP/M in drive 8)"
  "pet2001     |pet2001.sh     |bridge/pet2001  |retro    |~2-4m   |full   |tiles/pet2001 overlay + golden (VICE xpet -model 2001 → COMMODORE BASIC)"
  "cbm8032      |cbm8032.sh     |bridge/cbm8032  |retro    |~2-4m   |full   |tiles/cbm8032 overlay + golden (VICE xpet -model 8032 → BASIC 4.0)"
  "cbm2         |cbm2.sh        |bridge/cbm2     |retro    |~2-4m   |full   |tiles/cbm2 overlay + golden (VICE xcbm2 -model 610 → BASIC 128)"
  "pdp11        |pdp11.sh       |bridge/pdp11    |retro    |~6-8m   |full   |tiles/pdp11 overlay + golden (Open SIMH PDP-11/70 → 2.11BSD login)"
  "gt40         |gt40.sh        |bridge/gt40     |retro    |~5-8m   |full   |tiles/gt40 overlay + golden (Open SIMH pdp11 VT11 → Lunar Lander)"
  "decos        |decos.sh       |bridge/decos    |retro    |~20-70m |full   |tiles/decos overlay + golden (Open SIMH → RT-11 / RSX-11M / RSTS-E chooser)"
  "zxspectrum  |zxspectrum.sh  |Zxspectrum    |installed|~15-30m |partial |TODO"
  "nextstep        |nextstep.sh        |Zx81          |installed|~15-30m |partial |TODO"
  "zx81        |zx81.sh        |Zx81          |installed|~15-30m |partial |TODO"
  "bbcmicro    |bbcmicro.sh    |Bbcmicro      |installed|~15-30m |partial |TODO"
  "dragon32    |dragon32.sh    |Dragon32      |installed|~15-30m |partial |TODO"
  "oricatmos   |oricatmos.sh   |Oricatmos     |installed|~15-30m |partial |TODO"
  "kc854       |kc854.sh       |Kc854         |installed|~15-30m |partial |TODO"
  "sinclairql  |sinclairql.sh  |Sinclairql    |installed|~15-30m |partial |TODO"
)

# Full build order (cheap wins first, heavy last). The default selection filters
# the two Sailfish stages because Stage 1 needs account-gated SDK media. Add
# --with-media after staging it. The licensed pair is appended only by
# --include-licensed. An explicit --only always opts that key in.
DEFAULT_ORDER=(kolibrios toaruos helenos 9front reactos haiku templeos amigaos qnx alpine tinycore
  freedos msdos-win1 win311 win95 win98 win2000 os2warp redstar3
  android-x86 postmarketos sailfishos sailfishos-gui serenityos
  bridge-base c64 atarist apple2 amiga amstradcpc redstar2 mpf2 vic20 plus4 c128 pet2001 cbm8032 decos)

# ---------------------------------------------------------------------------
c_reset=$'\e[0m'
c_bold=$'\e[1m'
c_red=$'\e[31m'
c_grn=$'\e[32m'
c_yel=$'\e[33m'
c_cyn=$'\e[36m'
log() { printf '%s[build-all]%s %s\n' "$c_cyn" "$c_reset" "$*"; }
warn() { printf '%s[build-all] WARN:%s %s\n' "$c_yel" "$c_reset" "$*" >&2; }
err() { printf '%s[build-all] ERROR:%s %s\n' "$c_red" "$c_reset" "$*" >&2; }

field() { # field <manifest-row> <1-based index>
  echo "$1" | awk -F'|' -v n="$2" '{gsub(/^[ \t]+|[ \t]+$/,"",$n); print $n}'
}
row_for() { # row_for <key>  -> the manifest row, or empty
  local k="$1" r
  for r in "${MANIFEST[@]}"; do
    [ "$(field "$r" 1)" = "$k" ] && {
      echo "$r"
      return 0
    }
  done
  return 1
}
has_flag() { # has_flag <manifest-row> <flag>
  local flags flag
  flags="$(field "$1" 8)"
  flag="$2"
  case ",${flags// /}," in *",$flag,"*) return 0 ;; *) return 1 ;; esac
}

print_manifest() {
  printf '%s%-13s %-16s %-13s %-9s %-8s %-8s %s%s\n' "$c_bold" \
    KEY SCRIPT OUTPUT-DIR CLASS EST AUTO PRODUCES "$c_reset"
  local r
  for r in "${MANIFEST[@]}"; do
    printf '%-13s %-16s %-13s %-9s %-8s %-8s %s\n' \
      "$(field "$r" 1)" "$(field "$r" 2)" "$(field "$r" 3)" \
      "$(field "$r" 4)" "$(field "$r" 5)" "$(field "$r" 6)" "$(field "$r" 7)"
  done
  cat <<'EOF'

CLASS:  fast=live-ISO/prebuilt exotic  retro=prebuilt Win/DOS base+injection
        heavy=from-source compile or full unattended install  licensed=needs a supplied ISO
AUTO:   full=hands-off to GUI  full*=hands-off build, 1 runtime footnote
        1-click=one one-time interactive click/calibration  supplied=scripted once you supply source media
EOF
}

# ---------------------------------------------------------------------------
usage() { sed -n '/^# USAGE:/,/^# ====/p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; }

ONLY=()
CLASS_FILTER=""
INCLUDE_LICENSED=0
WITH_MEDIA=0
FAIL_FAST=0
DRY_RUN=0
SKIP_VERIFY=0
CHECK_ASSETS=0
while [ $# -gt 0 ]; do
  case "$1" in
    --list)
      print_manifest
      exit 0
      ;;
    --only)
      [ $# -ge 2 ] || {
        err "--only requires a guest key"
        exit 2
      }
      ONLY+=("$2")
      shift 2
      ;;
    --only=*)
      ONLY+=("${1#*=}")
      shift
      ;;
    --class)
      [ $# -ge 2 ] || {
        err "--class requires a class"
        exit 2
      }
      CLASS_FILTER="$2"
      shift 2
      ;;
    --class=*)
      CLASS_FILTER="${1#*=}"
      shift
      ;;
    --with-media)
      WITH_MEDIA=1
      shift
      ;;
    --include-licensed)
      INCLUDE_LICENSED=1
      shift
      ;;
    --check-assets)
      CHECK_ASSETS=1
      shift
      ;;
    --fail-fast)
      FAIL_FAST=1
      shift
      ;;
    --skip-verify)
      SKIP_VERIFY=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      err "unknown arg: $1"
      usage
      exit 2
      ;;
  esac
done

# Resolve the list of guests to build and retain every media-gated omission for
# the notices and final summary.
BUILD_LIST=()
S_KEY=()
S_REASON=()
record_skip() {
  S_KEY+=("$1")
  S_REASON+=("$2")
}
if [ "${#ONLY[@]}" -gt 0 ]; then
  # explicit --only wins and can pull in any class (incl. licensed)
  for k in "${ONLY[@]}"; do
    if row_for "$k" >/dev/null; then BUILD_LIST+=("$k"); else
      err "no such guest: $k (see --list)"
      exit 2
    fi
  done
else
  for k in "${DEFAULT_ORDER[@]}"; do
    r="$(row_for "$k")"
    [ -z "$CLASS_FILTER" ] || [ "$(field "$r" 4)" = "$CLASS_FILTER" ] || continue
    if has_flag "$r" media && [ "$WITH_MEDIA" = 0 ]; then
      record_skip "$k" "Sailfish SDK emulator media required (use --with-media)"
    else
      BUILD_LIST+=("$k")
    fi
  done
  # Licensed guests are outside DEFAULT_ORDER and have their own explicit opt-in.
  for r in "${MANIFEST[@]}"; do
    [ "$(field "$r" 4)" = licensed ] || continue
    [ -z "$CLASS_FILTER" ] || [ "$CLASS_FILTER" = licensed ] || continue
    k="$(field "$r" 1)"
    if [ "$INCLUDE_LICENSED" = 1 ]; then
      BUILD_LIST+=("$k")
    else
      record_skip "$k" "user-supplied licensed ISO required (use --include-licensed)"
    fi
  done
fi

if [ "${#BUILD_LIST[@]}" -eq 0 ]; then
  for i in "${!S_KEY[@]}"; do warn "skipping ${S_KEY[$i]}: ${S_REASON[$i]}"; done
  err "nothing selected to build (check --class and media opt-in flags)"
  exit 2
fi

# Verify-skip pass-through: the per-guest scripts read either VERIFY or DO_VERIFY.
if [ "$SKIP_VERIFY" = 1 ]; then export VERIFY=0 DO_VERIFY=0; fi

# Optional asset preflight (docs/lab/ASSETS-MANIFEST.md): verify staged licensed
# media + repo assets + env vars for the selected guests BEFORE building anything.
if [ "$CHECK_ASSETS" = 1 ]; then
  ca_args=()
  for k in "${BUILD_LIST[@]}"; do ca_args+=(--only "$k"); done
  if ! "$SCRIPT_DIR/check-assets.sh" "${ca_args[@]}"; then
    err "asset preflight failed — stage the missing inputs (see docs/lab/ASSETS-MANIFEST.md)"
    exit 3
  fi
fi

log "gallery root : $GALLERY_ROOT"
log "build order  : ${BUILD_LIST[*]}"
[ "$DRY_RUN" = 1 ] && log "(dry-run: no guest scripts will be executed)"
for i in "${!S_KEY[@]}"; do warn "skipping ${S_KEY[$i]}: ${S_REASON[$i]}"; done
echo

# ---------------------------------------------------------------------------
declare -a R_KEY R_STATUS R_SECS
overall_rc=0
for key in "${BUILD_LIST[@]}"; do
  row="$(row_for "$key")"
  script="$SCRIPT_DIR/$(field "$row" 2)"
  dir="$GALLERY_ROOT/$(field "$row" 3)"
  est="$(field "$row" 5)"

  printf '%s============================================================%s\n' "$c_bold" "$c_reset"
  log "GUEST $c_bold$key$c_reset  (script=$(basename "$script"), est=$est, -> $dir)"

  if [ ! -x "$script" ] && [ ! -f "$script" ]; then
    err "missing build script: $script"
    R_KEY+=("$key")
    R_STATUS+=("MISSING")
    R_SECS+=("0")
    overall_rc=1
    if [ "$FAIL_FAST" = 1 ]; then break; else continue; fi
  fi

  if [ "$DRY_RUN" = 1 ]; then
    log "would run: bash $script"
    R_KEY+=("$key")
    R_STATUS+=("DRY")
    R_SECS+=("0")
    continue
  fi

  start=$(date +%s)
  # Run the guest build in its own process so env + set -e inside it are isolated.
  # stdout/stderr stream live; we only capture the exit code.
  if bash "$script"; then st="OK"; else
    st="FAIL"
    overall_rc=1
  fi
  secs=$(($(date +%s) - start))

  R_KEY+=("$key")
  R_STATUS+=("$st")
  R_SECS+=("$secs")
  if [ "$st" = OK ]; then log "$c_grn$key OK$c_reset in ${secs}s"; else err "$key FAILED after ${secs}s"; fi
  if [ "$st" = FAIL ] && [ "$FAIL_FAST" = 1 ]; then
    err "--fail-fast: stopping"
    break
  fi
  echo
done

# ---------------------------------------------------------------------------
echo
printf '%s================= build-all summary =================%s\n' "$c_bold" "$c_reset"
printf '%s%-16s %-8s %8s%s\n' "$c_bold" GUEST STATUS TIME "$c_reset"
for i in "${!R_KEY[@]}"; do
  s="${R_STATUS[$i]}"
  col="$c_reset"
  case "$s" in OK) col="$c_grn" ;; FAIL | MISSING) col="$c_red" ;; DRY | SKIP) col="$c_yel" ;; esac
  printf '%-16s %s%-8s%s %7ss\n' "${R_KEY[$i]}" "$col" "$s" "$c_reset" "${R_SECS[$i]}"
done
for i in "${!S_KEY[@]}"; do
  printf '%-16s %s%-8s%s %s\n' "${S_KEY[$i]}" "$c_yel" SKIPPED "$c_reset" "${S_REASON[$i]}"
done
echo
if [ "$overall_rc" = 0 ]; then
  if [ "$DRY_RUN" = 1 ]; then
    log "dry-run complete: ${#R_KEY[@]} guest command(s) shown; nothing was built."
  else
    log "${c_grn}all ${#R_KEY[@]} selected guest builds completed.$c_reset  Next: wire tiles via streamhost/tiles-manifest.sh + bring-up-all.sh."
  fi
  [ "${#S_KEY[@]}" -eq 0 ] || log "${#S_KEY[@]} media-gated builder(s) skipped; see the summary and opt-in flags above."
else
  if [ "$DRY_RUN" = 1 ]; then
    warn "dry-run found one or more missing guest scripts."
  else
    warn "one or more guests did not complete — re-run just those with --only <key> (add FORCE=1 to rebuild)."
  fi
fi
exit "$overall_rc"
