System hostname = openbsd
Which network interface do you wish to configure = vio0
IPv4 address for vio0 = autoconf
IPv6 address for vio0 = none
Password for root account = kernelhive
Start sshd(8) by default = no
Do you expect to run the X Window System = yes
Do you want the X Window System to be started by xenodm(1) = no
Change the default console to com0 = no
Setup a user = no
What timezone are you in = UTC
Which disk is the root disk = sd0
Use (W)hole disk MBR, whole disk (G)PT, (O)penBSD area or (E)dit = whole
Use (A)uto layout, (E)dit auto layout, or create (C)ustom layout = a
Location of sets = http
HTTP proxy URL = none
HTTP Server = 10.0.2.2:8079
Server directory = pub/OpenBSD/7.9/amd64
Unable to connect using https. Use http instead = yes
Set name(s) = -comp* -game* +site* done
Directory does not contain SHA256.sig. Continue without verification = yes
Checksum test for site79.tgz failed. Continue anyway = yes
Continue anyway = yes
Location of sets = done
Exit to (S)hell, (H)alt or (R)eboot = halt
