#!/bin/bash
# =============================================================================
# stations/mame-native/media-hook.sh — FRESH MEDIA FOR AN IN-PROCESS RESTORE.
# The companion of stations/mame-native/x11-runtime.sh, emitted next to it as
# an --aux-file on every LOADST station that mounts media
# (MAME_NATIVE_DISK_TEMPLATE). Both halves of one protocol live in this file,
# so the hook and its client are always the same generation.
#
# WHY. MAME opens its media read-write. A hard-disk image takes every guest
# write in place; a floppy's track data lives in the drive's in-memory image
# and is committed to the file whenever the motor stops (floppy.cpp mon_w).
# The launcher gives every START a fresh copy of each immutable template, which
# is the whole fix for a cold-relaunch station. A LOADST station's Restore is
# not a start: `LOADST golden` restores CPU, RAM and every device's registers,
# but no savestate carries a floppy's track data (floppy.cpp saves the drive
# mechanics only) and a hard disk is the file itself — so the visitor's saved
# file survived Restore (samcoupe rig, 2026-10-05: `khproof` still in DIR after
# LOADST). Hence: PAUSE, swap fresh copies in, LOADST, RESUME.
#
# media-hook.sh --arm <station-dir> <src>:<dst>...
#   (the launcher, before it starts MAME) writes <station-dir>/media-hook/
#   boot.lua; the launcher passes `-pluginspath <station-dir>/media-hook`.
#   boot.lua runs at Lua-engine start whatever the state — NOT
#   -autoboot_script, which fires from a persistent scheduler timer that
#   restoring golden.sta restores as already fired (measured: it never ran).
#   On the machine's start-up reset it binds each <dst> to the image device
#   holding it, writes `armed <pid>` to <station-dir>/media-reset.armed, and
#   from then on polls <station-dir>/media-reset.req once per frame (the frame
#   notifier keeps running while the machine is paused). A request unloads
#   every image, copies <src> over <dst>, loads it again, and answers
#   `OK <nonce>` / `ERR <why> <nonce>` in media-reset.ack.
#
# media-hook.sh --media-reset <station-dir> <ctl.sock> <state>
#   (serve/reset-tile.sh and `labctl reset`, ONLY when media-reset.armed names
#   the running emulator's pid) PAUSE over the ctlsock, request the swap, wait
#   for its ack, LOADST <state>, RESUME — all while paused, so no guest write
#   lands between the fresh copy and the restore. Exit 0 = restored; anything
#   else = the caller falls back to the service restart, whose start copies
#   fresh media anyway.
# =============================================================================
set -euo pipefail

case "${1:-}" in
  --arm)
    [ "$#" -ge 3 ] || {
      echo "usage: media-hook.sh --arm <station-dir> <src>:<dst>..." >&2
      exit 2
    }
    base="$2"
    shift 2
    # the paths go into Lua string literals verbatim: refuse anything that
    # would need escaping rather than escape it
    for p in "$base" "$@"; do
      case "$p" in *[!A-Za-z0-9._/:+-]*)
        echo "media-hook: path needs Lua escaping, refusing: $p" >&2
        exit 1
        ;;
      esac
    done
    mkdir -p "$base/media-hook"
    {
      printf -- '-- boot.lua — the media hook, GENERATED by mame-native/media-hook.sh --arm; do not edit.\n'
      printf 'local dir = "%s"\nlocal media = {\n' "$base"
      for pair in "$@"; do
        printf '  { src = "%s", dst = "%s" },\n' "${pair%%:*}" "${pair#*:}"
      done
      printf '}\n'
      cat <<'LUA'
local function put(name, text)
  local p = dir .. "/" .. name
  local f = io.open(p .. ".tmp", "w")
  if not f then return end
  f:write(text, "\n")
  f:close()
  os.rename(p .. ".tmp", p)
end
local function copy(src, dst)
  local i = io.open(src, "rb")
  if not i then return "cannot read " .. src end
  local data = i:read("a")
  i:close()
  local o = io.open(dst .. ".tmp", "wb")
  if not o then return "cannot write " .. dst end
  o:write(data)
  o:close()
  local ok, err = os.rename(dst .. ".tmp", dst)
  if not ok then return err end
end
local pidf = io.open("/proc/self/stat", "r")
local pid = pidf:read("l"):match("^(%d+)")
pidf:close()
local function swap(nonce)
  local err
  for _, m in ipairs(media) do
    m.img:unload()
    err = copy(m.src, m.dst)
    if not err then err = m.img:load(m.dst) end
    if err then
      err = m.dst .. ": " .. tostring(err)
      break
    end
  end
  put("media-reset.ack", (err and ("ERR " .. err) or "OK") .. " " .. nonce)
end
-- bind each copy to the image device holding it at start-up (an unloaded image
-- has no filename to find it by); re-bound on every machine reset
_G.kh_media_reset_boot = emu.add_machine_reset_notifier(function()
  for _, m in ipairs(media) do
    m.img = nil
    for _, img in pairs(manager.machine.images) do
      if img.filename == m.dst then m.img = img end
    end
    if not m.img then
      put("media-reset.armed", "unbound " .. pid .. " " .. m.dst)
      return
    end
  end
  _G.kh_media_reset = _G.kh_media_reset or emu.add_machine_frame_notifier(function()
    local f = io.open(dir .. "/media-reset.req", "r")
    if not f then return end
    local nonce = f:read("l") or "-"
    f:close()
    os.remove(dir .. "/media-reset.req")
    swap(nonce)
  end)
  put("media-reset.armed", "armed " .. pid)
end)
LUA
    } >"$base/media-hook/boot.lua"
    ;;
  --media-reset)
    [ "$#" -eq 4 ] || {
      echo "usage: media-hook.sh --media-reset <station-dir> <ctl.sock> <state>" >&2
      exit 2
    }
    exec python3 - "$2" "$3" "$4" <<'PY'
import os, secrets, socket, sys, time
base, sock, state = sys.argv[1], sys.argv[2], sys.argv[3]
t0 = time.monotonic()
s = socket.socket(socket.AF_UNIX)
s.settimeout(10)
try:
    s.connect(sock)
except OSError as e:
    print(f"media reset: ctl {sock}: {e}")
    sys.exit(125)
f = s.makefile("rw")
f.readline()  # HELLO
seq = 0
def verb(line, timeout):
    """one mamectl/1 request; the reply line, EV lines skipped"""
    global seq
    seq += 1
    s.settimeout(timeout)
    f.write(f"{seq} {line}\n")
    f.flush()
    while True:
        r = f.readline()
        if not r:
            raise OSError("ctl socket closed")
        if r.startswith(f"{seq} "):
            return r.strip()
try:
    r = verb("PAUSE", 10)
    if " OK" not in r:
        print(f"media reset: PAUSE: {r}")
        sys.exit(1)
    ack = os.path.join(base, "media-reset.ack")
    req = os.path.join(base, "media-reset.req")
    nonce = secrets.token_hex(4)
    try:
        os.remove(ack)
    except FileNotFoundError:
        pass
    with open(req + ".tmp", "w") as w:
        w.write(nonce + "\n")
    os.rename(req + ".tmp", req)
    # the hook answers at the paused machine's frame pace (~40-50 ms) plus the
    # copy itself; a 32 MB hard disk is well under a second
    deadline = time.monotonic() + 20
    got = ""
    while time.monotonic() < deadline:
        try:
            with open(ack) as a:
                got = a.readline().strip()
        except FileNotFoundError:
            got = ""
        if got.endswith(" " + nonce):
            break
        time.sleep(0.02)
    else:
        print(f"media reset: the media hook did not answer within 20 s ({got or 'no ack'})")
        sys.exit(1)
    if not got.startswith("OK "):
        print(f"media reset: {got}")
        sys.exit(1)
    swapped = time.monotonic() - t0
    r = verb(f"LOADST {state}", 60)
    if " OK" not in r:
        print(f"media reset: fresh media in, but LOADST {state}: {r}")
        sys.exit(1)
    print(f"fresh media in {swapped:.2f} s, LOADST {state} ({r.split(' OK ', 1)[-1]})")
except OSError as e:
    print(f"media reset: {e}")
    sys.exit(125)
finally:
    try:
        verb("RESUME", 10)
    except OSError:
        pass
PY
    ;;
  *)
    echo "usage: media-hook.sh --arm <station-dir> <src>:<dst>... | --media-reset <station-dir> <ctl.sock> <state>" >&2
    exit 2
    ;;
esac
