10 REM PRIME FACTORS
20 FAST:SCNCLR:PRINT "PRIME FACTORS - TYPE 0 TO STOP"
30 DO:PRINT:INPUT "WHOLE NUMBER";N:N=INT(ABS(N))
40 IF N=0 THEN EXIT
50 PRINT N;"=";:F=2:S$=""
60 DO WHILE F*F<=N
70 IF N/F=INT(N/F) THEN PRINT S$;F;:S$="*":N=N/F:ELSE F=F+1
80 LOOP
90 PRINT S$;N
100 LOOP:SLOW
