; phase 1 — boot the 4.3BSD miniroot and restore the root dump onto rq1.
set rq0 ra81
at rq0 miniroot
set rq1 ra81
at rq1 rq.dsk
set rq2 disable
set rq3 disable
set rp disable
set lpt disable
set rl disable
set tq disable
set tu disable
att ts 43.tap
set tti 7b
set tto 7b
load -o boot42 0
d r10 9
d r11 0
run 2
