#!/usr/bin/env node
// ============================================================================
//  scripts/analytics/catalogue.mjs — render the probe catalogue, and gate it.
//  ---------------------------------------------------------------------------
//  The catalogue is declared once, in TypeScript, so that `reach('...')` is
//  type-checked at every call site (spa/src/analytics/catalogue.ts). The report
//  tool and the operator both need it as data, so it is RENDERED here into
//  registry/analytics-catalogue.json — a generated file like every other one in
//  this repo, byte-parity gated by `make analytics-catalogue-check`.
//
//  THE GATE IS THE INTERESTING HALF. `check` fails if a declared probe id does
//  not appear literally in the source file that declares itself its owner.
//  Without it the report has two zeros that look identical and mean opposite
//  things — "nobody uses this feature" and "I declared a probe and never
//  called it" — and the second kind is what gets working code deleted. It also
//  catches the likelier drift: a call site MOVED to another file, leaving the
//  catalogue pointing at a file that no longer mentions it.
//
//  Node reads the .ts file directly (type stripping, Node >= 22.18), so there is
//  no build step and no second copy of the catalogue to fall out of date.
// ============================================================================

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..', '..');
const SPA = join(ROOT, 'spa');
const OUT = join(ROOT, 'registry', 'analytics-catalogue.json');

const { PROBES, FLOWS } = await import(
  join(SPA, 'src', 'analytics', 'catalogue.ts')
);

/** The rendered document. Sorted so the file is stable across edits. */
function render() {
  const probes = {};
  for (const id of Object.keys(PROBES).sort()) {
    const p = PROBES[id];
    probes[id] = {
      area: p.area,
      owner: p.owner,
      what: p.what,
      grades: [...p.grades],
      ...(p.consumes ? { consumes: p.consumes } : {}),
    };
  }
  const flows = {};
  for (const id of Object.keys(FLOWS).sort()) {
    flows[id] = { area: FLOWS[id].area, what: FLOWS[id].what, steps: [...FLOWS[id].steps] };
  }
  return `${JSON.stringify(
    {
      _comment:
        'GENERATED by scripts/analytics/catalogue.mjs from spa/src/analytics/catalogue.ts. ' +
        'Do not hand-edit: `make analytics-catalogue-check` compares this byte for byte ' +
        'with what the TypeScript source renders right now.',
      version: 1,
      probes,
      flows,
    },
    null,
    2,
  )}\n`;
}

/** Every complaint the gate can make, in one pass. */
async function problems() {
  const found = [];
  const seen = new Map();
  for (const [id, spec] of Object.entries(PROBES)) {
    let source = seen.get(spec.owner);
    if (source === undefined) {
      source = await readFile(join(SPA, spec.owner), 'utf8').catch(() => null);
      seen.set(spec.owner, source);
    }
    if (source === null) {
      found.push(`${id}: owner ${spec.owner} does not exist`);
      continue;
    }
    // The literal id, quoted, is what a call site writes. Anything clever here
    // (an AST walk, a looser match) buys a way for a commented-out call to pass.
    if (!source.includes(`'${id}'`) && !source.includes(`"${id}"`)) {
      found.push(`${id}: declared, but ${spec.owner} contains no call site for it`);
    }
    if (spec.consumes && !(spec.consumes in PROBES)) {
      found.push(`${id}: consumes '${spec.consumes}', which is not a declared probe`);
    }
    if (spec.consumes && !PROBES[spec.consumes].grades.includes('auto')) {
      found.push(`${id}: consumes '${spec.consumes}', which is not an 'auto' producer`);
    }
    if (!spec.grades.length) found.push(`${id}: declares no grades, so it can never report`);
  }
  return found;
}

const mode = process.argv[2] ?? 'emit';
if (mode === 'emit') {
  await writeFile(OUT, render());
  console.log(`analytics catalogue: wrote ${OUT}`);
} else if (mode === 'check') {
  const found = await problems();
  const current = await readFile(OUT, 'utf8').catch(() => null);
  if (current !== render()) found.unshift(`${OUT} is stale — run \`make analytics-catalogue\``);
  if (found.length) {
    console.error('analytics catalogue: FAILED');
    for (const line of found) console.error(`  - ${line}`);
    process.exit(1);
  }
  console.log(`analytics catalogue: ok (${Object.keys(PROBES).length} probes, ${Object.keys(FLOWS).length} flows)`);
} else {
  console.error('usage: catalogue.mjs [emit|check]');
  process.exit(2);
}
