#!/usr/bin/env node
// ============================================================================
//  scripts/analytics/catalogue.mjs — render the probe catalogue, and gate it.
//  ---------------------------------------------------------------------------
//  The catalogue is declared once, in TypeScript, so that `reach('...')` is
//  type-checked at every call site (spa/src/analytics/catalogue.ts). The report
//  tool and the operator both need it as data, so it is RENDERED here into
//  registry/analytics-catalogue.json — a generated file like every other one in
//  this repo, byte-parity gated by `make analytics-catalogue-check`.
//
//  THE GATE IS THE INTERESTING HALF. `check` fails if a declared probe id does
//  not appear literally in the source file that declares itself its owner.
//  Without it the report has two zeros that look identical and mean opposite
//  things — "nobody uses this feature" and "I declared a probe and never
//  called it" — and the second kind is what gets working code deleted. It also
//  catches the likelier drift: a call site MOVED to another file, leaving the
//  catalogue pointing at a file that no longer mentions it.
//
//  Node reads the .ts file directly (type stripping, Node >= 22.18), so there is
//  no build step and no second copy of the catalogue to fall out of date.
//
//  TWO PLANES, ONE DOCUMENT, ONE COMMAND. The SPA declares its probes in
//  TypeScript; the Python serving plane declares its own in
//  scripts/serve/probes.py, because that is the file the serving process
//  imports and a declaration that lived anywhere else could drift from what is
//  deployed. Rather than a second generator and a second `make` target to
//  forget, this one ASKS probes.py for its catalogue (`python3 probes.py`,
//  which prints it as JSON) and renders both sections here. The gate below runs
//  over both, so `make analytics-catalogue-check` stays the single command that
//  checks everything.
// ============================================================================

import { readFile, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..', '..');
const SPA = join(ROOT, 'spa');
const OUT = join(ROOT, 'registry', 'analytics-catalogue.json');

const { PROBES, FLOWS } = await import(
  join(SPA, 'src', 'analytics', 'catalogue.ts')
);

//  The server plane's declaration, read from the module the serving process
//  actually imports. Running it beats parsing it: a regex over the file would
//  be a SECOND reader of the catalogue that can disagree with Python's, which
//  is the exact class of bug this gate exists to prevent.
const SERVER_PROBES = JSON.parse(
  execFileSync('python3', [join(ROOT, 'scripts', 'serve', 'probes.py')], {
    encoding: 'utf8',
  }),
);
//  Owner paths on this side are repo-relative (the serving plane has no single
//  root the way spa/ does), so this is where they resolve from.
const SERVER_OWNER_ROOT = ROOT;
//  A probe whose owner is the declaring file itself would pass the call-site
//  gate on its own declaration, which is the one way to get a zero that means
//  nothing at all.
const SERVER_DECL = 'scripts/serve/probes.py';

/** The rendered document. Sorted so the file is stable across edits. */
function render() {
  const probes = {};
  for (const id of Object.keys(PROBES).sort()) {
    const p = PROBES[id];
    probes[id] = {
      area: p.area,
      owner: p.owner,
      what: p.what,
      grades: [...p.grades],
      ...(p.consumes ? { consumes: p.consumes } : {}),
    };
  }
  const flows = {};
  for (const id of Object.keys(FLOWS).sort()) {
    flows[id] = { area: FLOWS[id].area, what: FLOWS[id].what, steps: [...FLOWS[id].steps] };
  }
  const serverProbes = {};
  for (const id of Object.keys(SERVER_PROBES).sort()) {
    const p = SERVER_PROBES[id];
    serverProbes[id] = {
      area: p.area,
      owner: p.owner,
      what: p.what,
      ...(p.consumes ? { consumes: p.consumes } : {}),
    };
  }
  return `${JSON.stringify(
    {
      _comment:
        'GENERATED by scripts/analytics/catalogue.mjs from spa/src/analytics/catalogue.ts ' +
        'and scripts/serve/probes.py. Do not hand-edit: `make analytics-catalogue-check` ' +
        'compares this byte for byte with what those two sources render right now.',
      version: 2,
      probes,
      flows,
      // The serving plane's own branch probes. Kept in a separate section
      // rather than merged into `probes`: they share the store (class
      // `server`) and the LEFT-JOIN idea, and nothing else. They carry no
      // grades — nobody asked the server for anything — and the report must
      // never sum them with a client count.
      serverProbes,
    },
    null,
    2,
  )}\n`;
}

/** Every complaint the gate can make, in one pass. */
async function problems() {
  const found = [];
  const seen = new Map();
  for (const [id, spec] of Object.entries(PROBES)) {
    let source = seen.get(spec.owner);
    if (source === undefined) {
      source = await readFile(join(SPA, spec.owner), 'utf8').catch(() => null);
      seen.set(spec.owner, source);
    }
    if (source === null) {
      found.push(`${id}: owner ${spec.owner} does not exist`);
      continue;
    }
    // The literal id, quoted, is what a call site writes. Anything clever here
    // (an AST walk, a looser match) buys a way for a commented-out call to pass.
    if (!source.includes(`'${id}'`) && !source.includes(`"${id}"`)) {
      found.push(`${id}: declared, but ${spec.owner} contains no call site for it`);
    }
    if (spec.consumes && !(spec.consumes in PROBES)) {
      found.push(`${id}: consumes '${spec.consumes}', which is not a declared probe`);
    }
    if (spec.consumes && !PROBES[spec.consumes].grades.includes('auto')) {
      found.push(`${id}: consumes '${spec.consumes}', which is not an 'auto' producer`);
    }
    if (!spec.grades.length) found.push(`${id}: declares no grades, so it can never report`);
  }
  found.push(...(await serverProblems()));
  return found;
}

/** The same gate, for the Python plane. Identical rule, different tree. */
async function serverProblems() {
  const found = [];
  const seen = new Map();
  // ID grammar is analytics.ID_RE: these rows land in the same `probe` table as
  // the client's and a name the store would reject is a probe that can only
  // ever read zero.
  const idOk = /^[a-z][a-zA-Z0-9]*(\.[a-z][a-zA-Z0-9]*){0,4}$/;
  for (const [id, spec] of Object.entries(SERVER_PROBES)) {
    if (!idOk.test(id)) found.push(`${id}: not a valid probe id (serve/analytics.py ID_RE)`);
    // Same table, different class. A shared name would still be two distinct
    // rows, but nobody reading the report would believe that.
    if (id in PROBES) found.push(`${id}: declared by BOTH the SPA and the server catalogue`);
    if (spec.owner === SERVER_DECL) {
      found.push(`${id}: owner is ${SERVER_DECL} itself, so the call-site gate would check its own declaration`);
      continue;
    }
    let source = seen.get(spec.owner);
    if (source === undefined) {
      source = await readFile(join(SERVER_OWNER_ROOT, spec.owner), 'utf8').catch(() => null);
      seen.set(spec.owner, source);
    }
    if (source === null) {
      found.push(`${id}: owner ${spec.owner} does not exist`);
      continue;
    }
    if (!source.includes(`hit('${id}')`) && !source.includes(`hit("${id}")`)) {
      found.push(`${id}: declared, but ${spec.owner} contains no hit() call site for it`);
    }
    if (spec.consumes && !(spec.consumes in SERVER_PROBES)) {
      found.push(`${id}: consumes '${spec.consumes}', which is not a declared server probe`);
    }
  }
  return found;
}

const mode = process.argv[2] ?? 'emit';
if (mode === 'emit') {
  await writeFile(OUT, render());
  console.log(`analytics catalogue: wrote ${OUT}`);
} else if (mode === 'check') {
  const found = await problems();
  const current = await readFile(OUT, 'utf8').catch(() => null);
  if (current !== render()) found.unshift(`${OUT} is stale — run \`make analytics-catalogue\``);
  if (found.length) {
    console.error('analytics catalogue: FAILED');
    for (const line of found) console.error(`  - ${line}`);
    process.exit(1);
  }
  console.log(
    `analytics catalogue: ok (${Object.keys(PROBES).length} client probes, ` +
      `${Object.keys(SERVER_PROBES).length} server probes, ${Object.keys(FLOWS).length} flows)`,
  );
} else {
  console.error('usage: catalogue.mjs [emit|check]');
  process.exit(2);
}
