10 HOME : PRINT "GUESS MY LETTER, A TO Z"
20 R = RND ( - PEEK (78) - 256 * PEEK (79))
30 L = INT ( RND (1) * 26) + 65:T = 0
40 PRINT : PRINT "PRESS A LETTER: ";: GET K$: PRINT K$
50 K = ASC (K$):T = T + 1
60 IF K < 65 OR K > 90 THEN PRINT "A LETTER, PLEASE.": GOTO 40
70 IF K < L THEN PRINT "LATER IN THE ALPHABET.": GOTO 40
80 IF K > L THEN PRINT "EARLIER IN THE ALPHABET.": GOTO 40
90 PRINT "YES! ";T;" GUESSES. AGAIN (Y/N)? ";: GET K$: PRINT K$
100 IF K$ = "Y" THEN 10
