#!/usr/bin/env python3
"""Generate the Kernel Hive release notes from git history.

WEEK CUTOFF. A week ENDS at Sunday 09:00 Europe/Helsinki, and that boundary is
EXCLUSIVE: a commit stamped exactly 09:00:00 belongs to the week that is just
starting. Week 1 starts at the FIRST commit in the repo -- the open-source
release (0d8ed78, 2026-08-07) -- and ends at the first Sunday 09:00 Helsinki
at-or-after it, so week 1 is usually a stub. Every later week is the 7-day
span between consecutive Sunday-09:00 boundaries. Boundaries are stepped on the
LOCAL wall clock through zoneinfo, so they stay at 09:00 Helsinki across DST
transitions (the first one that matters here is 2026-10-25). Weeks are numbered
1..N chronologically and PRESENTED newest-first; the week containing the newest
commit is IN PROGRESS.

WHICH TIMESTAMP, AND WHY IT IS CLAMPED. A commit is bucketed by its AUTHOR
date -- stable across the rebases and merges this repo does constantly, where
the committer date is not. Two clamps make that safe, because `git log` order
is committer-date order and neither date is trustworthy on its own:
  * author > committer means a clock ran ahead (or a date was rewritten); the
    committer date is the later of the two proofs that the commit exists, so
    the earlier of the pair wins;
  * a stamp after the generation time cannot have happened, so it is pulled
    back to `now`. Without this ONE skewed commit invents an empty week for
    every week between now and its date, and the README's 4-week window then
    shows nothing but empty weeks.
  * a stamp before the repo's own root commit is pulled up to it, for the
    mirror-image reason (a `git am` of a 2019 patch would invent 300 weeks).
The window endpoints are then min()/max() over those clamped stamps -- never
`commits[0]` / `commits[-1]`, which are committer-date order and would silently
drop any commit whose author date sorts outside them. build() asserts the
buckets conserve the commit count, so a future variation on that mistake fails
loudly instead of quietly shrinking the notes.

This file owns the FACTS (git, clamps, classification, week cutting);
scripts/release_notes_render.py owns the WORDING (markdown, digest selection,
escaping). They are split because one file was over the repo's 600-line Python
budget, and that is the seam that does not tangle.

THREE OUTPUTS, all regenerated by `make release-notes`:
  * README.md            -- "## Release notes", the most recent 4 weeks as a
                            compact digest, between HTML marker comments,
                            immediately before "## Contributing".
  * docs/RELEASE-NOTES.md -- the full archive: every week, every commit, each
                            bullet carrying its short sha linked to GitHub.
  * spa/public/release-notes.json -- machine-readable, consumed by the SPA
                            About view (published by a UI bundle redeploy,
                            `scripts/serve-https-spa.sh deploy`).

WHY --check IGNORES THE IN-PROGRESS WEEK. These artifacts are DERIVED from git
history, so the in-progress week changes with literally every commit -- the very
commit a contributor is pushing would make the gate red, and so would a sibling
agent's merge that the pusher cannot fix. An unfixable gate teaches SKIP_GATE=1
(docs/lab/AGENT-CI-EXIT-RULE.md), so --check compares only CLOSED weeks: weeks
whose Sunday-09:00 boundary has already passed relative to the NEWEST COMMIT
(never the wall clock, so the same tree passes on Sunday and on Monday). The
mutable tail is deliberately out of scope. Regenerate after a MERGE, not only
after an edit.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

# Sibling module, imported the way scripts/stations_registry/* imports
# poster_registry: scripts/ is sys.path[0] both when this file is run as a
# script and under `unittest discover -s scripts`.
from release_notes_render import render_archive, render_readme_section, splice_readme

REPO_ROOT = Path(__file__).resolve().parents[1]
TZ = ZoneInfo("Europe/Helsinki")
CUTOFF_LABEL = "Sunday 09:00 Europe/Helsinki"

STATIONS = "Stations"
DEPENDENCIES = "Dependencies"
OTHER = "Other"
SECTION_ORDER = [
    STATIONS,
    "Gallery UI",
    "Streaming daemon",
    "Retronet",
    "Tooling & infrastructure",
    "Docs",
    DEPENDENCIES,
    OTHER,
]

# Non-station scopes only -- station ids are read from registry/stations/*.json
# at runtime so a new station needs no edit here. Entries beyond the locked
# mapping are obvious aliases of an already-named bucket (a tooling word, or the
# head of a multi-part scope such as box-sync / retronet-bot / docs-research);
# the section SET is fixed.
_ALIAS_GROUPS = {
    # "posters" is poster prose + photo galleries, i.e. gallery content.
    "Gallery UI": "spa ui gallery posters grid",
    # The daemon and the I/O planes it owns: control socket, pointer, keyboard
    # (key-tel, keyboard-lag), framebuffer sharing, telemetry, idle pause.
    "Streaming daemon": (
        "streamhost rust encoder transport ctlsock nsptr input drawshm telemetry idle keyboard key rel"
    ),
    "Retronet": "retronet",
    # vom (vom-reference) and exit (exit-rule) are reference documents.
    "Docs": "docs readme research playbook handover terminology vom exit",
    "Tooling & infrastructure": (
        "registry scripts build ci make dev agents lint tools host labctl provision box bridge "
        "debridge workflow serve migrate chore harvest repro qwenit qwen gate guards chroot "
        "devwatch vicectl vice tiles public hooks xvfb verify e2e config fleet assets rename "
        "split mame third_party guest coldboot reset platform rollout"
    ),
}
SCOPE_ALIASES = {scope: section for section, scopes in _ALIAS_GROUPS.items() for scope in scopes.split()}

# Station-adjacent scopes that are not registry ids (renames, per-machine work).
STATION_ALIASES = {
    "alpha-nt": "w2kalpha",  # pre-rename id, renamed 2026-08-10
    "alpha": "w2kalpha",
    "tru64exec": "tru64",
    "atarist-mame": "atarist",
    "nextstep-pointer": "nextstep",
    "iris": "indyr4400",  # SGI IRIS/Indy work
    "xerox": "alto",
}

# A hand-written `deps(spa): ...` is a dependency bump like Dependabot's own.
DEP_SCOPES = {"deps", "dependencies", "dependabot"}

# THREE subject shapes carry a scope, and they are deliberately not one regex:
#   SCOPE_RE     "tru64: fix ..."  / "deps(spa): ..."  -- a real prefix, STRIPPED
#                from the bullet text (the locked single-token form, plus the
#                conventional-commit `type(scope):` variant this repo also uses).
#   PHRASE_RE    "retronet web: ...", "c128 + c64 fixtures: ..." -- the scope is
#                the FIRST word of a short phrase. Only the section is taken from
#                it; the text is kept whole, because stripping "chokanji poster:"
#                would throw away "poster".
#   LEAD_RE      "chokanji joins the retronet web plane: ..." -- prose that opens
#                with a station id. Recognised for STATIONS ONLY: a station id is
#                a distinctive identifier, whereas "make", "docs" or "build" open
#                ordinary English sentences all the time.
SCOPE_RE = re.compile(r"^([a-z0-9][a-z0-9+._/-]*)(?:\(([a-z0-9][a-z0-9+._/-]*)\))?: ")
PHRASE_RE = re.compile(r"^([a-z0-9][a-z0-9+._/-]*)(?:[ +]+[^\s:]+){1,5}: ")
LEAD_RE = re.compile(r"^([a-z0-9][a-z0-9+._/-]*)")
DEP_SUBJECT_RE = re.compile(r"^Bump the .* (group|dependency)")
GIT_FORMAT = "%H%x1f%h%x1f%aI%x1f%cI%x1f%an%x1f%s"

# Words whose canonical spelling is not "capitalise the first letter": product
# names, acronyms and command names that open a subject once the scope prefix is
# gone. Station ids and path-like words (stage.sh, qmp-type.py) are left exactly
# as written -- they are identifiers, and "Stage.sh" is a different file.
DISPLAY_CASE = {
    "vice": "VICE",
    "nextstep": "NeXTSTEP",
    "irix": "IRIX",
    "mame": "MAME",
    "icq": "ICQ",
    "labctl": "labctl",
    "qemu": "QEMU",
    "spa": "SPA",
    "ui": "UI",
    "html": "HTML",
    "http": "HTTP",
    "ssh": "ssh",
    "npm": "npm",
    "iptables": "iptables",
}


def run_git(args: list[str]) -> str:
    return subprocess.run(["git", "-C", str(REPO_ROOT), *args], check=True, capture_output=True, text=True).stdout


def station_ids() -> set[str]:
    return {p.stem for p in (REPO_ROOT / "registry" / "stations").glob("*.json")}


def _bucket(key: str, stations: set[str]) -> tuple[str, str | None] | None:
    """(section, label) for a scope key, or None when nothing recognises it."""
    for candidate in _scope_candidates(key):
        if candidate in DEP_SCOPES:
            return DEPENDENCIES, None
        if candidate in stations:
            # The registry id, never the raw scope: `mpf2/kc854` must label the
            # entry `mpf2` so every Stations label is a real station id (the SPA
            # renders it as a station chip).
            return STATIONS, candidate
        if candidate in STATION_ALIASES:
            return STATIONS, STATION_ALIASES[candidate]
        if candidate in SCOPE_ALIASES:
            return SCOPE_ALIASES[candidate], key
    return None


def classify(subject: str, author: str, stations: set[str]) -> tuple[str, str | None]:
    """Return (section, scope). `scope` is None when nothing labels the entry."""
    # Dependencies first: dependabot in this repo writes "build(deps): bump the
    # cargo group ..." which the scope regex never matches, so the author clause
    # is load-bearing.
    if "dependabot" in author.lower() or DEP_SUBJECT_RE.match(subject):
        return DEPENDENCIES, None
    prefix = SCOPE_RE.match(subject)
    if prefix:
        # `type(scope): ` -- the TYPE decides first ("docs(rel-pointer): " is a
        # doc), the inner scope is the fallback ("feat(tru64): " is a station).
        keys = [prefix.group(1), prefix.group(2)] if prefix.group(2) else [prefix.group(1)]
        if any(key in DEP_SCOPES for key in keys):
            return DEPENDENCIES, None
        for key in keys:
            hit = _bucket(key, stations)
            if hit:
                return hit
        return OTHER, keys[0]
    lead = LEAD_RE.match(subject)
    if lead:
        hit = _bucket(lead.group(1), stations)
        if hit and (PHRASE_RE.match(subject) or hit[0] == STATIONS):
            return hit
    return OTHER, None


def _scope_candidates(scope: str):
    """Whole scope first, then progressively coarser heads.

    Multi-part scopes are real here (docs/research, retronet-bot, ctlsock+tools,
    mpf2/kc854), and folding them onto their first component puts them in the
    bucket a reader expects.
    """
    yield scope
    head = re.split(r"[/+]", scope)[0]
    if head != scope:
        yield head
    dashed = head.split("-")[0]
    if dashed != head:
        yield dashed


def recase(text: str, stations: set[str]) -> str:
    """Upper-case the opening letter -- unless the opening word is a name.

    "stage.sh per-session staging" must not become "Stage.sh": that is a
    different filename. Same for station ids (macos753), command names (labctl)
    and acronyms whose real spelling is in DISPLAY_CASE (VICE, NeXTSTEP).
    """
    lead = re.match(r"[A-Za-z0-9][A-Za-z0-9+._/-]*", text)
    if not lead:
        return text
    word = lead.group(0)
    key = word.lower()
    if key in DISPLAY_CASE:
        return DISPLAY_CASE[key] + text[len(word) :]
    dashed = key.split("-")[0]
    if dashed in DISPLAY_CASE and dashed != key:
        return DISPLAY_CASE[dashed] + text[len(dashed) :]
    if key in stations or key in STATION_ALIASES or re.search(r"[./_][A-Za-z0-9]", word):
        return text
    return text[:1].upper() + text[1:]


def bullet_text(subject: str, stations: set[str] | None = None) -> str:
    """The commit subject as a bullet: a `scope: ` prefix stripped, then recased.

    Only the single-token prefix is stripped. A phrase scope ("chokanji poster:")
    stays in the text -- dropping it would lose "poster", and the section already
    carries the classification.
    """
    text = SCOPE_RE.sub("", subject, count=1).strip() or subject
    return recase(text, stations if stations is not None else set())


def first_boundary(epoch: datetime) -> datetime:
    """First Sunday 09:00 Helsinki at-or-after `epoch` (exclusive end)."""
    local = epoch.astimezone(TZ)
    day = local.date() + timedelta(days=(6 - local.weekday()) % 7)
    candidate = datetime(day.year, day.month, day.day, 9, 0, tzinfo=TZ)
    return candidate if candidate > local else candidate + timedelta(days=7)


def next_boundary(boundary: datetime) -> datetime:
    """Step one week on the LOCAL wall clock, so 09:00 survives DST."""
    naive = boundary.replace(tzinfo=None) + timedelta(days=7)
    return naive.replace(tzinfo=TZ)


# Every comparison below (start <= when < end, end > newest, candidate > local)
# is between aware datetimes that share the SAME cached ZoneInfo object, which
# Python compares by naive wall clock rather than by instant. At a 09:00 cutoff
# the two orderings agree everywhere, including both fold states of every DST
# Sunday; they would diverge only if the cutoff hour were moved into the
# 03:00-04:00 repeated hour. Keep the cutoff out of the fold, or normalise to
# UTC before comparing.


def read_commits(now: datetime | None = None) -> list[dict]:
    """Every non-merge commit, with a bucketing stamp that cannot lie (see the
    module docstring's clamps)."""
    now = now or datetime.now(TZ)
    out = run_git(["log", "--no-merges", f"--format={GIT_FORMAT}"])
    commits = []
    for line in out.splitlines():
        if not line.strip():
            continue
        sha, short, authored, committed, author, subject = line.split("\x1f", 5)
        stamp = min(
            datetime.fromisoformat(authored).astimezone(TZ),
            datetime.fromisoformat(committed).astimezone(TZ),
            now,
        )
        commits.append(
            {
                "sha": sha,
                "short": short,
                "when": stamp,
                "author": author,
                "subject": subject,
            }
        )
    if not commits:
        return commits
    floor = repo_epoch(commits)
    for commit in commits:
        commit["when"] = max(commit["when"], floor)
    return commits


def repo_epoch(commits: list[dict]) -> datetime:
    """The root commit's stamp -- the open-source release, and the floor for all
    the others. Falls back to the earliest stamp if HEAD's roots are unreachable
    (a grafted or shallow clone)."""
    by_sha = {c["sha"]: c["when"] for c in commits}
    roots = [by_sha[sha] for sha in run_git(["rev-list", "--max-parents=0", "HEAD"]).split() if sha in by_sha]
    return min(roots) if roots else min(c["when"] for c in commits)


def week_spans(epoch: datetime, newest: datetime) -> list[tuple[datetime, datetime]]:
    spans = []
    start, end = epoch, first_boundary(epoch)
    while True:
        spans.append((start, end))
        if end > newest:
            return spans
        start, end = end, next_boundary(end)


def assert_conserved(weeks: list[dict], commits: list[dict]) -> None:
    """The buckets must hold every input commit.

    The weeks tile [epoch, last boundary) with no gap and no overlap, so any
    mismatch means a commit fell outside the window -- which is exactly how this
    generator used to lose commits in silence. Loud beats plausible-looking.
    """
    bucketed = sum(week["commitCount"] for week in weeks)
    if bucketed != len(commits):
        raise SystemExit(
            f"release-notes: BUG — {len(commits)} commits read, {bucketed} bucketed into weeks. "
            "The week window does not cover every commit; fix the endpoints, do not paper over it."
        )


def build(now: datetime | None = None) -> dict:
    commits = read_commits(now)
    if not commits:
        raise SystemExit("release-notes: no commits found")
    stations = station_ids()
    # min/max, NOT commits[-1]/commits[0]: `git log` sorts by COMMITTER date and
    # this repo rebases, so the author-date extremes are not at the ends.
    epoch = min(c["when"] for c in commits)
    newest = max(c["when"] for c in commits)

    weeks = []
    for number, (start, end) in enumerate(week_spans(epoch, newest), start=1):
        picked = [c for c in commits if start <= c["when"] < end]
        buckets: dict[str, list[dict]] = {}
        for c in picked:
            section, scope = classify(c["subject"], c["author"], stations)
            buckets.setdefault(section, []).append(
                {
                    "scope": scope,
                    "text": bullet_text(c["subject"], stations),
                    "sha": c["short"],
                    "date": c["when"].date().isoformat(),
                }
            )
        sections = []
        for title in SECTION_ORDER:
            entries = buckets.get(title)
            if not entries:
                continue
            block = {"title": title, "count": len(entries)}
            if title == DEPENDENCIES:
                block["entries"] = []
                block["collapsed"] = True
            else:
                block["entries"] = entries
            sections.append(block)
        weeks.append(
            {
                "number": number,
                "start": start.isoformat(),
                "end": end.isoformat(),
                "startDate": start.date().isoformat(),
                "endDate": end.date().isoformat(),
                "inProgress": end > newest,
                "commitCount": len(picked),
                "sections": sections,
            }
        )

    assert_conserved(weeks, commits)
    return {
        "cutoff": CUTOFF_LABEL,
        "epoch": epoch.isoformat(),
        "generatedFrom": run_git(["rev-parse", "--short", "HEAD"]).strip(),
        "weeks": list(reversed(weeks)),
    }


def outputs(data: dict) -> dict[Path, str]:
    readme = REPO_ROOT / "README.md"
    return {
        readme: splice_readme(readme.read_text(), render_readme_section(data)),
        REPO_ROOT / "docs" / "RELEASE-NOTES.md": render_archive(data),
        REPO_ROOT / "spa" / "public" / "release-notes.json": json.dumps(data, indent=2) + "\n",
    }


def closed(data: dict) -> list[dict]:
    return [w for w in data["weeks"] if not w["inProgress"]]


def check() -> int:
    if run_git(["rev-parse", "--is-shallow-repository"]).strip() == "true":
        print("release-notes: SKIP — shallow clone, no history to derive from (use fetch-depth: 0)")
        return 0
    fresh = build()
    disk_path = REPO_ROOT / "spa" / "public" / "release-notes.json"
    if not disk_path.exists():
        print(f"release-notes: STALE — {disk_path.relative_to(REPO_ROOT)} is missing")
        return 1
    disk = json.loads(disk_path.read_text())
    stale = []
    # Only CLOSED weeks are compared (see the module docstring): the in-progress
    # week changes with every commit and would make this gate red for everyone.
    if closed(disk) != closed(fresh):
        stale.append("spa/public/release-notes.json: closed weeks differ from git history")
    if disk.get("cutoff") != fresh["cutoff"] or disk.get("epoch") != fresh["epoch"]:
        stale.append("spa/public/release-notes.json: cutoff/epoch differ from git history")
    # The two markdown files are checked against the JSON on disk, so an
    # in-progress-week difference never reaches them either.
    for path, rendered in outputs(disk).items():
        if path.read_text() != rendered:
            stale.append(f"{path.relative_to(REPO_ROOT)}: out of sync with release-notes.json")
    for line in stale:
        print(f"release-notes: STALE — {line}")
    if stale:
        print("release-notes: run `make release-notes` and commit the result")
        return 1
    print(f"release-notes: OK — {len(closed(fresh))} closed weeks match git history")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the release notes from git history.")
    parser.add_argument(
        "--check", action="store_true", help="exit non-zero if the outputs are stale (closed weeks only)"
    )
    parser.add_argument("--json", action="store_true", help="print the JSON to stdout without writing")
    parser.add_argument("--write", action="store_true", help="regenerate in place (the default)")
    args = parser.parse_args(argv)
    if args.check:
        return check()
    data = build()
    if args.json:
        print(json.dumps(data, indent=2))
        return 0
    for path, text in outputs(data).items():
        path.write_text(text)
        print(f"release-notes: wrote {path.relative_to(REPO_ROOT)}")
    for week in reversed(data["weeks"]):
        flag = " (in progress)" if week["inProgress"] else ""
        print(f"  week {week['number']}: {week['startDate']}..{week['endDate']}  {week['commitCount']} commits{flag}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
