"""The keyword transcoder's key tables (scripts/stations_registry/keyword_keys.py)
and the chord-pacing rule for keyword-entry stations (validate_typein.py).

The tables are generated from the stations' own keymaps, so these tests read the
real committed keymaps: a keymap regenerated by scripts/dev/mame-keymap.py that
changes a legend the transcoder relies on fails here, not on the exhibit floor.
"""

from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from stations_registry import keyword_keys as kk
from stations_registry import validate_typein as vt
from stations_registry.constants import REPO

SPECTRUM = REPO / "streamhost/stations/zxspectrum/zxspectrum.keymap"
ZX81 = REPO / "streamhost/stations/zx81/zx81.keymap"
CAPS, SYM, SHIFT, ENTER = 0x2A, 0x36, 0x2A, 0x1C


class SpectrumTableTest(unittest.TestCase):
    table = kk.spectrum_table(SPECTRUM)

    def test_k_mode_keywords_are_one_key_in_rom_spelling(self) -> None:
        self.assertEqual(self.table["statements"]["PRINT"], [[0x19]])
        self.assertEqual(self.table["statements"]["GO TO"], [[0x22]])
        self.assertEqual(self.table["aliases"], {"CONT": "CONTINUE", "RAND": "RANDOMIZE"})

    def test_symbol_shift_and_extended_mode_chords(self) -> None:
        self.assertEqual(self.table["tokens"]['"'], [[SYM, 0x19]])
        self.assertEqual(self.table["tokens"]["<="], [[SYM, 0x10]])
        self.assertEqual(self.table["tokens"]["INK"], [[CAPS, SYM], [SYM, 0x2D]])
        self.assertEqual(self.table["tokens"]["READ"], [[CAPS, SYM], [0x1E]])
        self.assertEqual(self.table["tokens"]["OPEN #"], [[CAPS, SYM], [SYM, 0x05]])

    def test_mame_name_fix_point_and_cat(self) -> None:
        # The 48K ROM's E-mode digit table and a rig agree: 8 is POINT, 9 is CAT.
        self.assertEqual(self.table["tokens"]["POINT"], [[CAPS, SYM], [SYM, 0x09]])
        self.assertEqual(self.table["tokens"]["CAT"], [[CAPS, SYM], [SYM, 0x0A]])

    def test_letters_and_what_ascii_cannot_mean(self) -> None:
        self.assertEqual(self.table["chars"]["a"], [[0x1E]])
        self.assertEqual(self.table["chars"]["A"], [[CAPS, 0x1E]])
        for legend in ("(c)", "£", "`"):
            self.assertNotIn(legend, self.table["tokens"])

    def test_a_fixed_mame_name_fails_instead_of_double_fixing(self) -> None:
        text = SPECTRUM.read_text(encoding="utf-8").replace("(             CAT", "(             POINT", 1)
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "fixed.keymap"
            path.write_text(text, encoding="utf-8")
            with self.assertRaises(kk.KeymapError):
                kk.spectrum_table(path)


class Zx81TableTest(unittest.TestCase):
    table = kk.zx81_table(ZX81)

    def test_function_mode_and_the_keywords_mame_leaves_out(self) -> None:
        self.assertEqual(self.table["tokens"]["INT"], [[SHIFT, ENTER], [0x13]])
        self.assertEqual(self.table["tokens"]["INKEY$"], [[SHIFT, ENTER], [0x30]])
        self.assertEqual(self.table["statements"]["CLS"], [[0x2F]])
        self.assertEqual(self.table["statements"]["COPY"], [[0x2C]])

    def test_shift_tokens_but_never_editing_keys(self) -> None:
        self.assertEqual(self.table["tokens"]["**"], [[SHIFT, 0x23]])
        self.assertEqual(self.table["tokens"]['""'], [[SHIFT, 0x10]])
        self.assertEqual(self.table["tokens"][","], [[SHIFT, 0x34]])
        for edit in ("EDIT", "GRAPHICS", "DELETE", "FUNCTION", "Left"):
            self.assertNotIn(edit, self.table["tokens"])

    def test_no_lower_case(self) -> None:
        self.assertEqual(self.table["chars"]["a"], self.table["chars"]["A"])


def station(type_in: dict, hold: int = 200, gap: int = 200) -> dict:
    return {
        "id": "zxspectrum",
        "_path": "registry/stations/zxspectrum.json",
        "stream": {"transport": "streamhost"},
        "runtime": {
            "stationEnv": {"SH_KEY_MIN_HOLD_MS": str(hold), "SH_KEY_MIN_GAP_MS": str(gap)},
            "x11": {"auxFiles": ["streamhost/stations/zxspectrum/zxspectrum.keymap"]},
        },
        "typeIn": type_in,
    }


class ChordPacingTest(unittest.TestCase):
    def errors(self, type_in: dict) -> list[str]:
        errors: list[str] = []
        vt.validate_type_in([station(type_in)], errors)
        return errors

    def test_accepts_settles_that_cover_one_chord(self) -> None:
        self.assertEqual(self.errors({"dialect": "sinclair-basic", "perCharMs": 400, "newDelayMs": 3000}), [])

    def test_refuses_a_settle_shorter_than_one_chord(self) -> None:
        errors = self.errors({"dialect": "sinclair-basic", "perCharMs": 400, "enterDelayMs": 300})
        self.assertTrue(any("typeIn.enterDelayMs=300 is below one chord (400 ms" in e for e in errors), errors)
        # newDelayMs defaults to enterDelayMs, so it is short too.
        self.assertTrue(any("typeIn.newDelayMs=300" in e for e in errors), errors)

    def test_refuses_a_case_rule_the_transcoder_owns(self) -> None:
        errors = self.errors({"dialect": "zx81-basic", "perCharMs": 400, "case": "unshifted"})
        self.assertTrue(any("transcoder owns letter case" in e for e in errors), errors)

    def test_refuses_a_keyword_station_without_a_keymap(self) -> None:
        row = station({"dialect": "sinclair-basic", "perCharMs": 400})
        row["runtime"]["x11"]["auxFiles"] = []
        errors: list[str] = []
        vt.validate_type_in([row], errors)
        self.assertTrue(any("no station keymap" in e for e in errors), errors)


if __name__ == "__main__":
    unittest.main()
