import type { ArchetypeId, Transport } from './three/archetypeRegistry';

// Runtime public exhibit + transport row from /gallery-manifest.json.
export interface VMManifestEntry {
  id: string;
  /** Curated year represented by the physical exhibit; drives hall sections. */
  era_year?: number;
  displayName: string;
  year: number | string;
  lineage: string;
  arch: string;
  ramMB?: number;
  /** Memory for machines under a megabyte, where ramMB rounds to a wrong 0. */
  ramKB?: number;
  notes?: string;

  // OPTIONAL curated museum metadata (used for placards), carried by the
  // manifest itself (registry/stations/<id>.json `museum` is the source).
  accent?: string;         // hex accent for the exhibit unit
  era?: string;            // e.g. "1990s"
  eraSoftware?: string[];  // period software titles
  periodBrowser?: string;  // the period web browser
  iconicApps?: string[];   // iconic games/apps
  blurb?: string;          // one-line curator note

  // Runtime lineup/binding fields. SceneV2 selects its model assembly from
  // archetypeId; the grid uses the same metadata for stream/poster behavior.
  order?: number;
  /** Soft hide (registry `listing`): false ⇒ this exhibit is NOT announced —
   *  no grid card, no desk in the 3D hall, not in any count. The row is still
   *  carried here on purpose, because `/os/:osId` resolves out of it: a hidden
   *  station stays deep-linkable and streams exactly as before. Discoverability,
   *  never access control. Absent ⇒ listed. */
  listed?: boolean;
  archetypeId?: ArchetypeId;
  transport?: Transport;
  eraLabel?: string;
  signalEndpoint?: string | null;
  endpoint?: string;
  pointerRel?: boolean;
  hardwareInput?: boolean;
  /** Graphical exhibit whose pointer is RELATIVE only — no absolute path to
   *  the guest, so the cursor cannot track the visitor's finger 1:1. */
  relativePointerOnly?: boolean;
  coldBoot?: boolean;

  // STATION-TYPE grouping dimensions (docs/ANALYTICS.md), sourced from the
  // registry's own `emulator.family` / `ui` / `reset.resetMode` — see
  // scripts/stations_registry/render.py's `emit_gallery_manifest`. Low
  // cardinality by construction (a handful of emulator families, five UI
  // kinds, four reset modes), unlike `id`, which stays a separate attribute
  // wherever these travel onto a span. Not every station has all three: a
  // poster entry has no live golden to report a reset mode for.
  emulatorFamily?: string;
  uiKind?: string;
  resetMode?: string;

  /** True only for a `resetMode=relaunch` station whose fixture declares
   *  SH_RESET_CTL_SOCK: the reset goes through an in-process control socket
   *  (ekactl quit) rather than a unit restart, so the stream's own
   *  WebTransport never drops. Absent/false ⇒ assume the old teardown/
   *  reconnect path (useRestoreFlow.ts). Derived in
   *  emit_gallery_manifest — there is no matching registry input field. */
  resetKeepsStream?: boolean;

  // OPTIONAL boot-video replay descriptor, merged at runtime from
  // /boot/index.json (BOOT-VIDEO-REPLAY-SPEC §4). Additive: absent ⇒ today's
  // behaviour. Carries the durations/paths the UI can use without a rebuild;
  // the mp4 path also drives the runtime binding's boot-video badge/mount.
  bootVideo?: {
    mp4: string;
    poster?: string;
    sprite?: string;
    vtt?: string;
    durationMs?: number;
    width?: number;
    height?: number;
    hasAudio?: boolean;
  };
}

/** Fully validated row stored by the app after loading the runtime manifest. */
export interface RuntimeVMManifestEntry extends VMManifestEntry {
  era_year: number;
  accent: string;
  era: string;
  eraSoftware: string[];
  periodBrowser: string;
  iconicApps: string[];
  blurb: string;
  order: number;
  archetypeId: ArchetypeId;
  transport: Transport;
  eraLabel: string;
}

export type EnrichedVM = RuntimeVMManifestEntry;

export type PosterInlineRun =
  | { kind: 'text'; text: string }
  | { kind: 'emphasis'; children: PosterInlineRun[] }
  | { kind: 'strong'; children: PosterInlineRun[] }
  | { kind: 'link'; href: string; children: PosterInlineRun[] };

export type PosterBlock =
  | { kind: 'heading'; level: 2 | 3; runs: PosterInlineRun[] }
  | { kind: 'paragraph'; runs: PosterInlineRun[] }
  | { kind: 'list'; items: PosterInlineRun[][] }
  | { kind: 'quote'; runs: PosterInlineRun[] }
  | { kind: 'image'; src: string; alt: string };

export interface PosterImage {
  src: string;
  alt: string;
  caption: string;
  credit?: string;
}

/** A freely-licensed historical photo shown in the Origins-section carousel.
 *  Fields mirror `registry/posters/gallery/<id>.resolved.json` (generated by
 *  scripts/tools/fetch-poster-gallery.py), minus the `sha256` integrity field
 *  which is a build-time-only concern and never reaches the UI. */
export interface PosterGalleryImage {
  src: string;
  alt: string;
  caption: string;
  author: string;
  authorUrl?: string;
  license: string;
  licenseId: string;
  licenseUrl: string;
  shareAlike: boolean;
  sourceUrl: string;
  sourceName: string;
  width: number;
  height: number;
}

/** An outbound link to a period advertisement/sales poster that is NOT
 *  bundled as image bytes (almost always still under copyright). */
export interface PosterAdLink {
  title: string;
  url: string;
  source: string;
}

export interface PosterDoc {
  title: string;
  subtitle: string;
  hero?: string;
  images: PosterImage[];
  blocks: PosterBlock[];
  /** Present only for the round-1 hardware-era stations that have a resolved
   *  gallery file; absent everywhere else (no carousel, no layout change). */
  gallery?: {
    images: PosterGalleryImage[];
    adLinks?: PosterAdLink[];
  };
}

/** A type-in demo listing for a station (registry: demoProgram), typed into the
 *  live guest by the stage menu. The visitor presses ENTER to run it. */
export interface DemoProgram {
  /** Menu label, e.g. "Type in a demo program". */
  label: string;
  /** The listing, one BASIC line per entry (no trailing newline). */
  readonly lines: readonly string[];
  /** Typed after the listing, WITHOUT a newline — the visitor presses ENTER. */
  runCommand: string;
  /** Milliseconds one character takes to REACH this guest (streamhost's
   *  SH_KEY_MIN_HOLD_MS + SH_KEY_MIN_GAP_MS). Omitted where the UI default
   *  DEMO_PER_CHAR_MS already covers the station; the registry validates that
   *  whichever applies is not below the daemon's drain rate. */
  readonly perCharMs?: number;
  /** Wait after ENTER: one delay for all lines, or per-line delays (omitted entries use the default). */
  readonly enterDelayMs?: number | readonly number[];
}

/** How a machine's keyboard differs from a PC's (registry `keyboard` block). */
export interface GuestKeyboard {
  /** Guest character -> the host character whose keystroke produces it. */
  readonly charMap?: Readonly<Record<string, string>>;
  /** 'upper-only': no lower case, and the shifted letter row is symbols, so
   *  letters must be sent UNSHIFTED or they arrive as punctuation. */
  readonly letterCase?: 'upper-only';
}

/** BASIC dialects the type-in editor highlights (registry `typeIn.dialect`;
 *  keyword lists in ui/typein/basicDialects.ts). */
export type BasicDialect =
  | 'cbm-basic' | 'bbc-basic' | 'msx-basic' | 'locomotive-basic' | 'superbasic'
  | 'sam-basic' | 'oric-basic' | 'color-basic' | 'applesoft' | 'kc-basic' | KeywordDialect;

/** Keyword-entry BASICs: one key is a keyword, so the editor types key chords
 *  through the keyword transcoder (ui/typein/keywordEntry.ts). */
export type KeywordDialect = 'sinclair-basic' | 'zx81-basic';

/** Set1 scancodes pressed in order and released in reverse: one keystroke. */
export type KeyChord = readonly number[];

/** A keyword-entry station's key table (data/keywordKeys.ts, generated from the
 *  station keymap by scripts/stations_registry/keyword_keys.py). */
export interface KeywordTable {
  readonly dialect: KeywordDialect;
  /** Statement keywords: one key, only where the ROM's cursor is K. */
  readonly statements: Readonly<Record<string, readonly KeyChord[]>>;
  /** Keywords and symbols the machine enters from any cursor mode. */
  readonly tokens: Readonly<Record<string, readonly KeyChord[]>>;
  /** Plain characters: letters (per the machine's case), digits, space. */
  readonly chars: Readonly<Record<string, readonly KeyChord[]>>;
  /** Accepted ASCII spellings -> the table's own (ROM) spelling. */
  readonly aliases: Readonly<Record<string, string>>;
  readonly enter: KeyChord;
}

/** How letters become keystrokes (registry `typeIn.case`). */
export type TypeInCase = 'as-typed' | 'unshifted' | 'code-upper' | 'code-lower';

/** A station's opt-in for the type-in code editor (registry `typeIn`). Every
 *  pacing number is validated against the station's own drain rate by
 *  scripts/stations_registry/validate_typein.py; absent block = no editor. */
export interface TypeInConfig {
  readonly dialect: BasicDialect;
  /** Wait per typed character, >= SH_KEY_MIN_HOLD_MS + SH_KEY_MIN_GAP_MS. */
  readonly perCharMs: number;
  readonly lineDelayMs?: number;
  readonly enterDelayMs?: number;
  /** Added per line already typed: the settle grows with the listing (ZX81). */
  readonly enterDelayPerLineMs?: number;
  /** Screen width and the extra wait after each wrap: the machine drops keys
   *  while it scrolls (mpf2). */
  readonly wrapPause?: { readonly cols: number; readonly ms: number; readonly promptCols?: number };
  readonly case?: TypeInCase;
  /** Longest logical line the machine's screen editor accepts. */
  readonly maxLineChars?: number;
  /** One sentence shown above the Type button (a step the machine needs first). */
  readonly hint?: string;
  /** Longer ENTER settles for named direct commands (whole line, upper case):
   *  samcoupe's NEW redraws the MGT banner and eats the next key; the 48K
   *  Spectrum's NEW re-tests its memory with the keyboard off. */
  readonly settleAfter?: Readonly<Record<string, number>>;
  /** Printable ASCII the station's keymap cannot produce: flagged, never typed. */
  readonly unreachable?: string;
}

/** One example program (registry/examples/<id>/), inlined into poster-docs.json. */
interface TypeInExample {
  file: string;
  kind: 'draw' | 'input' | 'game' | 'sound' | 'other';
  title: string;
  description?: string;
  text: string;
}

/** A link to the machine's own manual (registry/examples/<id>/index.json). */
interface TypeInManual {
  title: string;
  url: string;
  lang?: string;
  note?: string;
}

export interface TypeInDoc {
  examples: TypeInExample[];
  manuals: TypeInManual[];
}
