//! Native `vicectl/1` input sink for a host-native, headless VICE station.
//!
//! The sibling of `mame_sock.rs`, and deliberately the same state machine: the
//! browser receive path only `try_lock`s and offers; connect / banner / write /
//! ack-read / reconnect all live in one background task; transitions ride a
//! bounded ordered queue; a breach drops the queue and resynchronizes instead of
//! replaying. What differs is the wire's key verb, and that difference is the
//! whole design of this wave.
//!
//! MAME's `KEY <0|1> <port> <field>` names a matrix CELL, so every converted
//! MAME station needed its own map dumped out of its own machine. VICE's
//! `KEY <0|1> <keysym>` carries an **X11 keysym**, and VICE resolves keysym ->
//! keyboard matrix through the machine's own `.vkm` keymap — the SAME file the
//! bridged kiosk used. A converted station therefore reproduces the kiosk's
//! character behaviour BY CONSTRUCTION (virtual shift, deshift, shift-lock, the
//! C128 alternative set), the daemon needs no per-station matrix map, and the
//! SPA needs no hand-authored `charMap`. See
//! `docs/lab/research/vice-input-plane.md` §2(d) and
//! `docs/lab/research/vice-daemon-plane.md`.
//!
//! HOST LAYOUT IS APPLIED HERE, BEFORE THE WIRE, and that is not a detail: the
//! bridged station produces `@` for the visitor's Shift+2 because X applied the
//! US layout before VICE saw the key. So `SH_VICESOCK_KEYMAP` is
//! `scancode -> (plain keysym, shifted keysym)` — one table shared by all seven
//! stations, generated by `scripts/dev/vice-keymap.py` — and this sink
//! SUBSTITUTES the shift level for character keys while still forwarding
//! `Shift_L`/`Shift_R` as themselves, so `.vkm` entries flagged `MAP_MOD_SHIFT`
//! keep working. The keysym a key was PRESSED with is remembered and reused for
//! its release, so releasing Shift before the character never strands a key
//! down in the emulated matrix.
//!
//! PACING LIVES IN THE EMULATOR, exactly as it does on the MAME path: the
//! `vicectl` module holds the burst and releases it per key at
//! `VICE_CTL_KEY_HOLD`/`_GAP`, with `VICE_CTL_KEY_EXCL=1` serializing
//! non-modifier presses (mandatory — the same 36-edge burst without it prints
//! `N ''N`). The daemon's `SH_KEY_MIN_*` gate only runs on the QEMU/dbus path.
//! The ack budget below is sized for that: ~8.5 keys/s is the guest's ceiling.
//!
//! KEYBOARD ONLY. All seven VICE stations are `pointer: none` today; pointer
//! records are rejected rather than silently invented. The `c64` GEOS pointer
//! is the last station of the wave and gets its verb when it is measured.
//!
//! Single-injector rule (BINDING, inherited): a station launched with
//! `VICE_CTL_SOCK` must not also be driven through VICE's binary monitor —
//! `kbdbuf_feed()` pokes PETSCII into the KERNAL buffer behind the matrix and
//! the two injectors cannot see each other.

use std::collections::VecDeque;
use std::sync::atomic::{AtomicBool, AtomicU64, AtomicU8, Ordering};
use std::sync::{Arc, Mutex, TryLockError};
use std::time::Duration;

use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader, Lines};
use tokio::net::unix::{OwnedReadHalf, OwnedWriteHalf};
use tokio::net::UnixStream;
use tokio::sync::Notify;
use tokio::time::Instant;

use crate::realtime_input::{
    AcceptedSeq, KeyEvent, PointerAbs, RealtimeInputSink, Reject, SinkHealth,
};
use crate::vice_keymap::ViceKeyMap;

const ORDERED_CAPACITY: usize = 64;
const HEALTH_STARTING: u8 = 0;
const HEALTH_HEALTHY: u8 = 1;
const HEALTH_DOWN: u8 = 2;
/// Ack deadline for the OLDEST unacked write. Every KEY is pace-delayed by the
/// module (~120 ms per key at the 60/60 ms default, and a station may raise it),
/// so the base covers connection setup and the per-paced allowance covers the
/// queue standing in front of the oldest write.
const ACK_BASE: Duration = Duration::from_secs(5);
const ACK_PER_PACED: Duration = Duration::from_millis(200);

/// Router modifier bits 0 (Left Shift) and 1 (Right Shift) — `modifier_bit()`
/// in `realtime_input.rs`. Read from router truth rather than tracked here, so
/// the shift level and the key edge can never disagree.
const SHIFT_MASK: u16 = 0b11;

fn trace_on() -> bool {
    static TRACE: std::sync::OnceLock<bool> = std::sync::OnceLock::new();
    *TRACE.get_or_init(|| {
        std::env::var("SH_VICESOCK_TRACE")
            .map(|v| v == "on" || v == "1")
            .unwrap_or(false)
    })
}

#[derive(Default)]
struct Counters {
    accepted: AtomicU64,
    dropped: AtomicU64,
    overflow: AtomicU64,
    backend_down: AtomicU64,
    /// Key edges whose scancode has no keymap row. Counted AND logged per edge:
    /// a silent unmapped reject was the one loss the 2026-08-12 MAME typing
    /// investigation could not see in any counter.
    unmapped: AtomicU64,
}

impl Counters {
    fn line(&self) -> String {
        format!(
            "accepted={} dropped={} overflow={} backend-down={} unmapped={}",
            self.accepted.load(Ordering::Relaxed),
            self.dropped.load(Ordering::Relaxed),
            self.overflow.load(Ordering::Relaxed),
            self.backend_down.load(Ordering::Relaxed),
            self.unmapped.load(Ordering::Relaxed),
        )
    }
}

/// One wire verb line, formatted without the seq stamp: the background task
/// stamps seqs at send time, so a reconnect renumbers cleanly and a queued
/// command never carries a stale seq across connections.
struct Cmd {
    line: String,
    /// Pace-delayed ack class: extends the ack deadline.
    paced: bool,
}

impl Cmd {
    /// `KEY <0|1> <keysym>`. The keysym goes on the wire in DECIMAL — the exact
    /// value `keyboard_key_pressed()` takes inside VICE, with no prefix for the
    /// module to have to parse.
    fn key(down: bool, keysym: u32) -> Self {
        Self {
            line: format!("KEY {} {keysym}", u8::from(down)),
            paced: true,
        }
    }

    /// `KEYCLEAR`: drop every held key and all pacing state. Sent once per
    /// connection, as the resync preamble.
    fn keyclear() -> Self {
        Self {
            line: "KEYCLEAR".to_string(),
            paced: false,
        }
    }
}

#[derive(Default)]
struct Pending {
    ordered: VecDeque<Cmd>,
    /// scancode -> the keysym its PRESS went out with. A release must repeat
    /// that keysym even if the visitor let Shift go first, or the emulated
    /// matrix keeps the key down forever.
    held: Vec<(u16, u32)>,
}

struct Shared {
    pending: Mutex<Pending>,
    notify: Notify,
    health: AtomicU8,
    counters: Counters,
    closed: AtomicBool,
    /// The shared host-layout table. Empty = fail-closed keyboard.
    keymap: Arc<ViceKeyMap>,
    /// One-shot log for a pointer record on a keyboard-only station.
    warned_pointer: AtomicBool,
}

pub struct ViceSockSink {
    shared: Arc<Shared>,
}

impl ViceSockSink {
    pub fn new(path: String, keymap: Arc<ViceKeyMap>) -> Arc<Self> {
        eprintln!("[input-router] vicesock sink socket={path}");
        let shared = Arc::new(Shared {
            pending: Mutex::new(Pending::default()),
            notify: Notify::new(),
            health: AtomicU8::new(HEALTH_STARTING),
            counters: Counters::default(),
            closed: AtomicBool::new(false),
            keymap,
            warned_pointer: AtomicBool::new(false),
        });
        tokio::spawn(vicesock_task(path, shared.clone()));
        let log_shared = shared.clone();
        tokio::spawn(async move {
            let mut tick = tokio::time::interval(Duration::from_secs(10));
            loop {
                tick.tick().await;
                if log_shared.closed.load(Ordering::Relaxed) {
                    break;
                }
                eprintln!("[input-router] vicesock {}", log_shared.counters.line());
            }
        });
        Arc::new(Self { shared })
    }

    fn lock_pending(&self) -> Result<std::sync::MutexGuard<'_, Pending>, Reject> {
        match self.shared.pending.try_lock() {
            Ok(p) => Ok(p),
            Err(TryLockError::WouldBlock) => {
                self.shared.counters.dropped.fetch_add(1, Ordering::Relaxed);
                Err(Reject::Busy)
            }
            Err(TryLockError::Poisoned(_)) => {
                self.shared.counters.dropped.fetch_add(1, Ordering::Relaxed);
                Err(Reject::BackendDown)
            }
        }
    }
}

impl RealtimeInputSink for ViceSockSink {
    /// Keyboard-only exhibit: a pointer record is REJECTED, never turned into
    /// some invented joyport motion. Logged once so the rejection is visible
    /// without a per-sample storm.
    fn try_pointer_abs(&self, _event: PointerAbs) -> Result<AcceptedSeq, Reject> {
        if !self.shared.warned_pointer.swap(true, Ordering::Relaxed) {
            eprintln!("[vicesock] pointer record on a keyboard-only station — rejected");
        }
        Err(Reject::Unsupported)
    }

    fn try_key(&self, event: KeyEvent) -> Result<AcceptedSeq, Reject> {
        let shifted = event.modifiers & SHIFT_MASK != 0;
        let mut p = self.lock_pending()?;
        // A release repeats the keysym its press went out with; only a PRESS
        // resolves the shift level. Resolved before any health check so an
        // unmapped scancode is rejected identically whether or not the backend
        // is up (and never folded onto a neighbouring key).
        let keysym = match event.down {
            true => self.shared.keymap.lookup(event.key, shifted),
            false => p
                .held
                .iter()
                .find(|(c, _)| *c == event.key)
                .map(|(_, k)| *k)
                .or_else(|| self.shared.keymap.lookup(event.key, shifted)),
        };
        let Some(keysym) = keysym else {
            self.shared
                .counters
                .unmapped
                .fetch_add(1, Ordering::Relaxed);
            eprintln!(
                "[vicesock] unmapped scancode 0x{:04x} down={}",
                event.key, event.down
            );
            return Err(Reject::Unsupported);
        };
        if self.health() != SinkHealth::Healthy {
            self.shared
                .counters
                .backend_down
                .fetch_add(1, Ordering::Relaxed);
            return Err(Reject::BackendDown);
        }
        if p.ordered.len() + 1 > ORDERED_CAPACITY {
            self.shared
                .counters
                .overflow
                .fetch_add(1, Ordering::Relaxed);
            self.shared.counters.dropped.fetch_add(1, Ordering::Relaxed);
            return Err(Reject::Overflow);
        }
        p.held.retain(|(c, _)| *c != event.key);
        if event.down {
            p.held.push((event.key, keysym));
        }
        p.ordered.push_back(Cmd::key(event.down, keysym));
        if trace_on() {
            eprintln!(
                "[vicesock-trace] rx seq={} code=0x{:04x} down={} shift={shifted} keysym={keysym}",
                event.seq, event.key, event.down
            );
        }
        self.shared
            .counters
            .accepted
            .fetch_add(1, Ordering::Relaxed);
        drop(p);
        self.shared.notify.notify_one();
        Ok(AcceptedSeq(event.seq))
    }

    fn health(&self) -> SinkHealth {
        match self.shared.health.load(Ordering::Acquire) {
            HEALTH_HEALTHY => SinkHealth::Healthy,
            HEALTH_DOWN => SinkHealth::Down,
            _ => SinkHealth::Starting,
        }
    }

    fn backend_name(&self) -> &'static str {
        "vicesock"
    }
}

impl Drop for ViceSockSink {
    fn drop(&mut self) {
        self.shared.closed.store(true, Ordering::Release);
        self.shared.notify.notify_waiters();
    }
}

/// One in-flight seq-stamped write awaiting its OK/ERR ack.
struct Sent {
    seq: u64,
    at: Instant,
    paced: bool,
    /// KEY verb: its ack closes a `[key-tel]` tx/ack pair (keyboard-lag chain).
    key: bool,
}

/// Deadline for the OLDEST unacked write; the paced allowance is recomputed from
/// the CURRENT outstanding set each loop iteration.
fn ack_deadline(outstanding: &VecDeque<Sent>) -> Option<Instant> {
    let oldest = outstanding.front()?;
    let paced = outstanding.iter().filter(|s| s.paced).count() as u32;
    Some(oldest.at + ACK_BASE + ACK_PER_PACED * paced)
}

/// Route one module line. `OK`/`ERR` retire their outstanding entry (the
/// measured receipt->ack RTT feeds telemetry); `DATA` rows (KEYDUMP) and `EV`
/// broadcasts are not acks.
fn on_reply(line: &str, outstanding: &mut VecDeque<Sent>) {
    let mut tok = line.splitn(3, ' ');
    let (Some(seq), Some(kind)) = (tok.next(), tok.next()) else {
        return;
    };
    let Ok(seq) = seq.parse::<u64>() else { return };
    if kind != "OK" && kind != "ERR" {
        return;
    }
    if let Some(i) = outstanding.iter().position(|s| s.seq == seq) {
        let sent = outstanding.remove(i).unwrap();
        let rtt_us = sent.at.elapsed().as_micros() as u64;
        if trace_on() {
            eprintln!("[vicesock-trace] ack {seq} rtt_us={rtt_us}");
        }
        if sent.key {
            // For a KEY this RTT is the module's whole pacing queue — the
            // number the visitor experiences as keyboard lag.
            crate::input_telemetry::key_ack("vicesock", seq, rtt_us);
        }
        crate::input_telemetry::record_inject("vicesock", 1, rtt_us, None);
    }
    // An ERR is an ack for liveness (the module processed the verb) but the verb
    // did not apply — a keysym the machine's .vkm does not name lands here.
    if kind == "ERR" {
        eprintln!("[vicesock] module replied {line}");
    }
}

async fn send_cmd(
    wr: &mut OwnedWriteHalf,
    seq: &mut u64,
    cmd: Cmd,
    outstanding: &mut VecDeque<Sent>,
) -> std::io::Result<()> {
    *seq += 1;
    wr.write_all(format!("{} {}\n", *seq, cmd.line).as_bytes())
        .await?;
    if trace_on() {
        eprintln!("[vicesock-trace] tx {} {}", *seq, cmd.line);
    }
    let key = cmd.line.starts_with("KEY ");
    if key {
        crate::input_telemetry::key_tx("vicesock", *seq, &cmd.line);
    }
    outstanding.push_back(Sent {
        seq: *seq,
        at: Instant::now(),
        paced: cmd.paced,
        key,
    });
    Ok(())
}

type ModuleLines = Lines<BufReader<OwnedReadHalf>>;

/// Connect and verify the module's banner. It must arrive within 1 s and name
/// `vicectl/1`; the optional `HELLO ` prefix is accepted so the banner reads the
/// same whichever of the two sibling modules is on the other end.
async fn connect_vicectl(path: &str) -> std::io::Result<(ModuleLines, OwnedWriteHalf)> {
    let stream = tokio::time::timeout(Duration::from_secs(1), UnixStream::connect(path))
        .await
        .map_err(|_| std::io::Error::new(std::io::ErrorKind::TimedOut, "connect timeout"))??;
    let (rd, wr) = stream.into_split();
    let mut lines = BufReader::new(rd).lines();
    let hello = tokio::time::timeout(Duration::from_secs(1), lines.next_line())
        .await
        .map_err(|_| std::io::Error::new(std::io::ErrorKind::TimedOut, "banner timeout"))??
        .ok_or_else(|| {
            std::io::Error::new(std::io::ErrorKind::UnexpectedEof, "EOF before banner")
        })?;
    if !banner_ok(&hello) {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("incompatible banner: {hello:?}"),
        ));
    }
    eprintln!("[vicesock] banner: {hello}");
    Ok((lines, wr))
}

fn banner_ok(line: &str) -> bool {
    let body = line.strip_prefix("HELLO ").unwrap_or(line);
    body == "vicectl/1" || body.starts_with("vicectl/1 ")
}

async fn vicesock_task(path: String, shared: Arc<Shared>) {
    let mut backoff_ms = 50u64;
    let mut seq = 0u64;
    while !shared.closed.load(Ordering::Acquire) {
        shared.health.store(HEALTH_STARTING, Ordering::Release);
        match connect_vicectl(&path).await {
            Ok((mut lines, mut wr)) => {
                eprintln!("[vicesock] connected, banner verified {path}");
                backoff_ms = 50;
                run_connection(&shared, &mut lines, &mut wr, &mut seq).await;
            }
            Err(e) => {
                eprintln!("[vicesock] connect/banner {path} failed: {e}; retry {backoff_ms}ms");
            }
        }
        shared.health.store(HEALTH_DOWN, Ordering::Release);
        {
            let mut p = shared.pending.lock().unwrap();
            p.ordered.clear();
            p.held.clear();
        }
        tokio::time::sleep(Duration::from_millis(backoff_ms)).await;
        backoff_ms = (backoff_ms * 2).min(1000);
    }
}

async fn run_connection(
    shared: &Shared,
    lines: &mut ModuleLines,
    wr: &mut OwnedWriteHalf,
    seq: &mut u64,
) {
    // Resync preamble: KEYCLEAR, and FORGET what was held. A key is never
    // re-pressed across a reconnect — these guests scan their own matrix and
    // generate their own auto-repeat from a held bit, so a re-pressed key whose
    // release was lost with the old connection would type forever.
    {
        let mut p = shared.pending.lock().unwrap();
        p.ordered.clear();
        p.held.clear();
    }
    shared.health.store(HEALTH_HEALTHY, Ordering::Release);

    let mut outstanding: VecDeque<Sent> = VecDeque::new();
    if let Err(e) = send_cmd(wr, seq, Cmd::keyclear(), &mut outstanding).await {
        eprintln!("[vicesock] resync write failed: {e}; reconnecting");
        return;
    }

    loop {
        loop {
            let next = {
                let mut p = shared.pending.lock().unwrap();
                p.ordered.pop_front()
            };
            let Some(cmd) = next else { break };
            if let Err(e) = send_cmd(wr, seq, cmd, &mut outstanding).await {
                eprintln!("[vicesock] write failed: {e}; reconnecting");
                return;
            }
        }
        if shared.closed.load(Ordering::Acquire) {
            return;
        }
        let deadline = ack_deadline(&outstanding);
        tokio::select! {
            _ = shared.notify.notified() => {}
            line = lines.next_line() => match line {
                Ok(Some(line)) => on_reply(&line, &mut outstanding),
                Ok(None) => {
                    eprintln!("[vicesock] module closed the socket; reconnecting");
                    return;
                }
                Err(e) => {
                    eprintln!("[vicesock] read failed: {e}; reconnecting");
                    return;
                }
            },
            _ = tokio::time::sleep_until(deadline.unwrap_or_else(Instant::now)),
                    if deadline.is_some() => {
                eprintln!(
                    "[vicesock] ack timeout ({} outstanding); reconnecting",
                    outstanding.len()
                );
                return;
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tokio::net::UnixListener;

    const BANNER: &[u8] = b"vicectl/1 machine=VIC20 rows=16 cols=8 keys=132\n";
    /// Shift_L, '2', 'a', Return — enough to prove substitution and passthrough.
    const MAP: &str = "0x002a\t0xffe1\t0xffe1\t# Shift_L\n\
                       0x0003\t0x0032\t0x0040\t# 2 at\n\
                       0x001e\t0x0061\t0x0041\t# a A\n\
                       0x001c\t0xff0d\t0xff0d\t# Return\n";

    fn key(seq: u64, code: u16, down: bool, modifiers: u16) -> KeyEvent {
        KeyEvent {
            seq,
            key: code,
            down,
            repeat: false,
            modifiers,
        }
    }

    fn write_map(dir: &std::path::Path, text: &str) -> Arc<ViceKeyMap> {
        let path = dir.join("us-layout.keysyms");
        std::fs::write(&path, text).unwrap();
        Arc::new(ViceKeyMap::load(path.to_str().unwrap()).unwrap())
    }

    /// Mock `vicectl` module: banner each connection, log every verb line (seq
    /// stripped) and ack it `<seq> OK`. `drop_after` drops the FIRST connection
    /// after acking that many lines (the reconnect fixture).
    fn spawn_module(
        listener: UnixListener,
        log: Arc<Mutex<Vec<String>>>,
        drop_after: Option<usize>,
    ) {
        tokio::spawn(async move {
            let mut first = true;
            loop {
                let Ok((mut stream, _)) = listener.accept().await else {
                    return;
                };
                let (rd, mut wr) = stream.split();
                if wr.write_all(BANNER).await.is_err() {
                    continue;
                }
                let mut lines = BufReader::new(rd).lines();
                let mut n = 0usize;
                while let Ok(Some(line)) = lines.next_line().await {
                    let Some((seq, verb)) = line.split_once(' ') else {
                        continue;
                    };
                    log.lock().unwrap().push(verb.to_string());
                    if wr
                        .write_all(format!("{seq} OK\n").as_bytes())
                        .await
                        .is_err()
                    {
                        break;
                    }
                    n += 1;
                    if first && drop_after == Some(n) {
                        break;
                    }
                }
                first = false;
            }
        });
    }

    async fn wait_until(what: &str, mut cond: impl FnMut() -> bool) {
        for _ in 0..2500 {
            if cond() {
                return;
            }
            tokio::time::sleep(Duration::from_millis(2)).await;
        }
        panic!("timeout waiting for {what}");
    }

    fn bind(tag: &str) -> (std::path::PathBuf, UnixListener) {
        let dir = std::env::temp_dir().join(format!("vicesock-{tag}-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let sock = dir.join("ctl.sock");
        let _ = std::fs::remove_file(&sock);
        let listener = UnixListener::bind(&sock).unwrap();
        (dir, listener)
    }

    /// The wire contract: a KEYCLEAR preamble, then one `KEY <0|1> <keysym>` per
    /// edge — with the SHIFT LEVEL SUBSTITUTED (Shift+2 is keysym `at`, 0x40 =
    /// 64, not `2` plus a shift the guest would have to resolve), Shift_L still
    /// forwarded as itself, and the release repeating the pressed keysym even
    /// though Shift was let go first.
    #[tokio::test]
    async fn substitutes_the_shift_level_and_releases_what_it_pressed() {
        let (dir, listener) = bind("wire");
        let log: Arc<Mutex<Vec<String>>> = Arc::default();
        spawn_module(listener, log.clone(), None);
        let map = write_map(&dir, MAP);

        let sink = ViceSockSink::new(dir.join("ctl.sock").to_str().unwrap().to_string(), map);
        wait_until("healthy after banner", || {
            sink.health() == SinkHealth::Healthy
        })
        .await;
        wait_until("KEYCLEAR preamble", || !log.lock().unwrap().is_empty()).await;

        // Shift+2 -> '"' on a C64 (keysym `at` on the host layout), with the
        // visitor releasing Shift BEFORE the digit.
        sink.try_key(key(1, 0x2a, true, 0b01)).unwrap();
        sink.try_key(key(2, 0x03, true, 0b01)).unwrap();
        sink.try_key(key(3, 0x2a, false, 0b00)).unwrap();
        sink.try_key(key(4, 0x03, false, 0b00)).unwrap();
        // A plain letter, then Return.
        sink.try_key(key(5, 0x1e, true, 0)).unwrap();
        sink.try_key(key(6, 0x1e, false, 0)).unwrap();
        sink.try_key(key(7, 0x1c, true, 0)).unwrap();
        sink.try_key(key(8, 0x1c, false, 0)).unwrap();
        wait_until("all edges on the wire", || log.lock().unwrap().len() >= 9).await;

        assert_eq!(
            log.lock().unwrap().clone(),
            vec![
                "KEYCLEAR",
                "KEY 1 65505", // Shift_L 0xffe1, forwarded as itself
                "KEY 1 64",    // '@' — the SHIFTED keysym for scancode 0x03
                "KEY 0 65505",
                "KEY 0 64", // ...and the release repeats it, Shift long gone
                "KEY 1 97", // 'a'
                "KEY 0 97",
                "KEY 1 65293", // Return
                "KEY 0 65293",
            ]
        );
        // A scancode the table does not carry is rejected, never folded onto a
        // neighbour.
        assert_eq!(
            sink.try_key(key(99, 0xe011, true, 0)),
            Err(Reject::Unsupported)
        );
        // Keyboard-only: pointer records are refused.
        assert_eq!(
            sink.try_pointer_abs(PointerAbs {
                seq: 100,
                x: 10,
                y: 10,
                width: 768,
                height: 544,
                buttons: 0,
                wheel_v: 0,
                wheel_h: 0,
                ordered: false,
            }),
            Err(Reject::Unsupported)
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// The module drops the connection: the sink goes Down, REJECTS offers while
    /// down rather than queueing them, reconnects, and re-preambles with a
    /// KEYCLEAR — never re-pressing a key that was held at the drop.
    #[tokio::test]
    async fn reconnect_clears_and_never_replays_a_held_key() {
        let (dir, listener) = bind("reconn");
        let log: Arc<Mutex<Vec<String>>> = Arc::default();
        spawn_module(listener, log.clone(), Some(2)); // KEYCLEAR + one KEY
        let map = write_map(&dir, MAP);

        let sink = ViceSockSink::new(dir.join("ctl.sock").to_str().unwrap().to_string(), map);
        wait_until("healthy", || sink.health() == SinkHealth::Healthy).await;
        sink.try_key(key(1, 0x1e, true, 0)).unwrap(); // 'a' pressed and HELD
        wait_until("first key on the wire", || log.lock().unwrap().len() >= 2).await;
        wait_until("down after drop", || sink.health() == SinkHealth::Down).await;
        assert_eq!(
            sink.try_key(key(2, 0x1c, true, 0)),
            Err(Reject::BackendDown)
        );
        wait_until("reconnect preamble", || log.lock().unwrap().len() >= 3).await;
        wait_until("healthy again", || sink.health() == SinkHealth::Healthy).await;
        sink.try_key(key(3, 0x1c, true, 0)).unwrap();
        wait_until("post-reconnect key", || log.lock().unwrap().len() >= 4).await;

        assert_eq!(
            log.lock().unwrap().clone(),
            vec!["KEYCLEAR", "KEY 1 97", "KEYCLEAR", "KEY 1 65293"]
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// Only a `vicectl/1` peer is spoken to, with or without the HELLO prefix.
    #[test]
    fn banner_must_name_vicectl_1() {
        assert!(banner_ok("vicectl/1 machine=C64SC rows=16 cols=8 keys=129"));
        assert!(banner_ok("HELLO vicectl/1 machine=VIC20"));
        assert!(banner_ok("vicectl/1"));
        assert!(!banner_ok("HELLO mamectl/1 test indy_4610"));
        assert!(!banner_ok("vicectl/2 machine=C64SC"));
        assert!(!banner_ok("vicectl/10"));
    }

    /// The paced allowance extends the oldest write's deadline per outstanding
    /// KEY; a lone KEYCLEAR carries the base only.
    #[test]
    fn ack_deadline_extends_per_paced_outstanding() {
        let at = Instant::now();
        let mut q = VecDeque::new();
        assert!(ack_deadline(&q).is_none());
        q.push_back(Sent {
            seq: 1,
            at,
            paced: false,
            key: false,
        });
        assert_eq!(ack_deadline(&q), Some(at + ACK_BASE));
        for seq in 2..=4 {
            q.push_back(Sent {
                seq,
                at,
                paced: true,
                key: false,
            });
        }
        assert_eq!(ack_deadline(&q), Some(at + ACK_BASE + ACK_PER_PACED * 3));
    }
}
