//! The ONE shared host-layout table every VICE station's input sink resolves
//! keys through — `SH_VICESOCK_KEYMAP`, loaded here, consumed by `vice_sock`.
//!
//! MAME needed a keymap PER STATION because its `KEY` verb names a matrix cell.
//! VICE's `vicectl` `KEY` verb carries an X11 KEYSYM and VICE resolves it
//! through the machine's own `.vkm` keymap, so nothing here is per-station: this
//! table describes the HOST keyboard (US layout), which is what the bridged
//! kiosks' X server applied before VICE ever saw a key. Generated by
//! `scripts/dev/vice-keymap.py` from the SPA's own scancode vocabulary; never
//! hand-edited. See `docs/lab/research/vice-daemon-plane.md`.

use std::sync::Arc;

/// `SH_VICESOCK_KEYMAP`: the ONE shared host-layout table, generated by
/// `scripts/dev/vice-keymap.py` and never hand-edited. One row per key:
/// `scancode-hex<TAB>plain-keysym-hex<TAB>shifted-keysym-hex`, with an optional
/// trailing `#` comment column carrying the human legend. Blank lines and
/// whole-line `#` comments are ignored.
pub(crate) struct ViceKeyMap {
    entries: Vec<(u16, u32, u32)>,
}

impl ViceKeyMap {
    /// Fail CLOSED and LOUD in both directions: a missing declaration and a
    /// broken file both yield an EMPTY map that rejects every key. There is no
    /// compiled-in fallback on purpose — a keysym table silently substituted for
    /// the deployed one is exactly the class of failure this pipeline ends.
    pub(crate) fn from_env() -> Arc<ViceKeyMap> {
        let Some(path) = std::env::var("SH_VICESOCK_KEYMAP")
            .ok()
            .filter(|p| !p.trim().is_empty())
        else {
            eprintln!(
                "[input-router] SH_VICESOCK_KEYMAP unset — keyboard DISABLED \
                 (deploy stations/vice-native/us-layout.keysyms and name it)"
            );
            return Arc::new(ViceKeyMap {
                entries: Vec::new(),
            });
        };
        match Self::load(&path) {
            Ok(map) => {
                eprintln!(
                    "[input-router] vice keymap: {} keys from {path}",
                    map.entries.len()
                );
                Arc::new(map)
            }
            Err(e) => {
                eprintln!(
                    "[input-router] SH_VICESOCK_KEYMAP {path}: {e} — keyboard DISABLED \
                     (fail-closed; regenerate with scripts/dev/vice-keymap.py)"
                );
                Arc::new(ViceKeyMap {
                    entries: Vec::new(),
                })
            }
        }
    }

    pub(crate) fn load(path: &str) -> Result<ViceKeyMap, String> {
        let text = std::fs::read_to_string(path).map_err(|e| e.to_string())?;
        let mut entries: Vec<(u16, u32, u32)> = Vec::new();
        for (n, raw) in text.lines().enumerate() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let mut it = line.split('\t');
            let (Some(code), Some(plain), Some(shifted)) = (it.next(), it.next(), it.next()) else {
                return Err(format!(
                    "line {}: want scancode<TAB>plain<TAB>shifted",
                    n + 1
                ));
            };
            // Anything after the third column must be a comment, never a
            // fourth field silently ignored.
            if let Some(tail) = it.next() {
                if !tail.trim_start().starts_with('#') {
                    return Err(format!("line {}: unexpected 4th column {tail:?}", n + 1));
                }
            }
            let code = parse_hex(code)
                .and_then(|v| u16::try_from(v).ok())
                .ok_or_else(|| format!("line {}: bad scancode {code:?}", n + 1))?;
            let plain = parse_hex(plain)
                .ok_or_else(|| format!("line {}: bad plain keysym {plain:?}", n + 1))?;
            let shifted = parse_hex(shifted)
                .ok_or_else(|| format!("line {}: bad shifted keysym {shifted:?}", n + 1))?;
            if plain == 0 || shifted == 0 {
                return Err(format!("line {}: keysym 0 is not a key", n + 1));
            }
            if entries.iter().any(|(c, _, _)| *c == code) {
                return Err(format!("line {}: duplicate scancode {code:#x}", n + 1));
            }
            entries.push((code, plain, shifted));
        }
        if entries.is_empty() {
            return Err("no entries".into());
        }
        Ok(ViceKeyMap { entries })
    }

    /// The keysym for one scancode at one shift level.
    pub(crate) fn lookup(&self, code: u16, shifted: bool) -> Option<u32> {
        self.entries
            .iter()
            .find(|(c, _, _)| *c == code)
            .map(|(_, p, s)| if shifted { *s } else { *p })
    }
}

fn parse_hex(tok: &str) -> Option<u32> {
    let t = tok.trim();
    u32::from_str_radix(t.strip_prefix("0x").or_else(|| t.strip_prefix("0X"))?, 16).ok()
}

#[cfg(test)]
mod tests {
    use super::ViceKeyMap;

    /// Shift_L, '2', 'a', Return — the same four rows the sink's wire test uses.
    const MAP: &str = "0x002a\t0xffe1\t0xffe1\t# Shift_L\n\
                       0x0003\t0x0032\t0x0040\t# 2 at\n\
                       0x001e\t0x0061\t0x0041\t# a A\n\
                       0x001c\t0xff0d\t0xff0d\t# Return\n";

    /// The table loads, resolves both shift levels, and REFUSES malformed input
    /// — a broken declared keymap must never degrade to some compiled-in guess.
    #[test]
    fn keymap_loads_and_fails_closed() {
        let dir = std::env::temp_dir().join(format!("vicemap-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("k");
        let p = path.to_str().unwrap();

        std::fs::write(&path, MAP).unwrap();
        let map = ViceKeyMap::load(p).unwrap();
        assert_eq!(map.lookup(0x03, false), Some(0x32));
        assert_eq!(map.lookup(0x03, true), Some(0x40));
        assert_eq!(map.lookup(0x2a, true), Some(0xffe1));
        assert_eq!(map.lookup(0x99, false), None);

        for bad in [
            "0x1e\t0x61\t0x41\n0x1e\t0x62\t0x42\n", // duplicate scancode
            "0x1e 0x61 0x41\n",                     // spaces, not tabs
            "zz\t0x61\t0x41\n",                     // unparsable scancode
            "0x1e\t61\t0x41\n",                     // keysym without 0x
            "0x1e\t0x00\t0x41\n",                   // keysym 0 is not a key
            "0x1e\t0x61\t0x41\tQ\n",                // 4th column that is not a comment
            "# only comments\n",                    // no entries at all
        ] {
            std::fs::write(&path, bad).unwrap();
            assert!(ViceKeyMap::load(p).is_err(), "must refuse: {bad:?}");
        }
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// The SHIPPED table is the contract with the SPA's scancode vocabulary and
    /// with `scripts/dev/vice-keymap.py`: it must load, and the keys a visitor
    /// actually types must resolve to the US-layout keysyms VICE's symbolic
    /// `.vkm` expects.
    #[test]
    fn shipped_us_layout_table_loads_and_resolves() {
        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../stations/vice-native/us-layout.keysyms"
        );
        let map = ViceKeyMap::load(path).expect("generated table must load");
        assert_eq!(map.entries.len(), 103);
        assert_eq!(map.lookup(0x1e, false), Some(0x61)); // a
        assert_eq!(map.lookup(0x1e, true), Some(0x41)); // A
        assert_eq!(map.lookup(0x03, true), Some(0x40)); // Shift+2 -> at
        assert_eq!(map.lookup(0x1c, false), Some(0xff0d)); // Return
        assert_eq!(map.lookup(0xe048, false), Some(0xff52)); // Up
        assert_eq!(map.lookup(0x2a, false), Some(0xffe1)); // Shift_L as itself
    }
}
