// ESLint flat config for spa/ — the Vite + React + TypeScript museum app.
//
// One heavily-commented flat config, no Prettier, and the npm script runs
// with --max-warnings=0 so any warning fails the gate. This app is
// TypeScript, so the stack is typescript-eslint's recommended set (syntactic only — the
// type-AWARE rules need a project service and slow the lint down; `tsc -b`
// already runs as part of `npm run build` and is the type gate) plus the two
// React plugins that matter for a Vite app:
//   - react-hooks:    rules-of-hooks is non-negotiable correctness.
//   - react-refresh:  keeps every exported symbol HMR-compatible.
//
// Scope: spa/ ONLY. scripts/ and tests/e2e-live/ at the repo root have their
// own tooling — do not widen this config beyond the app.

import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';

// Rules applied to all app code, layered on the recommended sets.
const commonRules = {
  eqeqeq: ['error', 'always', { null: 'ignore' }],
  'no-var': 'error',
  'prefer-const': ['error', { destructuring: 'all' }],
  'no-undef-init': 'error',
  'no-useless-concat': 'error',
  'no-useless-rename': 'error',
  'no-throw-literal': 'error',
  'no-return-await': 'error',
  'no-self-compare': 'error',
  'no-implicit-globals': 'error',
  'no-unneeded-ternary': 'error',
  'dot-notation': 'error',
  // Only enforce shorthand for properties ({ foo } instead of { foo: foo });
  // method-shorthand rewrites can change constructability semantics.
  'object-shorthand': ['error', 'properties'],
  // console.* is the app's diagnostics channel (stream negotiation, transport
  // fallback decisions) — deliberately allowed.
  'no-console': 'off',
  // Empty catch is a deliberate pattern for optional browser APIs
  // (clipboard, fullscreen, vibrate) — allowed, but only for catch.
  'no-empty': ['error', { allowEmptyCatch: true }],
  // `warn` keeps the editor squiggle yellow rather than red for in-progress
  // identifiers, but `npm run lint` runs with --max-warnings=0 so CI still
  // fails on any survivor. Prefix intentionally-unused args with `_`.
  '@typescript-eslint/no-unused-vars': [
    'warn',
    {
      args: 'after-used',
      argsIgnorePattern: '^_',
      varsIgnorePattern: '^_',
      caughtErrors: 'none',
      ignoreRestSiblings: true,
    },
  ],
};

export default tseslint.config(
  {
    // Global ignores — build output, deps, the gitignored real-credentials
    // file (lint the tracked example instead; the real file may not exist),
    // any vendored third-party sources, and the two registry-GENERATED files
    // (museumCatalog.ts, archetypeRegistry.ts — regenerated by the tiles
    // registry codegen, so the gate must never fight their output).
    ignores: [
      'dist/**',
      'coverage/**',
      'node_modules/**',
      '.venv-assets/**',
      'src/data/credentials.ts',
      'src/data/museumCatalog.ts',
      'src/data/posters.ts',
      'src/three/archetypeRegistry.ts',
      'src/data/catalog.ts',
      '**/vendor/**',
    ],
  },

  // App source — TS/TSX in the browser.
  {
    files: ['src/**/*.{ts,tsx}'],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
      reactRefresh.configs.vite,
    ],
    plugins: {
      // react-hooks v7's recommended configs bundle the React-Compiler
      // diagnostics (set-state-in-effect, purity, preserve-manual-memoization,
      // …) which flag ~40 spots in the streaming UI and can only be satisfied
      // by semantic rewrites of live, hand-tuned code. We deliberately take
      // just the two classic correctness rules; adopt the compiler set in a
      // dedicated change if ever worth it.
      'react-hooks': reactHooks,
    },
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: {
        ...globals.browser,
      },
    },
    rules: {
      ...commonRules,
      'react-hooks/rules-of-hooks': 'error',
      // warn still fails `npm run lint` (--max-warnings=0); it only keeps the
      // editor squiggle yellow.
      'react-hooks/exhaustive-deps': 'warn',
      // The three/ scene modules and the stream clients intentionally use
      // `any` at WebCodecs/WebTransport/vendor boundaries where lib.dom
      // typings lag the shipping browser APIs. Keep it visible as a warning?
      // No — a warning IS a failure under --max-warnings=0, and blanket
      // `any`-hunting in the 3D/codec glue is churn without payoff. Off.
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  // Node-runtime TS config files (Vite/Vitest configure themselves via a Node
  // process, never a browser — separate from the src/ browser block above so
  // `globals.browser` doesn't leak into files that actually run under Node).
  {
    files: ['vite.config.ts', 'vitest.config.ts'],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: {
        ...globals.node,
      },
    },
    rules: {
      ...commonRules,
    },
  },

  // Node ESM helper scripts (the ensure-credentials prebuild shim).
  {
    files: ['scripts/**/*.mjs'],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: {
        ...globals.node,
      },
    },
    rules: {
      ...commonRules,
      // Plain JS here — the TS-namespaced rule doesn't apply.
      '@typescript-eslint/no-unused-vars': 'off',
      'no-unused-vars': [
        'warn',
        { args: 'after-used', argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
);
