// DO NOT EDIT — generated by scripts/tiles-registry.py generate from
// registry/tiles/*.json + registry/registry-v1.json; run `make tile-registry-generate`.
import type { VMManifestEntry } from '../types';

// Curated museum metadata keyed by VM id. If the runtime manifest omits placard
// fields (accent/era/software/etc), we enrich from here so placards stay rich
// even against a minimal manifest. Purely additive — never overrides real data.
const CATALOG: Record<string, Partial<VMManifestEntry>> = {
  kolibrios: {
    accent: '#39c6d6',
    era: '2000s',
    eraSoftware: ['KolibriOS desktop', 'TinyBasic', 'Fasm IDE', 'Animage paint'],
    periodBrowser: 'WebView (HTMLv)',
    iconicApps: ['Fara (dungeon crawler)', 'MineSweeper', '3D Cube demo'],
    blurb: 'A complete graphical OS that fits on a single floppy — written in pure asm.',
  },
  toaruos: {
    accent: '#c98b3a',
    era: '2010s',
    eraSoftware: ['Yutani compositor', 'Bim editor', 'Kuroko shell', 'Terminal'],
    periodBrowser: 'no period browser (demo apps)',
    iconicApps: ['Julia fractal viewer', 'Bomberman-style demo', 'Clock widget'],
    blurb: "One developer's from-scratch UNIX with a real windowing compositor.",
  },
  freedos: {
    accent: '#5fa85f',
    era: '1990s',
    eraSoftware: ['EDIT', 'FDISK', '4DOS', 'Arachne browser'],
    periodBrowser: 'Arachne / Lynx (DOS)',
    iconicApps: ['Rogue', 'Nibbles', 'DOOM (shareware)'],
    blurb: "The DOS command prompt that never died — C:\\> is still alive and well.",
  },
};

// Fallback accent palette (deterministic per-id) if nothing else is known.
const FALLBACK_ACCENTS = ['#39c6d6', '#c98b3a', '#5fa85f', '#c95a6b', '#8a7fd6', '#d6b23a'];

function fallbackAccent(id: string): string {
  let h = 0;
  for (let i = 0; i < id.length; i++) h = (h * 31 + id.charCodeAt(i)) >>> 0;
  return FALLBACK_ACCENTS[h % FALLBACK_ACCENTS.length];
}

function eraFromYear(year: number | string): string {
  const y = typeof year === 'number' ? year : parseInt(String(year), 10);
  if (!Number.isFinite(y)) return 'unknown';
  return `${Math.floor(y / 10) * 10}s`;
}

// Merge a raw manifest entry with curated + derived metadata.
export function enrich(entry: VMManifestEntry): Required<
  Pick<VMManifestEntry, 'accent' | 'era' | 'eraSoftware' | 'periodBrowser' | 'iconicApps' | 'blurb'>
> & VMManifestEntry {
  const cat = CATALOG[entry.id] ?? {};
  return {
    ...entry,
    accent: entry.accent ?? cat.accent ?? fallbackAccent(entry.id),
    era: entry.era ?? cat.era ?? eraFromYear(entry.year),
    eraSoftware: entry.eraSoftware ?? cat.eraSoftware ?? [],
    periodBrowser: entry.periodBrowser ?? cat.periodBrowser ?? '—',
    iconicApps: entry.iconicApps ?? cat.iconicApps ?? [],
    blurb: entry.blurb ?? cat.blurb ?? entry.notes ?? '',
  };
}

export type EnrichedVM = ReturnType<typeof enrich>;
