// DO NOT EDIT — generated by scripts/tiles-registry.py generate from
// registry/tiles/*.json (demoProgram); run `make tile-registry-generate`.
import type { DemoProgram } from '../types';

const DEMO_PROGRAMS = {
  "amstradcpc": {
    "label": "Type in a demo program",
    "lines": [
      "10 mode 1",
      "16 ink 3,6",
      "17 border 1",
      "20 clg",
      "30 b%=rnd*5+1",
      "40 c%=rnd*5+1",
      "50 origin 320,200",
      "60 for a=0 to 1000 step pi/30",
      "70 x%=100*cos(a)",
      "80 move x%,x%",
      "90 draw 200*cos(a/b%),200*sin(a/c%),3",
      "91 if inkey$<>\"\" then 20",
      "100 next",
      "110 goto 20"
    ],
    "runCommand": "run"
  },
  "mpf2": {
    "label": "Type in a demo program",
    "lines": [
      "10 hgr",
      "20 hcolor=3",
      "30 for x=0 to 279 step 7",
      "40 hplot x,0 to 279-x,159",
      "50 next",
      "60 for y=0 to 159 step 5",
      "70 hplot 0,y to 279,159-y",
      "80 next",
      "90 hcolor=int(rnd(1)*8)",
      "100 goto 30"
    ],
    "runCommand": "run"
  }
} as const satisfies Record<string, DemoProgram>;

export function demoProgramFor(osId: string): DemoProgram | undefined {
  return DEMO_PROGRAMS[osId as keyof typeof DEMO_PROGRAMS];
}
