// DO NOT EDIT — generated by scripts/stations-registry.py generate from
// registry/tiles/*.json (demoProgram); run `make station-registry-generate`.
import type { DemoProgram } from '../types';

const DEMO_PROGRAMS = {
  "amstradcpc": {
    "label": "Type in a demo program",
    "lines": [
      "10 mode 1",
      "16 ink 3,6",
      "17 border 1",
      "20 clg",
      "30 b%=rnd*5+1",
      "40 c%=rnd*5+1",
      "50 origin 320,200",
      "60 for a=0 to 1000 step pi/30",
      "70 x%=100*cos(a)",
      "80 move x%,x%",
      "90 draw 200*cos(a/b%),200*sin(a/c%),3",
      "91 if inkey$<>\"\" then 20",
      "100 next",
      "110 goto 20"
    ],
    "runCommand": "run",
    "perCharMs": 90
  },
  "armeval": {
    "label": "Time 20000 loops on a 1986 ARM",
    "lines": [
      "10 T%=TIME",
      "20 FOR I%=1 TO 20000:NEXT",
      "30 PRINT\"20000 LOOPS \";(TIME-T%)/100"
    ],
    "runCommand": "RUN",
    "perCharMs": 160
  },
  "bbcmicro": {
    "label": "Type in a demo program",
    "lines": [
      "10 mode 1",
      "20 for i=0 to 1279 step 16",
      "30 gcol 0,1+i mod 3",
      "40 move 640,512:draw i,1023",
      "50 next"
    ],
    "runCommand": "run",
    "perCharMs": 170
  },
  "cbm8032": {
    "label": "Type in a demo program",
    "lines": [
      "10 print chr$(147)",
      "20 for r=1 to 12",
      "30 for c=1 to 8",
      "40 print tab((c-1)*10);r*c;",
      "50 next c:print:next r"
    ],
    "runCommand": "run",
    "perCharMs": 170
  },
  "dragon32": {
    "label": "Type in a demo program",
    "lines": [
      "10 pmode 3,1",
      "20 pcls",
      "30 screen 1,0",
      "40 for r=2 to 90 step 4",
      "50 circle(128,96),r,rnd(4)",
      "60 next r",
      "70 goto 40"
    ],
    "runCommand": "run",
    "perCharMs": 170
  },
  "mpf2": {
    "label": "Type in a demo program",
    "lines": [
      "10 hgr",
      "20 hcolor=3",
      "30 for x=0 to 279 step 7",
      "40 hplot x,0 to 279-x,159",
      "50 next",
      "60 for y=0 to 159 step 5",
      "70 hplot 0,y to 279,159-y",
      "80 next",
      "90 hcolor=int(rnd(1)*8)",
      "100 goto 30"
    ],
    "runCommand": "run"
  },
  "oricatmos": {
    "label": "Type in a demo program",
    "lines": [
      "10 cls",
      "20 for c=0 to 6",
      "30 paper c:ink 7-c",
      "40 print \"oric atmos 1984\"",
      "50 ping:wait 40",
      "60 next c",
      "70 paper 7:ink 0"
    ],
    "runCommand": "run",
    "perCharMs": 160
  },
  "pet2001": {
    "label": "Type in a demo program",
    "lines": [
      "10 print chr$(147)",
      "20 x=int(rnd(1)*1000)",
      "30 poke 32768+x,81",
      "40 goto 20"
    ],
    "runCommand": "run",
    "perCharMs": 180
  },
  "vic20": {
    "label": "Type in a demo program",
    "lines": [
      "10 print chr$(147)",
      "20 x=int(rnd(1)*506)",
      "30 poke 7680+x,81",
      "40 poke 38400+x,int(rnd(1)*8)",
      "50 goto 20"
    ],
    "runCommand": "run",
    "perCharMs": 170
  },
  "zxspectrum": {
    "label": "Type in a demo program (one key = one keyword)",
    "lines": [
      "10 b1",
      "20 b2",
      "30 b6",
      "40 b5",
      "50 g10"
    ],
    "runCommand": "r",
    "perCharMs": 400
  }
} as const satisfies Record<string, DemoProgram>;

export function demoProgramFor(osId: string): DemoProgram | undefined {
  return DEMO_PROGRAMS[osId as keyof typeof DEMO_PROGRAMS];
}
