// DO NOT EDIT — generated by scripts/stations-registry.py generate from
// registry/stations/*.json (keyboard); run `make station-registry-generate`.
import type { GuestKeyboard } from '../types';

const KEYBOARDS = {
  "armeval": {
    "charMap": {
      "\"": "@",
      "'": "&",
      "&": "^",
      "(": "*",
      ")": "(",
      "=": "_",
      "@": "\\",
      "+": ":",
      "^": "=",
      "~": "+",
      "_": "`",
      ":": "'",
      "*": "\""
    }
  },
  "bbcmicro": {
    "charMap": {
      "\"": "@",
      "'": "&",
      "&": "^",
      "(": "*",
      ")": "(",
      "=": "_",
      "@": "\\",
      "+": ":",
      "^": "=",
      "~": "+",
      "_": "`",
      ":": "'",
      "*": "\""
    }
  },
  "dragon32": {
    "charMap": {
      "@": "[",
      "\"": "@",
      "&": "^",
      "'": "&",
      "(": "*",
      ")": "(",
      ":": "-",
      "*": "_",
      "+": ":",
      "-": "=",
      "=": "+"
    },
    "letterCase": "upper-only"
  },
  "kc854": {
    "charMap": {
      "W": "w",
      "w": "W",
      "A": "a",
      "a": "A",
      "\"": "@",
      "-": "=",
      "=": "+",
      "Y": "y",
      "y": "Y",
      "E": "e",
      "e": "E",
      "S": "s",
      "s": "S",
      "^": "[",
      ":": "-",
      "*": "_",
      "X": "x",
      "x": "X",
      "T": "t",
      "t": "T",
      "F": "f",
      "f": "F",
      "P": "p",
      "p": "P",
      "@": ")",
      "V": "v",
      "v": "V",
      "U": "u",
      "u": "U",
      "H": "h",
      "h": "H",
      "'": "&",
      "O": "o",
      "o": "O",
      ")": "(",
      "N": "n",
      "n": "N",
      "I": "i",
      "i": "I",
      "J": "j",
      "j": "J",
      "(": "*",
      "K": "k",
      "k": "K",
      "M": "m",
      "m": "M",
      "Z": "z",
      "z": "Z",
      "G": "g",
      "g": "G",
      "&": "^",
      "L": "l",
      "l": "L",
      "B": "b",
      "b": "B",
      "R": "r",
      "r": "R",
      "D": "d",
      "d": "D",
      "|": "\"",
      "+": ";",
      ";": ":",
      "C": "c",
      "c": "C",
      "Q": "q",
      "q": "Q"
    }
  },
  "mpf2": {
    "charMap": {
      "=": "O",
      "-": "I",
      "+": "P",
      "(": "*",
      ")": "(",
      "*": ")"
    },
    "letterCase": "upper-only"
  },
  "pet2001": {
    "letterCase": "upper-only"
  },
  "vic20": {
    "letterCase": "upper-only"
  },
  "zxspectrum": {
    "letterCase": "upper-only"
  }
} as const satisfies Record<string, GuestKeyboard>;

export function keyboardFor(osId: string): GuestKeyboard | undefined {
  return KEYBOARDS[osId as keyof typeof KEYBOARDS];
}
