// DO NOT EDIT — generated by scripts/tiles-registry.py generate from
// registry/tiles/*.json (keyboard); run `make tile-registry-generate`.
import type { GuestKeyboard } from '../types';

const KEYBOARDS = {
  "dragon32": {
    "charMap": {
      "@": "[",
      "\"": "@",
      "&": "^",
      "'": "&",
      "(": "*",
      ")": "(",
      ":": "-",
      "*": "_",
      "+": ":",
      "-": "=",
      "=": "+"
    },
    "letterCase": "upper-only"
  },
  "mpf2": {
    "charMap": {
      "=": "O",
      "-": "I",
      "+": "P",
      "(": "*",
      ")": "(",
      "*": ")"
    },
    "letterCase": "upper-only"
  },
  "pet2001": {
    "letterCase": "upper-only"
  },
  "vic20": {
    "letterCase": "upper-only"
  }
} as const satisfies Record<string, GuestKeyboard>;

export function keyboardFor(osId: string): GuestKeyboard | undefined {
  return KEYBOARDS[osId as keyof typeof KEYBOARDS];
}
