// DO NOT EDIT — generated by scripts/stations-registry.py generate from
// registry/stations/*.json (keyboard); run `make station-registry-generate`.
import type { GuestKeyboard } from '../types';

const KEYBOARDS = {
  "amstradcpc": {
    "charMap": {
      "&": "^",
      "\"": "@",
      "'": "&",
      "(": "*",
      ")": "(",
      "_": ")",
      "=": "_",
      "^": "=",
      "@": "[",
      "|": "{",
      "[": "]",
      "{": "}",
      "]": "\\",
      "}": "|",
      ":": ";",
      "*": ":",
      ";": "'",
      "+": "\"",
      "\\": "`",
      "`": "~"
    },
    "physical": true
  },
  "armeval": {
    "charMap": {
      "\"": "@",
      "'": "&",
      "&": "^",
      "(": "*",
      ")": "(",
      "=": "_",
      "@": "\\",
      "+": ":",
      "^": "=",
      "~": "+",
      "_": "`",
      ":": "'",
      "*": "\""
    },
    "physical": true
  },
  "atari800xl": {
    "charMap": {
      "\"": "@",
      "'": "&",
      "&": "^",
      "@": "*",
      "<": "-",
      ">": "=",
      "-": "[",
      "_": "{",
      "=": "]",
      "|": "}",
      "+": "'",
      "\\": "\"",
      "*": "\\",
      "^": "|",
      "[": "<",
      "]": ">"
    },
    "physical": true
  },
  "bbcmicro": {
    "charMap": {
      "\"": "@",
      "'": "&",
      "&": "^",
      "(": "*",
      ")": "(",
      "=": "_",
      "@": "\\",
      "+": ":",
      "^": "=",
      "~": "+",
      "_": "`",
      ":": "'",
      "*": "\""
    },
    "physical": true
  },
  "c64basic": {
    "letterCase": "upper-only"
  },
  "cpm22": {
    "charMap": {
      "y": "z",
      "z": "y",
      "Y": "Z",
      "Z": "Y",
      "\"": "@",
      "&": "^",
      "/": "&",
      "(": "*",
      ")": "(",
      "=": ")",
      "?": "_",
      "+": "]",
      "*": "}",
      ";": "<",
      ":": ">",
      "-": "/",
      "_": "?",
      "'": "\\",
      "~": "|"
    },
    "physical": true
  },
  "dragon32": {
    "charMap": {
      "@": "[",
      "\"": "@",
      "&": "^",
      "'": "&",
      "(": "*",
      ")": "(",
      ":": "-",
      "*": "_",
      "+": ":",
      "-": "=",
      "=": "+"
    },
    "letterCase": "upper-only",
    "physical": true
  },
  "fmtowns": {
    "charMap": {
      "\"": "@",
      "&": "^",
      "'": "&",
      "(": "*",
      ")": "(",
      "=": "_",
      "^": "=",
      "~": "+",
      "@": "[",
      "`": "{",
      "[": "]",
      "{": "}",
      "]": "`",
      "}": "~",
      "+": ":",
      "*": "\"",
      ":": "'"
    },
    "physical": true
  },
  "kc854": {
    "charMap": {
      "W": "w",
      "w": "W",
      "A": "a",
      "a": "A",
      "\"": "@",
      "-": "=",
      "=": "+",
      "Y": "y",
      "y": "Y",
      "E": "e",
      "e": "E",
      "S": "s",
      "s": "S",
      "^": "[",
      ":": "-",
      "*": "_",
      "X": "x",
      "x": "X",
      "T": "t",
      "t": "T",
      "F": "f",
      "f": "F",
      "P": "p",
      "p": "P",
      "@": ")",
      "V": "v",
      "v": "V",
      "U": "u",
      "u": "U",
      "H": "h",
      "h": "H",
      "'": "&",
      "O": "o",
      "o": "O",
      ")": "(",
      "N": "n",
      "n": "N",
      "I": "i",
      "i": "I",
      "J": "j",
      "j": "J",
      "(": "*",
      "K": "k",
      "k": "K",
      "M": "m",
      "m": "M",
      "Z": "z",
      "z": "Z",
      "G": "g",
      "g": "G",
      "&": "^",
      "L": "l",
      "l": "L",
      "B": "b",
      "b": "B",
      "R": "r",
      "r": "R",
      "D": "d",
      "d": "D",
      "|": "\"",
      "+": ";",
      ";": ":",
      "C": "c",
      "c": "C",
      "Q": "q",
      "q": "Q"
    },
    "physical": true
  },
  "mpf2": {
    "charMap": {
      "=": "O",
      "-": "I",
      "+": "P",
      "(": "*",
      ")": "(",
      "*": ")",
      "\"": "@",
      "&": "^",
      "'": "&",
      ":": ";",
      ";": ":",
      "/": "?",
      "?": "/",
      "^": "K",
      "@": "L",
      "A": "a",
      "B": "b",
      "C": "c",
      "D": "d",
      "E": "e",
      "F": "f",
      "G": "g",
      "H": "h",
      "I": "i",
      "J": "j",
      "K": "k",
      "L": "l",
      "M": "m",
      "N": "n",
      "O": "o",
      "P": "p",
      "Q": "q",
      "R": "r",
      "S": "s",
      "T": "t",
      "U": "u",
      "V": "v",
      "W": "w",
      "X": "x",
      "Y": "y",
      "Z": "z"
    },
    "letterCase": "upper-only",
    "physical": true
  },
  "msx2": {
    "charMap": {}
  },
  "msxturbor": {
    "charMap": {
      "\"": "@",
      "&": "^",
      "'": "&",
      "(": "*",
      ")": "(",
      ":": "'",
      "*": "\"",
      "+": ":",
      "=": "_",
      "@": "[",
      "[": "]",
      "]": "\\",
      "^": "=",
      "`": "{",
      "\\": "`",
      "|": "~",
      "{": "}",
      "}": "|",
      "~": "+"
    },
    "physical": true
  },
  "pet2001": {
    "letterCase": "upper-only"
  },
  "samcoupe": {
    "charMap": {
      "=": "[",
      "+": "=",
      "*": "+",
      ":": "'",
      "\"": "]",
      "/": "_",
      "_": "{",
      "(": "*",
      ")": "(",
      "&": "^",
      "'": "&",
      "~": ")",
      "\\": "?"
    },
    "physical": true
  },
  "svi328": {
    "charMap": {
      ":": ";",
      ";": ":",
      "~": "|"
    },
    "physical": true
  },
  "svi328cpm": {
    "charMap": {
      ":": ";",
      ";": ":",
      "~": "|"
    },
    "physical": true
  },
  "svi728": {
    "charMap": {}
  },
  "svi738": {
    "charMap": {}
  },
  "symbos": {
    "charMap": {
      "'": "`",
      "`": "'",
      "\"": "~",
      "~": "\""
    },
    "physical": true
  },
  "vic20": {
    "letterCase": "upper-only"
  },
  "zxspectrum": {
    "letterCase": "upper-only"
  }
} as const satisfies Record<string, GuestKeyboard>;

export function keyboardFor(osId: string): GuestKeyboard | undefined {
  return KEYBOARDS[osId as keyof typeof KEYBOARDS];
}
