// DO NOT EDIT — generated by scripts/tiles-registry.py generate from
// registry/tiles/*.json + registry/registry-v1.json; run `make tile-registry-generate`.
import type { VMManifestEntry } from '../types';
import { OS_BINDINGS } from '../three/archetypeRegistry';

// ============================================================================
//  MUSEUM CATALOG — placard metadata for the full OS lineup (41 bindings)
//  ---------------------------------------------------------------------------
//  TODAY'S ARCHITECTURE: 39 of the museum's exhibits are streamhost tiles —
//  QEMU (or emulator-bridge) guests streamed by the Rust streamhost daemon over
//  WebTransport + WebCodecs. 36 of those 39 have their placard entries in this
//  file; the trio (freedos/kolibrios/toaruos) come from the bundled base
//  manifest + data/catalog.ts. The three non-streamhost bindings are all
//  showcase posters (art + placard, no live connection attempt):
//    - win11  — its backing VM was deleted along with the legacy neko host
//      that fronted it over RDP,
//    - macos  — VM 925 and its VNC->WebSocket bridge were destroyed 2026-07-14,
//    - riscos — RISC OS is ARM/RPCEmu, so it has had no QEMU streamhost tile
//      since the neko plane was retired.
//  This file provides rich, period-accurate placard metadata for its 38 entries
//  so all 41 exhibits render, each with an era-accurate archetype + accent.
//
//  mergeCatalog() overlays the bundled base manifest (the trio's core rows) on
//  top of these entries, so every osId in OS_BINDINGS becomes an exhibit.
// ============================================================================

// Curated, period-accurate metadata for every non-trio exhibit. The trio
// (freedos/kolibrios/toaruos) come from the bundled base manifest + data/catalog.ts.
const ENTRIES: VMManifestEntry[] = [
  {
    id: 'win311', displayName: 'Windows 3.11', year: 1993,
    lineage: 'MS-DOS + Windows 3.x', arch: 'i386', ramMB: 16,    era: '1990s', accent: '#7fb0d6',
    eraSoftware: ['Program Manager', 'File Manager', 'Write', 'Paintbrush'],
    periodBrowser: 'Mosaic / early Netscape',
    iconicApps: ['Solitaire', 'Minesweeper', 'Reversi'],
    blurb: 'Windows for Workgroups — the tiled Program Manager era, riding on top of DOS.',
  },
  {
    id: 'win95', displayName: 'Windows 95', year: 1995,
    lineage: 'Windows 9x', arch: 'i386', ramMB: 64,    era: '1990s', accent: '#2f8f5b',
    eraSoftware: ['Start menu', 'Explorer', 'Internet Explorer 1', 'Notepad'],
    periodBrowser: 'Internet Explorer / Netscape Navigator',
    iconicApps: ['Minesweeper', 'FreeCell', 'Hover!'],
    blurb: 'The Start button that changed everything — the desktop metaphor that defined a decade.',
  },
  {
    id: 'win98se', displayName: 'Windows 98 SE', year: 1999,
    lineage: 'Windows 9x', arch: 'i386', ramMB: 96,    era: '1990s', accent: '#3a7fc9',
    eraSoftware: ['Active Desktop', 'IE5', 'Outlook Express', 'Media Player 6'],
    periodBrowser: 'Internet Explorer 5',
    iconicApps: ['3D Pinball Space Cadet', 'Minesweeper', 'Solitaire'],
    blurb: 'The polished peak of the 9x line — USB, Active Desktop, and Space Cadet pinball.',
  },
  {
    id: 'win2000', displayName: 'Windows 2000', year: 2000,
    lineage: 'Windows NT 5.0', arch: 'i386', ramMB: 128,    era: '2000s', accent: '#5b6fc9',
    eraSoftware: ['NTFS', 'Active Directory', 'IE5.5', 'MMC'],
    periodBrowser: 'Internet Explorer 5.5',
    iconicApps: ['Pinball', 'Solitaire', 'Paint'],
    blurb: 'NT stability meets the 9x desktop — the professional workstation of the millennium.',
  },
  {
    id: 'winxp', displayName: 'Windows XP', year: 2001,
    lineage: 'Windows NT 5.1', arch: 'i386', ramMB: 256,    era: '2000s', accent: '#5aa832',
    eraSoftware: ['Luna theme', 'IE6', 'Windows Media Player 8', 'Movie Maker'],
    periodBrowser: 'Internet Explorer 6',
    iconicApps: ['Bliss wallpaper', 'Pinball', 'Solitaire'],
    blurb: 'Bliss. The green hill and blue taskbar the whole world remembers.',
  },
  {
    id: 'nt351', displayName: 'Windows NT 3.51', year: 1995,
    lineage: 'Windows NT 3.x', arch: 'i386', ramMB: 64,    era: '1990s', accent: '#3a6ea5',
    eraSoftware: ['Program Manager', 'File Manager', 'Control Panel', 'Paintbrush'],
    periodBrowser: 'Internet Explorer 2 / early Netscape',
    iconicApps: ['Program Manager', 'File Manager', 'Minesweeper'],
    blurb: 'The last workstation NT built around Program Manager — compact, blue, and unmistakably mid-1990s.',
  },
  {
    id: 'win11', displayName: 'Windows 11', year: 2021,
    lineage: 'Windows NT 10.0', arch: 'x86_64', ramMB: 4096,    era: '2020s', accent: '#2d9bd6',
    eraSoftware: ['Centered taskbar', 'Edge', 'Fluent design', 'Widgets'],
    periodBrowser: 'Microsoft Edge (Chromium)',
    iconicApps: ['Snipping Tool', 'Terminal', 'Solitaire Collection'],
    blurb: 'The rounded, centered present day, running on the same wall as the machines it descends from.',
  },
  {
    id: 'alpine', displayName: 'Alpine Linux', year: 2005,
    lineage: 'musl + BusyBox Linux', arch: 'x86_64', ramMB: 256,    era: '2000s', accent: '#0d597f',
    eraSoftware: ['apk', 'OpenRC', 'BusyBox', 'musl libc'],
    periodBrowser: 'no default GUI browser (server distro)',
    iconicApps: ['ash shell', 'vi', 'doas'],
    blurb: 'The tiny, security-focused distro that quietly runs half the containers on Earth.',
  },
  {
    id: 'tinycore', displayName: 'Tiny Core Linux', year: 2009,
    lineage: 'BusyBox Linux', arch: 'i386', ramMB: 128,    era: '2000s', accent: '#4a9fd6',
    eraSoftware: ['FLTK/FLWM desktop', 'tce-load', 'BusyBox'],
    periodBrowser: 'dillo / Firefox extension',
    iconicApps: ['App Browser', 'Terminal', 'Text editor'],
    blurb: 'A complete graphical Linux in ~16 MB — the whole OS lives in RAM.',
  },
  {
    id: 'ninefront', displayName: '9front (Plan 9)', year: 2011,
    lineage: 'Plan 9 from Bell Labs', arch: 'x86_64', ramMB: 512,    era: '2010s', accent: '#c9c05b',
    eraSoftware: ['rio', 'acme', 'stats', 'catclock', 'rc shell', '9P'],
    periodBrowser: 'mothra / abaco',
    iconicApps: ['acme editor', 'stats', 'catclock', 'rio windows', 'sam'],
    blurb: 'Bell Labs’ successor to Unix, still alive — everything is a file, over the network.',
  },
  {
    id: 'helenos', displayName: 'HelenOS', year: 2006,
    lineage: 'Microkernel multiserver OS', arch: 'x86_64', ramMB: 512,    era: '2000s', accent: '#b58fd6',
    eraSoftware: ['spartan microkernel', 'HelenOS GUI', 'bdsh shell'],
    periodBrowser: 'no period browser (research OS)',
    iconicApps: ['Terminal', 'Calculator', 'Viewer'],
    blurb: 'A from-scratch microkernel research OS — a whole desktop built on message passing.',
  },
  {
    id: 'solaris', displayName: 'Solaris CDE', year: 1994,
    lineage: 'SunOS / System V Unix', arch: 'SPARC', ramMB: 512,    era: '1990s', accent: '#d68a3a',
    eraSoftware: ['CDE (Common Desktop Environment)', 'dtterm', 'OpenWindows'],
    periodBrowser: 'HotJava / early Netscape',
    iconicApps: ['Front Panel', 'File Manager', 'dtterm'],
    blurb: 'The workstation Unix of the 90s — CDE’s front panel on classic Sun hardware.',
  },
  {
    id: 'serenityos', displayName: 'SerenityOS', year: 2018,
    lineage: 'From-scratch Unix-like', arch: 'x86_64', ramMB: 1024,    era: '2010s', accent: '#c95a8f',
    eraSoftware: ['LibGUI desktop', 'Ladybird browser', 'Assistant', 'Terminal'],
    periodBrowser: 'Ladybird',
    iconicApps: ['Solitaire', 'Minesweeper', 'PixelPaint'],
    blurb: 'A love letter to the late-90s desktop, written entirely from scratch on YouTube.',
  },
  {
    id: 'android', displayName: 'Android', year: 2008,
    lineage: 'Linux (AOSP)', arch: 'ARM / x86', ramMB: 2048,    era: '2000s', accent: '#3ddc84',
    eraSoftware: ['Launcher', 'WebView', 'Dalvik/ART', 'Play-era apps'],
    periodBrowser: 'Android Browser / Chrome',
    iconicApps: ['Maps', 'Camera', 'Messaging'],
    blurb: 'The pocket Linux that ate the world — the original touchscreen candybar.',
  },
  {
    id: 'postmarketos', displayName: 'postmarketOS', year: 2017,
    lineage: 'Alpine Linux mobile', arch: 'ARM', ramMB: 2048,    era: '2010s', accent: '#008b4b',
    eraSoftware: ['Phosh / Plasma Mobile', 'apk', 'PulseAudio'],
    periodBrowser: 'Firefox / GNOME Web',
    iconicApps: ['Phosh shell', 'Terminal', 'Settings'],
    blurb: 'Real mainline Linux on the phone — a ten-year lifecycle for the PinePhone era.',
  },
  {
    id: 'sailfishos', displayName: 'Sailfish OS', year: 2013,
    lineage: 'Mer / MeeGo (Jolla)', arch: 'ARM', ramMB: 2048,    era: '2010s', accent: '#e60d42',
    eraSoftware: ['Lipstick UI', 'Silica', 'Android app support'],
    periodBrowser: 'Sailfish Browser (Gecko)',
    iconicApps: ['Gesture deck', 'Clock', 'Media'],
    blurb: 'MeeGo’s heir from Jolla — the gesture-driven Nordic take on the smartphone.',
  },
  {
    id: 'templeos', displayName: 'TempleOS', year: 2013,
    lineage: 'Terry A. Davis / from-scratch', arch: 'x86_64', ramMB: 1024,    era: '2010s', accent: '#f2c14e',
    eraSoftware: ['HolyC', 'The Oracle', 'After Egypt', 'built-in editor'],
    periodBrowser: 'none — no networking by design',
    iconicApps: ['HolyC REPL', 'The Oracle', 'After Egypt'],
    blurb: 'Terry Davis’ divine 640x480 16-colour temple — a ring-0, single-address-space OS written from scratch in HolyC.',
    notes: 'Live streamhost tile. PS/2 input only — TempleOS has no USB stack. Ring-0, single-address-space, no networking by design; CD-only ephemeral live boot.',
  },
  {
    id: 'macos', displayName: 'macOS Sequoia', year: 2024,
    lineage: 'Darwin / XNU', arch: 'arm64', ramMB: 8192,    era: '2020s', accent: '#a0a0a8',
    eraSoftware: ['Aqua', 'Finder', 'Safari', 'Continuity'],
    periodBrowser: 'Safari',
    iconicApps: ['Finder', 'Launchpad', 'Terminal'],
    blurb: 'The modern Apple desktop on a Studio Display — currently a showcase poster awaiting a rebuilt guest.',
    notes: 'Showcase poster: VM 925 (the macOS guest) and the VNC->WebSocket bridge that fronted it were destroyed on 2026-07-14, so there is nothing to connect to; a rebuilt macOS tile is the pending fix.',
  },

  // ---- 7 newest gallery OSes ----
  {
    id: 'reactos', displayName: 'ReactOS 0.4.14', year: 2024,
    lineage: 'Windows NT / ReactOS', arch: 'i386', ramMB: 512,    era: '2020s', accent: '#2f6fba',
    eraSoftware: ['ReactOS Explorer', 'Start menu / taskbar', 'App Manager', 'ReactOS Shell'],
    periodBrowser: 'no bundled browser (NT 5.x live CD)',
    iconicApps: ['ReactOS Explorer', 'Command Prompt', 'App Manager', 'Winefile'],
    blurb: 'The open-source Windows-2000 — a from-scratch, binary-compatible reimplementation of the NT 5.x kernel and Win32.',
    notes: 'Live streamhost tile. ReactOS 0.4.14 live CD (0.4.15 hangs QEMU 11 kernel init). Archetype: beige-tower-crt (a Windows-2000-era beige tower is the right period fit).',
  },
  {
    id: 'haiku', displayName: 'Haiku R1/beta5', year: 2024,
    lineage: 'Be Inc. BeOS → Haiku', arch: 'x86_64', ramMB: 2048,    era: '2020s', accent: '#ffca3a',
    eraSoftware: ['Tracker', 'Deskbar', 'the yellow window tabs', 'HaikuDepot'],
    periodBrowser: 'WebPositive',
    iconicApps: ['Tracker', 'Deskbar', 'WebPositive', 'HaikuDepot'],
    blurb: 'The MIT-licensed, still-maintained successor to BeOS — the iconic yellow window tabs, faithfully reborn.',
    notes: 'Live streamhost tile. Official haiku-r1beta5 anyboot live CD. Archetype: beige-tower-crt; a bespoke BeBox (the dual-CPU BeOS workstation) would be the ideal era-accurate model.',
  },
  {
    id: 'os2warp', displayName: 'OS/2 Warp 4', year: 1996,
    lineage: 'IBM/Microsoft OS/2', arch: 'i386', ramMB: 256,    era: '1990s', accent: '#1e5aa8',
    eraSoftware: ['Workplace Shell', 'LaunchPad', 'WebExplorer', 'System Editor'],
    periodBrowser: 'IBM WebExplorer',
    iconicApps: ['Workplace Shell', 'LaunchPad', 'WebExplorer'],
    blurb: 'IBM’s 1996 "Merlin" — the object-oriented Workplace Shell that was famously "a better DOS than DOS, a better Windows than Windows".',
    notes: 'Live streamhost tile at 1024x768x64k (IBM GENGRADD on QEMU std VGA). Runs under TCG — it broke under KVM and was reverted — but remains fully interactive. Archetype: beige-tower-crt.',
  },
  {
    id: 'aros', displayName: 'AROS', year: 2024,
    lineage: 'Commodore Amiga → AROS', arch: 'i386', ramMB: 256,    era: '2020s', accent: '#e87a17',
    eraSoftware: ['Workbench', 'Wanderer desktop', 'RAM Disk', 'AmigaDOS'],
    periodBrowser: 'no bundled browser (live CD)',
    iconicApps: ['Workbench', 'Wanderer', 'AmigaDOS shell'],
    blurb: 'The free, from-scratch AmigaOS — Wanderer brings back the Workbench desktop with no copyrighted Kickstart ROM required.',
    notes: 'Live streamhost tile. Official AROS pc-i386 live CD. Archetype: beige-tower-crt; a bespoke Amiga wedge (the low-profile Amiga 500/1200 keyboard-box) would be the ideal era-accurate model.',
  },
  {
    id: 'riscos', displayName: 'RISC OS 5.30', year: 2022,
    lineage: 'Acorn RISC OS', arch: 'ARM', ramMB: 256,    era: '2020s', accent: '#4a7c3a',
    eraSoftware: ['icon bar', 'pinboard', 'Filer', '!Draw'],
    periodBrowser: 'NetSurf',
    iconicApps: ['icon bar + pinboard', '!Draw', '!Paint', 'StrongED'],
    blurb: 'Acorn’s ARM desktop, still shipping from RISC OS Open — the icon bar and pinboard that defined British computing.',
    notes: 'Showcase poster: RISC OS is ARM (the retired tile ran RPCEmu, not QEMU), so it has had no streamhost tile since the neko plane was deleted — poster + placard only for now. ROOL 5.30 softload ROM + HardDisc4. Archetype: beige-tower-crt; a bespoke Acorn RiscPC (the stackable slab that ran RISC OS) would be the ideal era-accurate model.',
  },
  {
    id: 'qnx', displayName: 'QNX Neutrino 6.5', year: 2010,
    lineage: 'QNX/BlackBerry', arch: 'i386', ramMB: 256,    era: '2010s', accent: '#1b6fb5',
    eraSoftware: ['Photon microGUI', 'the app shelf', 'pterm', 'Voyager'],
    periodBrowser: 'Voyager',
    iconicApps: ['Photon microGUI', 'the app shelf', 'Voyager'],
    blurb: 'A hard-real-time microkernel OS whose Photon microGUI once fit a web browser and a whole desktop onto a single floppy.',
    notes: 'Live streamhost tile with a true 1:1 relative mouse — the guest owns a PS/2 pointer, so under pointer lock the SPA ships raw deltas straight to it. QNX 6.5.0 self-hosting live CD. Archetype: putty-lcd (early-2000s embedded/industrial panel-PC fit).',
  },
  {
    id: 'msdoswin1', displayName: 'MS-DOS 6.22 + Windows 1.0', year: 1994,
    lineage: 'Microsoft MS-DOS / Windows', arch: 'i386', ramMB: 16,    era: '1990s', accent: '#c8a24a',
    eraSoftware: ['COMMAND.COM', 'MS-DOS Executive', 'EDIT', 'QBASIC'],
    periodBrowser: 'none — pre-web (1985/1994)',
    iconicApps: ['COMMAND.COM', 'Windows 1.0 tiled windows', 'EDIT', 'QBASIC'],
    blurb: 'The C:\\> prompt of MS-DOS 6.22 (1994) with Microsoft’s first Windows 1.0 (1985) layered on top — the tiled-window dawn before the desktop metaphor.',
    notes: 'Live streamhost tile. One combined image: boots MS-DOS 6.22 to C:\\> and launches Windows 1.01 via WIN — presented here as a single exhibit. Archetype: beige-ibm-pc (the boxy DOS-era CRT + IBM-PC fit).',
  },

  // ---- emulator-bridge retro home computers ----
  {
    id: 'c64', displayName: 'Commodore 64 — GEOS 2.0', year: 1982,
    lineage: 'Commodore 64 / GEOS',
    arch: 'MOS 6510 (6502), 1 MHz, 64 KB', ramMB: 0, ramKB: 64,    era: '1980s', accent: '#6c5eb5',
    eraSoftware: ['GEOS 2.0 deskTop', 'geoWrite', 'geoPaint', 'Preference Manager', 'the 1541 drive'],
    periodBrowser: 'none — pre-web 8-bit era',
    iconicApps: ['GEOS deskTop', 'geoWrite', 'geoPaint', 'the 1541 disk drive'],
    blurb: 'A full windows-icons-menus desktop (GEOS) running on a 1 MHz, 64 KB home computer — the 8-bit era’s answer to the Macintosh.',
    notes: 'Live streamhost tile. Emulator-in-captured-Linux BRIDGE tile: a captured Debian 12 kiosk runs VICE (x64sc) full-screen emulating a C64 that auto-boots the GEOS 2.0 deskTop; streamhost captures the Linux framebuffer + AC97 audio (the C64 SID routed through ALSA) exactly like every other tile. archetype beige-tower-crt (ideal: a bespoke C64 breadbin + 1541 + CRT). See streamhost/docs/BRIDGE.md.',
  },
  {
    id: 'atarist', displayName: 'Atari ST (EmuTOS GEM)', year: 1985,
    lineage: 'Atari ST / Digital Research GEM',
    arch: 'Motorola 68000 (m68k)', ramMB: 0, ramKB: 1024,    era: '1980s', accent: '#E4002B',
    eraSoftware: ['GEM desktop (TOS)', 'NEODESK', 'Cubase / Notator (MIDI)', 'Degas Elite', 'First Word / First Word Plus'],
    periodBrowser: 'none — pre-web 16-bit era',
    iconicApps: ['GEM desktop (DISK A/B, TRASH, PRINTER)', 'GEM file manager', 'Atari BASIC / GFA BASIC', 'Cubase MIDI sequencer'],
    blurb: 'The 16-bit “Jackintosh” — a 68000 with the GEM windows-icons-menus desktop and built-in MIDI, shown here booting the open-source EmuTOS straight to the classic monochrome GEM desktop.',
    notes: 'Live streamhost tile. Emulator-in-captured-Linux BRIDGE tile: a captured Debian 12 kiosk runs the hatari Atari ST emulator full-screen (EmuTOS → GEM desktop); streamhost captures the Linux framebuffer + AC97 audio like every other tile. archetype beige-tower-crt (ideal: a bespoke Atari ST wedge). See streamhost/docs/BRIDGE.md.',
  },
  {
    id: 'apple2', displayName: 'Apple II — GEOS', year: 1988,
    lineage: 'Apple II / GEOS',
    arch: 'MOS 65C02 (Apple //e enhanced), 1 MHz, 128 KB', ramMB: 0, ramKB: 128,    era: '1980s', accent: '#8A8577',
    eraSoftware: ['Apple GEOS deskTop', 'geoWrite', 'geoPaint', 'ProDOS', 'DeskTop file manager'],
    periodBrowser: 'none — pre-web 8-bit era',
    iconicApps: ['geoWrite', 'geoPaint', 'GEOS deskTop', 'Preference Manager'],
    blurb: 'A windows-icons-menus desktop (GEOS) with geoWrite & geoPaint running on a 1 MHz Apple //e — the 8-bit era’s Macintosh, on Apple hardware.',
    notes: 'Live streamhost tile. Emulator-in-captured-Linux BRIDGE tile: a captured Debian 12 kiosk runs an Apple //e emulator full-screen booting Apple GEOS; streamhost captures the Linux framebuffer + AC97 audio like every other tile. archetype beige-tower-crt (ideal: a bespoke platinum Apple //e all-in-one). See streamhost/docs/BRIDGE.md.',
  },
  {
    id: 'amiga', displayName: 'Amiga 500 — Workbench 1.3', year: 1987,
    lineage: 'Commodore Amiga / AmigaOS',
    arch: 'Motorola 68000 (16/32-bit)', ramMB: 0, ramKB: 512,    era: '1980s', accent: '#0055AA',
    eraSoftware: ['Workbench 1.3', 'AmigaDOS CLI', 'Deluxe Paint', 'Extras 1.3 / AmigaBASIC'],
    periodBrowser: 'none — pre-web (AmigaOS 1.3)',
    iconicApps: ['Workbench 1.3 desktop', 'AmigaDOS Shell/CLI', 'the insert-disk hand', 'the floppy-drive click'],
    blurb: 'A 1987 home computer whose custom chips (blitter + copper + 4-channel Paula sound) gave it colour multitasking and arcade graphics the PC and Mac couldn’t touch for years — booting the real Kickstart 1.3 + Workbench 1.3 on a genuine 68000.',
    notes: 'Live streamhost tile. Emulator-in-captured-Linux BRIDGE tile: a captured Debian 12 kiosk runs an Amiga emulator full-screen booting the real Kickstart 1.3 + Workbench 1.3; streamhost captures the Linux framebuffer + AC97 audio like every other tile. archetype beige-tower-crt (ideal: a bespoke Amiga 500 wedge). See streamhost/docs/BRIDGE.md.',
  },
  {
    id: 'redstar2', displayName: 'Red Star OS 2.0', year: 2009,
    lineage: 'Linux (Red Hat/Fedora lineage)', arch: 'i386', ramMB: 1024,    era: '2000s', accent: '#c8102e',
    eraSoftware: ['KDE 3.5', 'Naenara', 'Uri 2.0', 'OpenOffice.org'],
    periodBrowser: 'Naenara (Firefox-derived)',
    iconicApps: ['Naenara', 'Uri 2.0 office suite', 'KDE Control Center'],
    blurb: 'A preserved KDE-era North Korean desktop distribution, presented offline with no network hardware.',
  },
  {
    id: 'redstar3', displayName: 'Red Star OS 3.0 Desktop', year: 2013,
    lineage: 'Linux (Fedora lineage)', arch: 'i386', ramMB: 1024,    era: '2010s', accent: '#b3202a',
    eraSoftware: ['KDE desktop', 'Naenara browser', 'Red Star file manager', 'system tools'],
    periodBrowser: 'Naenara (Firefox-derived)',
    iconicApps: ['Naenara', 'File Manager', 'System Preferences'],
    blurb: 'A macOS-styled desktop distribution from the DPRK: Fedora/KDE foundations reshaped into a tightly controlled national-computing environment.',
    notes: 'Private air-gapped preservation exhibit. The guest has no emulated network interface.',
  },
  {
    id: 'amstradcpc', displayName: 'Amstrad CPC 6128 — Locomotive BASIC', year: 1985,
    lineage: 'Amstrad CPC / Locomotive BASIC',
    arch: 'Zilog Z80A, 4 MHz, 128 KB', ramMB: 0, ramKB: 128,    era: '1980s', accent: '#F0C000',
    eraSoftware: ['Locomotive BASIC 1.1', 'AMSDOS / CP/M Plus', 'Protext', 'The Advanced OCP Art Studio', 'CPC games (Head over Heels, Chase H.Q.)'],
    periodBrowser: 'none — pre-web 8-bit era',
    iconicApps: ['Locomotive BASIC', 'AMSDOS', 'CP/M Plus', 'The Advanced OCP Art Studio'],
    blurb: 'The British 8-bit all-in-one — an integrated Z80 micro with monitor and disk drive that boots to the iconic yellow-on-blue Locomotive BASIC Ready prompt.',
    notes: 'Live streamhost tile. Emulator-in-captured-Linux BRIDGE tile: a captured Debian 12 kiosk runs Caprice32 (cap32) in a verified scale-3 SDL/X11 window emulating an Amstrad CPC 6128 that boots Locomotive BASIC; streamhost captures the Linux framebuffer + AC97 audio (the CPC AY-3-8912 routed through ALSA) exactly like every other tile. archetype beige-tower-crt (ideal: a bespoke CPC 6128 + CTM monitor). See streamhost/docs/BRIDGE.md.',
  },
  {
    id: 'nt4', displayName: 'Windows NT 4.0', year: 1996,
    lineage: 'Windows NT 4.0', arch: 'i386', ramMB: 128,    era: '1990s', accent: '#1f7a7a',
    eraSoftware: ['Explorer shell', 'Internet Explorer 2.0', 'Solitaire', 'Paint'],
    periodBrowser: 'Internet Explorer 2.0',
    iconicApps: ['Solitaire', 'Minesweeper', 'Paint'],
    blurb: 'The classic Explorer shell on the NT kernel. The teal desktop that brought the Windows 95 look to enterprise NT.',
  },
  {
    id: 'openvms', displayName: 'OpenVMS x86-64 9.2 — DECwindows', year: 2024,
    lineage: 'VMS / OpenVMS', arch: 'x86_64', ramMB: 8960,    era: '2020s', accent: '#00a6d6',
    eraSoftware: ['DECwindows Motif', 'DCL', 'FileView', 'DECterm'],
    periodBrowser: 'none — DECwindows desktop exhibit',
    iconicApps: ['DECterm', 'FileView', 'Clock', 'Calculator'],
    blurb: 'The durable VMS lineage on modern x86-64, presented as its classic network-transparent DECwindows Motif desktop.',
    notes: 'A two-VM graphical bridge: OpenVMS supplies MWM and the applications while a private lean-X Debian guest supplies only the captured Xorg scanout and absolute tablet input.',
  },
  {
    id: 'irix', displayName: 'SGI Indy — IRIX 6.5', year: 1993,
    lineage: 'SGI IRIX / System V Unix',
    arch: 'MIPS R4600 (MIPS III, 64-bit)', ramMB: 256,    era: '1990s', accent: '#5B8FA8',
    eraSoftware: ['Indigo Magic Desktop (4Dwm)', 'IRIX Interactive Desktop / toolchest', 'showcasedemos (gr_osview, buttonfly)', 'WorldView / SGI demos', 'Netscape for IRIX'],
    periodBrowser: 'Netscape Navigator / Communicator for IRIX',
    iconicApps: ['4Dwm Indigo Magic teal desktop', 'the SGI toolchest', 'IconCatalog', 'File System Navigator'],
    blurb: 'SGI’s 1993 Indy brought real workstation Unix — 64-bit MIPS, hardware 24-bit graphics, and the gorgeous teal Indigo Magic Desktop — to a friendly blue pizza-box. IRIX 6.5 was the definitive SGI Unix, booting to the 4Dwm desktop.',
    notes: 'Live streamhost tile — the FIRST non-QEMU tile: an Xvfb + MAME(indy_4610) emulator captured directly by streamhost’s SH_CAPTURE=shm backend (MAME’s SGI Indy emulation kernel-panics under a KVM vCPU, so it runs on the bare-metal CPU, not a QEMU VM). archetype beige-tower-crt. See docs/history/irix-tile-issue20-handoff.md.',
  },
  {
    id: 'mpf2', displayName: 'Multitech Microprofessor II — MPF-II BASIC', year: 1982,
    lineage: 'Multitech / Apple II clone',
    arch: 'MOS 6502, 1 MHz, 64 KB RAM, 16 KB ROM', ramMB: 0, ramKB: 64,    era: '1980s', accent: '#8B4513',
    eraSoftware: ['MPF-II BASIC in ROM', 'the built-in machine-language monitor', 'cassette titles: Blitz, Snake, Head On, Reverse, Sabotage', 'type-in listings from the computer magazines'],
    periodBrowser: 'none — pre-web 8-bit era',
    iconicApps: ['MPF-II BASIC', 'the machine-language monitor'],
    blurb: 'Taiwan\'s first mass-market home computer — a chiclet-keyboard Apple II clone that boots straight to BASIC, in 6 colours on a television set.',
    notes: 'Live streamhost tile. Emulator-in-captured-Linux BRIDGE tile: a captured Debian 12 kiosk runs MAME (mpf2 driver) emulating a Multitech MPF-II that boots its ROM BASIC; streamhost captures the Linux framebuffer + AC97 audio exactly like every other tile. Keyboard-only exhibit (no pointing device — the real machine had none); uses the beige-tower-crt fallback until a bespoke MPF-II archetype exists. See streamhost/docs/BRIDGE.md and docs/guests/mpf2.md.',
  },
  {
    id: 'vic20', displayName: 'Commodore VIC-20 — CBM BASIC V2', year: 1980,
    lineage: 'Commodore 8-bit (MOS 6502)',
    arch: 'MOS 6502, 1.108 MHz (PAL), 5 KB RAM, 20 KB ROM', ramMB: 0, ramKB: 5,    era: '1980s', accent: '#3FBFC7',
    eraSoftware: ['CBM BASIC V2 in ROM', 'cartridge games: Jelly Monsters, Radar Rat Race, Gorf, Omega Race', 'Scott Adams text adventures on cassette', 'the VIC-1530 Datasette and the VIC-1541 disk drive', 'type-in listings from Compute!’s Gazette'],
    periodBrowser: 'none — pre-web 8-bit era',
    iconicApps: ['CBM BASIC V2', 'VIC-20 cartridge games', 'the Datasette'],
    blurb: 'The first computer of any kind to sell a million: 5 KB of memory, 22 columns of blue text on a television set, and William Shatner asking why you would buy just a video game.',
    notes: 'Live streamhost tile. Emulator-in-captured-Linux BRIDGE tile: a captured Debian 12 kiosk runs VICE (xvic) emulating a PAL VIC-20 that boots its ROM to the CBM BASIC V2 READY prompt; streamhost captures the Linux framebuffer + AC97 audio (the VIC-I sound routed through ALSA) exactly like every other tile. VICE is already in the frozen bridge base (built from source for the c64 tile) and bundles the Commodore ROMs, so this tile needs no external media at all. Keyboard-only exhibit (the machine’s other input was a joystick); uses the beige-tower-crt fallback until a bespoke VIC-20 archetype exists. See streamhost/docs/BRIDGE.md and docs/guests/vic20.md.',
  },
  {
    id: 'plus4', displayName: 'Commodore Plus/4 — 3-plus-1 in ROM', year: 1984,
    lineage: 'Commodore 264 series (MOS 7501, TED)',
    arch: 'MOS 7501, 1.77 MHz (PAL), 64 KB RAM, 32 KB application ROM', ramMB: 0, ramKB: 64,    era: '1980s', accent: '#C2CF5F',
    eraSoftware: ['3-plus-1: a word processor, spreadsheet, database and graphing package, in ROM', 'Commodore BASIC V3.5, with a machine-language monitor built in', 'the 264-series cartridges and the 1531 Datasette', 'a small, mostly European software scene it never grew out of'],
    periodBrowser: 'none — pre-web 8-bit era',
    iconicApps: ['the 3-plus-1 word processor', 'the 3-plus-1 spreadsheet', 'Commodore BASIC V3.5'],
    blurb: 'Commodore’s misfire, and the reason it is worth looking at: an office suite — word processor, spreadsheet, database, graphing — burned into ROM and running one second after you switch the machine on, with no disk in sight.',
    notes: 'Live streamhost tile. Emulator-in-captured-Linux BRIDGE tile: a captured Debian 12 kiosk runs VICE (xplus4) emulating a PAL Plus/4; streamhost captures the Linux framebuffer + AC97 audio exactly like every other tile. VICE bundles the Commodore ROMs INCLUDING both 3-plus-1 banks, so this tile needs no external media. The golden is curated INTO the suite (F1+RETURN, then C= C and tc) and rests in the spreadsheet. The suite’s command prompt is one-shot — C= + C opens it, one command runs, it closes — so module switching needs the Commodore key (Tab under VICE’s symbolic keymap); the SPA’s plus4 on-screen keyboard therefore carries one-tap Word/Calc/File buttons that send the whole sequence. Keyboard-only exhibit; beige-tower-crt fallback archetype. See streamhost/docs/BRIDGE.md and docs/guests/plus4.md.',
  },
];

// Fast lookup.
const BY_ID: Record<string, VMManifestEntry> = Object.fromEntries(
  ENTRIES.map((e) => [e.id, e]),
);

/**
 * Merge the bundled base manifest (the freedos/kolibrios/toaruos rows, passed
 * in by useManifest) with this catalog, so EVERY osId in OS_BINDINGS becomes an
 * exhibit. Base entries win on any field they define — the catalog fills the
 * rest and supplies all the non-trio exhibits.
 */
export function mergeCatalog(base: VMManifestEntry[]): VMManifestEntry[] {
  const baseById: Record<string, VMManifestEntry> = Object.fromEntries(
    base.map((e) => [e.id, e]),
  );

  // One exhibit per osId declared in the binding registry (the source of truth
  // for the lineup), deduped. Prefer base-manifest data, then catalog, then a
  // minimal stub so an unmapped binding still renders rather than vanishing.
  return Object.keys(OS_BINDINGS).map((osId) => {
    const baseEntry = baseById[osId];
    const catalogEntry = BY_ID[osId];
    if (baseEntry && catalogEntry) return { ...catalogEntry, ...baseEntry };
    if (baseEntry) return baseEntry;
    if (catalogEntry) return catalogEntry;
    const b = OS_BINDINGS[osId];
    return {
      id: osId,
      displayName: osId,
      year: parseInt(b.eraLabel, 10) || 2000,
      lineage: b.eraLabel,
      arch: 'unknown',
      accent: b.accentColor,
    } satisfies VMManifestEntry;
  });
}

export const CATALOG_ENTRIES = ENTRIES;
