// DO NOT EDIT — generated by scripts/stations-registry.py generate from
// registry/posters/*.md; run `make station-registry-generate`.
// Existence + hero only — the prose is runtime data (/poster-docs.json).

const POSTER_INDEX = {
  "aix432": {
    "hero": "/posters/aix432/desktop.webp"
  },
  "alpine": {
    "hero": "/posters/alpine/desktop.webp"
  },
  "alto": {
    "hero": "/posters/alto/desktop.webp"
  },
  "amiga": {
    "hero": "/posters/amiga/desktop.webp"
  },
  "amigaos35": {
    "hero": "/posters/amigaos35/desktop.webp"
  },
  "amix": {
    "hero": "/posters/amix/desktop.webp"
  },
  "amstradcpc": {
    "hero": "/posters/amstradcpc/desktop.webp"
  },
  "android": {
    "hero": "/posters/android/desktop.webp"
  },
  "apple2": {
    "hero": "/posters/apple2/desktop.webp"
  },
  "armeval": {
    "hero": "/posters/armeval/desktop.webp"
  },
  "aros": {
    "hero": "/posters/aros/desktop.webp"
  },
  "atarist": {
    "hero": "/posters/atarist/desktop.webp"
  },
  "aux": {
    "hero": "/posters/aux/desktop.webp"
  },
  "bbcmicro": {
    "hero": "/posters/bbcmicro/desktop.webp"
  },
  "beos": {
    "hero": "/posters/beos/desktop.webp"
  },
  "bootos": {
    "hero": "/posters/bootos/desktop.webp"
  },
  "c128": {
    "hero": "/posters/c128/desktop.webp"
  },
  "c64": {
    "hero": "/posters/c64/desktop.webp"
  },
  "cbm2": {
    "hero": "/posters/cbm2/desktop.webp"
  },
  "cbm8032": {
    "hero": "/posters/cbm8032/desktop.webp"
  },
  "chokanji": {
    "hero": "/posters/chokanji/desktop.webp"
  },
  "daybreak": {
    "hero": "/posters/daybreak/desktop.webp"
  },
  "debian22": {
    "hero": "/posters/debian22/desktop.webp"
  },
  "decos": {
    "hero": "/posters/decos/desktop.webp"
  },
  "dragon32": {
    "hero": "/posters/dragon32/desktop.webp"
  },
  "freedos": {
    "hero": "/posters/freedos/desktop.webp"
  },
  "gt40": {
    "hero": "/posters/gt40/desktop.webp"
  },
  "haiku": {
    "hero": "/posters/haiku/desktop.webp"
  },
  "helenos": {
    "hero": "/posters/helenos/desktop.webp"
  },
  "hpuxvue": {
    "hero": "/posters/hpuxvue/desktop.webp"
  },
  "indyr4400": {
    "hero": "/posters/indyr4400/desktop.webp"
  },
  "irix": {
    "hero": "/posters/irix/desktop.webp"
  },
  "kc854": {
    "hero": "/posters/kc854/desktop.webp"
  },
  "kolibrios": {
    "hero": "/posters/kolibrios/desktop.webp"
  },
  "macos": {
    "hero": "/posters/macos/desktop.webp"
  },
  "macos753": {
    "hero": "/posters/macos753/desktop.webp"
  },
  "macos9": {
    "hero": "/posters/macos9/desktop.webp"
  },
  "mpf2": {
    "hero": "/posters/mpf2/desktop.webp"
  },
  "msdoswin1": {
    "hero": "/posters/msdoswin1/desktop.webp"
  },
  "newsos": {
    "hero": "/posters/newsos/desktop.webp"
  },
  "nextstep": {
    "hero": "/posters/nextstep/desktop.webp"
  },
  "ninefront": {
    "hero": "/posters/ninefront/desktop.webp"
  },
  "nt351": {
    "hero": "/posters/nt351/desktop.webp"
  },
  "nt4": {
    "hero": "/posters/nt4/desktop.webp"
  },
  "openvms": {
    "hero": "/posters/openvms/desktop.webp"
  },
  "oricatmos": {
    "hero": "/posters/oricatmos/desktop.webp"
  },
  "os2warp": {
    "hero": "/posters/os2warp/desktop.webp"
  },
  "pcgeos": {
    "hero": "/posters/pcgeos/desktop.webp"
  },
  "pdp11": {
    "hero": "/posters/pdp11/desktop.webp"
  },
  "pet2001": {
    "hero": "/posters/pet2001/desktop.webp"
  },
  "plus4": {
    "hero": "/posters/plus4/desktop.webp"
  },
  "postmarketos": {
    "hero": "/posters/postmarketos/desktop.webp"
  },
  "qnx": {
    "hero": "/posters/qnx/desktop.webp"
  },
  "ravynos": {
    "hero": "/posters/ravynos/desktop.webp"
  },
  "reactos": {
    "hero": "/posters/reactos/desktop.webp"
  },
  "redstar2": {
    "hero": "/posters/redstar2/desktop.webp"
  },
  "redstar3": {
    "hero": "/posters/redstar3/desktop.webp"
  },
  "rhapsody": {
    "hero": "/posters/rhapsody/desktop.webp"
  },
  "riscos": {
    "hero": "/posters/riscos/desktop.webp"
  },
  "sailfishos": {
    "hero": "/posters/sailfishos/desktop.webp"
  },
  "serenityos": {
    "hero": "/posters/serenityos/desktop.webp"
  },
  "sinclairql": {
    "hero": "/posters/sinclairql/desktop.webp"
  },
  "solaris": {
    "hero": "/posters/solaris/desktop.webp"
  },
  "star": {
    "hero": "/posters/star/desktop.webp"
  },
  "sunos414": {
    "hero": "/posters/sunos414/desktop.webp"
  },
  "templeos": {
    "hero": "/posters/templeos/desktop.webp"
  },
  "tinycore": {
    "hero": "/posters/tinycore/desktop.webp"
  },
  "toaruos": {
    "hero": "/posters/toaruos/desktop.webp"
  },
  "tru64": {
    "hero": "/posters/tru64/desktop.webp"
  },
  "vic20": {
    "hero": "/posters/vic20/desktop.webp"
  },
  "w2kalpha": {
    "hero": "/posters/w2kalpha/dxdiag.webp"
  },
  "win11": {
    "hero": "/posters/win11/desktop.webp"
  },
  "win2000": {
    "hero": "/posters/win2000/desktop.webp"
  },
  "win311": {
    "hero": "/posters/win311/desktop.webp"
  },
  "win95": {
    "hero": "/posters/win95/desktop.webp"
  },
  "win98se": {
    "hero": "/posters/win98se/desktop.webp"
  },
  "winxp": {
    "hero": "/posters/winxp/desktop.webp"
  },
  "zx81": {
    "hero": "/posters/zx81/desktop.webp"
  },
  "zxspectrum": {
    "hero": "/posters/zxspectrum/desktop.webp"
  }
} as const satisfies Record<string, { hero?: string }>;

export function posterFor(osId: string): { hero?: string } | undefined {
  return POSTER_INDEX[osId as keyof typeof POSTER_INDEX];
}
